// Generated by pnpm generate. Edit the sibling .mts source.
/** Portable configuration meaning. No storage, bindings, or runtime globals. */
/** The exact documents resolved for one Tower request. Shared with the
 * hosted receiver, so a private caller cannot expand a settings read. */
export declare const TOWER_CONFIG_FILES: Readonly<{
    readonly constants: "config/constants.json";
    readonly pull: "config/pull.json";
    readonly integrations: "config/integrations.json";
    readonly counters: "config/counters.json";
    readonly dashboard: "config/tower.json";
    readonly serpPanel: "config/serp-panel.json";
    readonly signalPanels: "config/signal-panels.json";
    readonly valueEvents: "config/value-events.json";
    readonly ga4EventParams: "config/ga4-custom-dimensions.json";
    readonly domainCosts: "config/domain-costs.json";
    readonly recurringCosts: "config/recurring-costs.json";
    readonly entities: "config/entities.json";
    readonly beads: "config/beads.json";
}>;
export declare const ASSET_STATUSES: readonly ["pre-launch", "onboarding", "baselining", "live", "retired"];
export type AssetStatus = (typeof ASSET_STATUSES)[number];
/**
 * A stage move is recorded as a timeline row because `assets.status` holds only
 * where an asset is; Restore reads the previous stage from the timeline. The
 * Tower and `pnpm config:apply` both write it, so both read these. The kind is
 * `config` because `annotations.kind` is a CHECK constraint and a stage is a
 * stored setting on the asset.
 */
export declare const LIFECYCLE_ANNOTATION_KIND = "config";
/** What a lifecycle-move `ref` starts with, so an operator-written ref can never
 * be mistaken for one. */
export declare const LIFECYCLE_REF_PREFIX = "lifecycle:";
/**
 * The `ref` one stage move is stored under (`lifecycle:baselining>retired`).
 * Part of the row's `(asset, at, kind, ref)` identity, so a retried write
 * collapses into one row and two moves in the same second stay two.
 */
export declare function lifecycleMoveRef(move: {
    from: AssetStatus;
    to: AssetStatus;
}): string;
export declare const STORE_COLUMNS: readonly ["status", "sense_only", "display_name"];
export type StoreColumn = (typeof STORE_COLUMNS)[number];
export declare const DISPLAY_NAME_MAX = 80;
export declare const ASSET_ID_MAX = 128;
export declare const ASSET_ID_RE: RegExp;
export declare const CONFIG_ASSET_KEY_SOURCE = "[a-z0-9][a-z0-9._-]*";
export declare const CONFIG_ASSET_KEY_RE: RegExp;
export declare const DOMAIN_RE: RegExp;
export type JsonValue = string | number | boolean | null | JsonValue[] | {
    [key: string]: JsonValue;
};
/** PostHog Cloud regions. `us` is us.posthog.com, `eu` is eu.posthog.com. */
export declare const POSTHOG_HOSTS: readonly ["us", "eu"];
export type PosthogHost = (typeof POSTHOG_HOSTS)[number];
/** A PostHog project id: digits only, as the project settings page shows it. */
export declare const POSTHOG_PROJECT_ID_SOURCE = "^[1-9][0-9]{0,11}$";
export declare const POSTHOG_FUNNEL_LIMITS: {
    readonly maxFunnels: 10;
    readonly minSteps: 2;
    readonly maxSteps: 10;
    readonly idMaxLength: 40;
    readonly nameMaxLength: 80;
    readonly eventMaxLength: 200;
    readonly pathMaxLength: 300;
};
/** A funnel id is a short kebab-case key, stable across renames of its name. */
export declare const POSTHOG_FUNNEL_ID_SOURCE = "^[a-z0-9]+(?:-[a-z0-9]+)*$";
/** An event name as PostHog stores it (`$pageview`, `form_start`, `Sign up`).
 * Quotes, backslashes, braces and control characters are refused: the
 * collector passes names as query values, and a name no site would send is
 * more likely a paste error than an event. */
export declare const POSTHOG_EVENT_NAME_SOURCE = "^[$A-Za-z0-9_][A-Za-z0-9_ .:/$-]*$";
/** A page path, compared exactly with `$pathname`: starts with `/`, no query
 * string, no fragment, no spaces. */
export declare const POSTHOG_PATH_SOURCE = "^/[A-Za-z0-9._~!$&()*+,;=:@%/-]*$";
export interface PosthogFunnelStep {
    event: string;
    path?: string;
}
export interface PosthogFunnel {
    id: string;
    name: string;
    steps: PosthogFunnelStep[];
}
/**
 * Why a funnels list cannot be saved, as one sentence naming the funnel and
 * step, or null when it is fine. An empty list is valid: it means "no funnels",
 * and the collector skips the funnels family with that reason.
 */
export declare function posthogFunnelsRefusal(value: unknown, name?: string): string | null;
/** The document that holds the declaration. */
export declare const NO_NIGHTLY_REPORT_FILE = "config/constants.json";
/** Its one pointer: a list of asset ids. Absent until the first asset declares. */
export declare const NO_NIGHTLY_REPORT_POINTER = "/no_nightly_report";
/** Why a declaration list cannot be saved, or null when it can. */
export declare function noNightlyReportRefusal(value: unknown): string | null;
/** The pipeline's check for an op that touches the declaration: the list is
 * written whole, never one entry at a time, and must be a list of asset ids. */
export declare function noNightlyReportOpRefusal(op: {
    file?: unknown;
    pointer?: unknown;
    kind?: unknown;
    value?: unknown;
}): string | null;
/**
 * The declared asset ids in a constants document, or null when it declares
 * none at all (the key is absent — the state a writer creates rather than
 * replaces). Total over an untrusted body: anything that is not a list of ids
 * reads as the ids it does hold, so one bad entry never silences the rest.
 */
export declare function noNightlyReportAssets(constants: unknown): string[] | null;
/**
 * Which asset an older single-asset binding serves: the first asset, in the
 * installation's own data-source register order (`config/integrations.json`
 * `/assets`, store first), whose entry has `lane`. Null, and the binding
 * serves no asset, when the register is missing or no asset has the lane.
 */
export declare function legacyBindingAsset(lane: string, register: unknown): string | null;
/** A guard states the value or the absence the writer observed, never both. */
export type FileJsonSetOp<File extends string = string> = FileJsonSetGuardedOp<File> | FileJsonSetFirstOp<File>;
interface FileJsonSetBase<File extends string> {
    kind: 'file-json-set';
    file: File;
    pointer: string;
    value: JsonValue;
}
export interface FileJsonSetGuardedOp<File extends string = string> extends FileJsonSetBase<File> {
    expect: JsonValue;
    expectAbsent?: never;
}
export interface FileJsonSetFirstOp<File extends string = string> extends FileJsonSetBase<File> {
    expect?: never;
    expectAbsent: true;
}
export interface FileJsonInsertOp<File extends string = string> {
    kind: 'file-json-insert';
    file: File;
    pointer: string;
    value: JsonValue;
}
export interface FileJsonDeleteOp<File extends string = string> {
    kind: 'file-json-delete';
    file: File;
    pointer: string;
    expect: JsonValue;
}
export interface StoreAssetSetOp<Column extends string = string> {
    kind: 'store-asset-set';
    asset: string;
    column: Column;
    expect: JsonValue;
    value: JsonValue;
}
export type ChangesetOp = FileJsonSetOp | FileJsonInsertOp | FileJsonDeleteOp | StoreAssetSetOp;
export interface Changeset<Op extends ChangesetOp = ChangesetOp> {
    version: 1;
    createdAt: string;
    slug: string;
    ops: Op[];
}
export type ConfigSource = 'store' | 'file';
export interface ConfigDocumentRead {
    file: string;
    body: unknown;
    source: ConfigSource;
    version: number | null;
    updatedAt: string | null;
    updatedBy: string | null;
}
export interface ApplyConfigOpsInput<Op = ChangesetOp> {
    ops: Op[];
    expectVersions?: Record<string, number | null> | null;
    actor: string;
    reason?: string | null;
    slug?: string;
}
export interface ConfigWriteMismatch {
    file?: string;
    pointer?: string;
    asset?: string;
    column?: string;
    expect: unknown;
    expectAbsent?: true;
    current: unknown;
    absent: boolean;
}
export type ApplyConfigOpsResult = {
    ok: true;
    applied: number;
    documents: {
        file: string;
        version: number;
        body: unknown;
    }[];
} | {
    ok: false;
    error: 'store_unavailable';
    detail: string;
} | {
    ok: false;
    error: 'invalid_changeset';
    detail: string;
} | {
    ok: false;
    error: 'store_op_not_accepted';
    detail: string;
} | {
    ok: false;
    error: 'not_seeded';
    detail: string;
    files: string[];
} | {
    ok: false;
    error: 'version_mismatch';
    files: {
        file: string;
        expected: number | null;
        observed: number;
    }[];
} | {
    ok: false;
    error: 'expect_mismatch';
    mismatches: ConfigWriteMismatch[];
};
export {};
