// Generated by pnpm config:generate. Edit the sibling .mts source.
/** Portable PostHog archive shape. No schema library, storage, or runtime globals. */
/** The families, in the order a run collects them. */
export declare const POSTHOG_FAMILIES: readonly ["web-daily", "events", "exceptions", "rageclicks", "web-vitals", "funnels"];
export type PosthogFamily = (typeof POSTHOG_FAMILIES)[number];
export interface PosthogFamilyRow {
    readonly grain: string;
    readonly fields: readonly string[];
}
/** Every family's row grain and contract fields. */
export declare const POSTHOG_FAMILY_ROWS: {
    readonly 'web-daily': {
        readonly grain: "day";
        readonly fields: readonly ["date", "pageviews", "people", "sessions"];
    };
    readonly events: {
        readonly grain: "event";
        readonly fields: readonly ["event", "count", "people", "firstSeen", "lastSeen"];
    };
    readonly exceptions: {
        readonly grain: "exception-message";
        readonly fields: readonly ["type", "message", "count", "people", "sessions", "maxPerSession", "hasSourceFile", "topPath", "topBrowser"];
    };
    readonly rageclicks: {
        readonly grain: "page-element";
        readonly fields: readonly ["path", "tag", "text", "attr", "clicks", "people", "desktopClicks", "mobileClicks", "tabletClicks", "pagePeople"];
    };
    readonly 'web-vitals': {
        readonly grain: "page-device-os";
        readonly fields: readonly ["path", "device", "os", "lcpP75", "inpP75", "clsP75", "fcpP75", "measurements"];
    };
    readonly funnels: {
        readonly grain: "funnel-step";
        readonly fields: readonly ["funnelId", "name", "step", "event", "path", "people"];
    };
};
/** The contract field names of one family's rows. */
export type PosthogFamilyField<F extends PosthogFamily> = (typeof POSTHOG_FAMILY_ROWS)[F]['fields'][number];
