// Generated by pnpm generate. Edit the sibling .mts source.
/** Presentation declarations over already saved GA4 event aggregates. */
export declare const PRODUCT_USE_GROUPS: readonly ["primary", "sharing", "supporting"];
export declare const PRODUCT_USE_MAX_STAGES = 32;
export declare const PRODUCT_USE_EVENT_MAX_LENGTH = 40;
export declare const PRODUCT_USE_LABEL_MAX_LENGTH = 60;
export declare const PRODUCT_USE_EVENT_PATTERN = "^[A-Za-z][A-Za-z0-9_]*$";
export interface ProductUseStage {
    eventName: string;
    label: string;
    group: (typeof PRODUCT_USE_GROUPS)[number];
    /** Compare independent event-user volumes, never a same-person conversion. */
    compareTo?: string;
    comparisonLabel?: string;
}
/** One validator used by saved settings, archive analysis and payload readers. */
export declare function productUseStagesRefusal(value: unknown): string | null;
/** Missing declarations remain missing. Returned values cannot mutate settings. */
export declare function readProductUseStages(value: unknown): readonly ProductUseStage[] | null;
