// Generated by pnpm generate. Edit the sibling .mts source.
/** Presentation declarations over already saved GA4 event aggregates. */
export const PRODUCT_USE_GROUPS = ['primary', 'sharing', 'supporting'];
export const PRODUCT_USE_MAX_STAGES = 32;
export const PRODUCT_USE_EVENT_MAX_LENGTH = 40;
export const PRODUCT_USE_LABEL_MAX_LENGTH = 60;
export const PRODUCT_USE_EVENT_PATTERN = '^[A-Za-z][A-Za-z0-9_]*$';
const eventPattern = new RegExp(PRODUCT_USE_EVENT_PATTERN);
const keys = new Set(['eventName', 'label', 'group', 'compareTo', 'comparisonLabel']);
const event = (value) => typeof value === 'string' &&
    value.length <= PRODUCT_USE_EVENT_MAX_LENGTH && eventPattern.test(value);
const label = (value) => typeof value === 'string' &&
    value.trim() === value && value.length > 0 && value.length <= PRODUCT_USE_LABEL_MAX_LENGTH;
/** One validator used by saved settings, archive analysis and payload readers. */
export function productUseStagesRefusal(value) {
    if (!Array.isArray(value) || value.length > PRODUCT_USE_MAX_STAGES) {
        return `Product use stages must be a list of at most ${PRODUCT_USE_MAX_STAGES} rows`;
    }
    const seen = new Set();
    for (const row of value) {
        if (row === null || typeof row !== 'object' || Array.isArray(row) ||
            Object.keys(row).some((key) => !keys.has(key)))
            return 'Invalid product use stage';
        const stage = row;
        if (!event(stage.eventName) || !label(stage.label) ||
            typeof stage.group !== 'string' || !PRODUCT_USE_GROUPS.some((group) => group === stage.group) ||
            (stage.compareTo !== undefined && (!event(stage.compareTo) || stage.compareTo === stage.eventName)) ||
            (stage.comparisonLabel !== undefined && !label(stage.comparisonLabel))) {
            return 'Invalid product use stage';
        }
        if (seen.has(stage.eventName))
            return 'Product use event names must be unique';
        seen.add(stage.eventName);
    }
    return null;
}
/** Missing declarations remain missing. Returned values cannot mutate settings. */
export function readProductUseStages(value) {
    if (productUseStagesRefusal(value) !== null)
        return null;
    return Object.freeze(value.map((stage) => Object.freeze({
        eventName: stage.eventName, label: stage.label, group: stage.group,
        ...(stage.compareTo === undefined ? {} : { compareTo: stage.compareTo }),
        ...(stage.comparisonLabel === undefined ? {} : { comparisonLabel: stage.comparisonLabel }),
    })));
}
