// Generated by pnpm generate. Edit the sibling .mts source.
export interface SearchMarket {
    locationCode: number;
    languageCode: string;
}
/**
 * The market every DataForSEO family asks in when a site has saved none of its
 * own — the United States, in English: the product's default, not any one
 * installation's.
 */
export declare const DATAFORSEO_BASELINE_MARKET: Readonly<SearchMarket>;
/**
 * A site's OWN market: its `dataforseo` entry in config/integrations.json
 * (`locationCode`, `languageCode` — the `asset-lane` register fields). The two
 * resolve independently, as the collector asks: a site that saved a location
 * but no language is asked for that place in the default language. Null when
 * the entry holds neither, and the site is asked in the default market.
 */
export declare function savedSearchMarket(entry: unknown): SearchMarket | null;
/** A market in words, "United Kingdom · English". A code this table does not
 * name is shown as its number rather than guessed. */
export declare function marketLabel(market: SearchMarket): string;
