// Generated by pnpm config:generate. Edit the sibling .mts source.
/** The ordinary task snapshot input shape, shared by native pollers and the
 * validated Worker writer. These facts grant no workspace authority. */
export declare const BEADS_HANDOFF_KINDS: readonly ["query", "finding", "page", "alert"];
export type BeadsHandoffKind = (typeof BEADS_HANDOFF_KINDS)[number];
/** One bead, flattened to what a board row needs. */
export interface BeadsIssueInput {
    id: string;
    title: string;
    status: string;
    priority: number;
    issueType: string;
    assignee?: string | null;
    updatedAt?: string | null;
    closedAt?: string | null;
    /** The epic this bead hangs off (`bd`'s `parent`). Absent or null means
     * "group it in the remainder", never "invent a group". */
    parent?: string | null;
    /** When a parked bead asks to be reconsidered. Only deferred beads have one. */
    deferUntil?: string | null;
    /** When the bead was filed. Optional: an older poller sends none, and the
     * store then keeps no key rather than a guess. */
    createdAt?: string | null;
}
/** One epic container plus what its children are doing. Entirely optional on
 * the wire: absent means this poller could not describe structure, and the
 * board falls back to flat lists rather than inventing grouping. */
export interface BeadsEpicInput {
    id: string;
    title: string;
    status: string;
    priority: number;
    /** ALL-TIME children, from `bd epic status` — the only honest progress
     * denominator, since the closed list here is a trailing week. */
    total: number;
    closed: number;
    counts: {
        open: number;
        inProgress: number;
        blocked: number;
        deferred: number;
    };
    priorities: number[];
}
export interface BeadsCountsInput {
    open: number;
    /** P0+P1 across everything not closed. Cuts across the other counts rather
     * than partitioning them; computed by the poller from the untruncated `bd`
     * output. Optional, and absent is stored as absent, never as 0: a poller one
     * generation older than the store did not look, and must not report a zero. */
    highPriority?: number;
    /** Deliberately parked work. In none of the other counts. Optional under
     * the same rule as `highPriority`. */
    deferred?: number;
    /** Beads waiting on the operator — ready `human`-labelled work plus open
     * `human` gates. Optional. */
    waiting?: number;
    ready: number;
    inProgress: number;
    blocked: number;
    closedRecent: number;
}
export interface BeadsProjectInput {
    asset: string;
    prefix: string;
    ok: boolean;
    error?: string | null;
    counts: BeadsCountsInput;
    /** Open work per `bd` priority band, P0..P4. Optional under the same rule as
     * `counts.highPriority`: absent is stored absent, and the card draws no
     * distribution. */
    priorities?: number[] | null;
    /** Epic grouping. Optional: absent means this poller cannot describe
     * structure, and the board renders its flat lists instead. */
    epics?: BeadsEpicInput[] | null;
    ready: BeadsIssueInput[];
    inProgress: BeadsIssueInput[];
    recentlyClosed: BeadsIssueInput[];
    /** Newest-filed work, newest first. Optional under the same rule. */
    recentlyCreated?: BeadsIssueInput[] | null;
    /** Parked work, soonest wake-up first. Optional under the same rule. */
    deferred?: BeadsIssueInput[] | null;
    /** The operator's inbox for this project, most-blocking first. Optional. */
    waiting?: BeadsIssueInput[] | null;
    /** Urgent operator asks over the untruncated inbox: all human gates plus
     * P0/P1 ready-human beads. Optional under the same rule. */
    waitingUrgent?: number;
    /**
     * SERP-panel triage state. Three-valued: key absent — this poller did not
     * look, and the card draws nothing; `null` — it looked and this property has
     * no review bead at all; an object — the open review, or the newest closed
     * one. "We never asked" must not render as "nothing to triage".
     */
    panelReview?: BeadsPanelReviewInput | null;
    /**
     * Work filed from this property's Tower handoffs. Optional under the same
     * rule: an absent key means the poller never asked, `[]` means it asked and
     * nobody has filed anything. A finding card may only present itself as
     * untouched off the second.
     */
    handoffs?: BeadsHandoffInput[] | null;
}
/**
 * Where this property stands on triaging its last SERP panel. The runner's
 * filer creates one `panel-review` bead per property per panel day; the
 * poller reports the open one, or the most recently closed one, so a card can
 * say "reviewed" rather than only "nothing outstanding". `status` is not
 * `bd`'s vocabulary: a review is open or closed, and in_progress is a detail
 * of how somebody works.
 */
export interface BeadsPanelReviewInput {
    beadId: string;
    /** The panel day being triaged, YYYY-MM-DD — the collection's `report_date`,
     * carried through `noticeos_panel_date` on the bead. */
    panelDate: string;
    /** When the review is due (the convention: seven days after the panel day).
     * Null when `bd` reported none. */
    dueAt?: string | null;
    status: 'open' | 'closed';
    /** Set only on a closed review. */
    closedAt?: string | null;
}
/**
 * One bead filed from a Tower handoff, joined to the finding that raised it.
 * The poller reads these off each spoke's handoff label and keeps the
 * `noticeos_*` metadata that names the origin; `key` is `noticeos_key` byte
 * for byte, so the surface matches by key alone.
 */
export interface BeadsHandoffInput {
    /** Which Tower surface raised it — see `BEADS_HANDOFF_KINDS`. */
    kind: BeadsHandoffKind;
    /** The finding's card key, the normalized query, the page URL, or the flag
     * id. Byte-exact. */
    key: string;
    beadId: string;
    /** `bd`'s richer statuses collapse to two upstream. `closed` means shipped,
     * NOT proven — only a watch-window verdict retires a finding. */
    status: 'open' | 'closed';
    closedAt?: string | null;
}
export interface BeadsSnapshotInput {
    capturedAt?: string | null;
    projects: BeadsProjectInput[];
}
