// Generated by pnpm config:generate. Edit the sibling .mts source.
export interface TaskMetadataField {
    /** The key NoticeOS writes. */
    readonly name: string;
    /** The key a bead filed before the rename carries. */
    readonly legacy: string;
}
export declare const TASK_METADATA: Readonly<{
    /** A Tower handoff's source: always the handoff label. */
    source: Readonly<{
        name: "noticeos_source";
        legacy: "reindex_source";
    }>;
    /** Which site the handoff was raised for. */
    asset: Readonly<{
        name: "noticeos_asset";
        legacy: "reindex_asset";
    }>;
    /** Which Tower surface raised it: finding, query, page or alert. */
    kind: Readonly<{
        name: "noticeos_kind";
        legacy: "reindex_kind";
    }>;
    /** The rule behind it. */
    rule: Readonly<{
        name: "noticeos_rule";
        legacy: "reindex_rule";
    }>;
    /** The byte-exact join back to the row that raised it. */
    key: Readonly<{
        name: "noticeos_key";
        legacy: "reindex_key";
    }>;
    /** A panel review's site. */
    panelAsset: Readonly<{
        name: "noticeos_panel_asset";
        legacy: "reindex_panel_asset";
    }>;
    /** A panel review's collection day. */
    panelDate: Readonly<{
        name: "noticeos_panel_date";
        legacy: "reindex_panel_date";
    }>;
    /** An unpushed-work ask's site. */
    pushAsset: Readonly<{
        name: "noticeos_push_asset";
        legacy: "reindex_push_asset";
    }>;
    /** A task-map drift report's project. */
    taskMapAsset: Readonly<{
        name: "noticeos_task_map_asset";
        legacy: "reindex_task_map_asset";
    }>;
    /** The server's identity for the hosted write that created this task, so a
     * retried request can find it. Server-set only; it has no older name. */
    operation: Readonly<{
        name: "noticeos_operation_id";
        legacy: "noticeos_operation_id";
    }>;
}>;
export type TaskMetadataName = keyof typeof TASK_METADATA;
/** The label every Tower handoff bead carries from now on. */
export declare const HANDOFF_LABEL = "noticeos-handoff";
/** The label handoff beads filed before the rename carry. */
export declare const LEGACY_HANDOFF_LABEL = "reindex-handoff";
/** Both, for a reader that finds handoffs by label (`bd list --label-any`). */
export declare const HANDOFF_LABELS: readonly string[];
/**
 * One field of a bead's metadata under either name: the NoticeOS key when the
 * bead carries it, else the pre-rename key. Undefined when the bead carries
 * neither, or its metadata is not an object (`bd list --json` omits it for a
 * bead with none).
 */
export declare function taskMetadataValue(metadata: unknown, field: TaskMetadataName): unknown;
/** Whether a label is the handoff label, of either vintage. */
export declare function isHandoffLabel(label: unknown): boolean;
