// Generated by pnpm generate. Edit the sibling .mts source.
/** Field-size boundary for a registered query and its private history read. */
export const WATCH_QUERY_MAX_CHARS = 2000;
/** Existing calibration horizon, unchanged from the Tower composer. */
export const WATCH_CALIBRATION_DAYS = 180;
export const WATCH_SERIES = [
    { integration: 'gsc', metric: 'clicks', label: 'Google clicks', improvesWhen: 'up', aggregation: 'sum' },
    { integration: 'gsc', metric: 'impressions', label: 'Google impressions', improvesWhen: 'up', aggregation: 'sum' },
    { integration: 'gsc', metric: 'ctr', label: 'Google click-through rate', improvesWhen: 'up', aggregation: 'mean' },
    { integration: 'gsc', metric: 'position', label: 'Google average position', improvesWhen: 'down', aggregation: 'mean' },
    { integration: 'ga4', metric: 'sessions', label: 'Analytics sessions', improvesWhen: 'up', aggregation: 'sum' },
    { integration: 'ga4', metric: 'active_users', label: 'Analytics active users', improvesWhen: 'up', aggregation: 'sum' },
    { integration: 'ga4', metric: 'page_views', label: 'Analytics page views', improvesWhen: 'up', aggregation: 'sum' },
    { integration: 'ga4', metric: 'event_count', label: 'Analytics events', improvesWhen: 'up', aggregation: 'sum' },
    { integration: 'bing-webmaster', metric: 'clicks', label: 'Bing clicks', improvesWhen: 'up', aggregation: 'sum' },
    { integration: 'bing-webmaster', metric: 'impressions', label: 'Bing impressions', improvesWhen: 'up', aggregation: 'sum' },
];
/** Both private RPC peers derive this fixed window from their server clock.
 * No public selector can widen it or supply a different historical window. */
export function watchQueryHistoryRange(nowMs) {
    if (!Number.isFinite(nowMs))
        throw new Error('Query history clock is unavailable.');
    return Object.freeze({
        first_day: new Date(nowMs - (WATCH_CALIBRATION_DAYS - 1) * 86_400_000).toISOString().slice(0, 10),
        last_day: new Date(nowMs).toISOString().slice(0, 10),
    });
}
