// Generated by pnpm generate. Edit the sibling .mts source.
/** Shared released vocabulary and bounded query-history range. These facts
 * classify a stored read; they grant no workspace or measurement authority. */
import type { WatchSeries } from './create-watch-window.js';
/** Field-size boundary for a registered query and its private history read. */
export declare const WATCH_QUERY_MAX_CHARS = 2000;
/** Existing calibration horizon, unchanged from the Tower composer. */
export declare const WATCH_CALIBRATION_DAYS = 180;
export declare const WATCH_SERIES: readonly WatchSeries[];
/** Both private RPC peers derive this fixed window from their server clock.
 * No public selector can widen it or supply a different historical window. */
export declare function watchQueryHistoryRange(nowMs: number): Readonly<{
    first_day: string;
    last_day: string;
}>;
