// Generated by pnpm config:generate. Edit the sibling .mts source.
/** Agent sign-in (epic ro-cvl9): OAuth 2.1 for NoticeOS's one MCP endpoint,
 * as MCP's authorization specification defines it. These are the protocol
 * facts every side shares: the protected resource, the scopes an agent may
 * hold and the workspace actions each one grants, the discovery documents,
 * and the bearer challenges. The authorization server is the identity
 * engine's maintained OAuth provider (packages/postgres/src/agent-sign-in.mts);
 * the resource side is workspace admission, which rechecks the person's
 * membership and role in the named workspace on every call. Nothing here
 * grants anything by itself.
 *
 * One connection serves every feature in every workspace its person belongs
 * to: each tool names its workspace, and the person's current role there
 * bounds the token's scopes. No scope reaches a human decision, membership or
 * a protected operation.
 */
/** The identity engine's base path; the issuer is the origin plus this. */
export declare const AGENT_AUTH_BASE = "/api/auth";
/** The one Tower page for every person-facing step: sign in, choose the
 * workspace, approve or deny. */
export declare const AGENT_ACCESS_PAGE = "/agent-access";
/** That page's two server calls. */
export declare const AGENT_ACCESS_PATHS: Readonly<{
    request: "/api/agent-access/request";
    approve: "/api/agent-access/approve";
}>;
/** The maintained library endpoints a deployment exposes, and their methods.
 * Every other library route stays private. */
export declare const AGENT_OAUTH_ROUTES: Readonly<Record<string, string>>;
/** The signed authorization query the provider hands the page; the page
 * passes it back unread. Never authority: the server checks its signature. */
export declare const AGENT_QUERY: RegExp;
export type AgentAccessLanding = Readonly<{
    kind: 'none';
}> | Readonly<{
    kind: 'agent';
    query: string;
}>;
/** Capture at document entry: an agent page landing and its signed query. */
export declare function parseAgentAccessLanding(input: string): AgentAccessLanding;
/** The one MCP endpoint, and so the one protected resource. */
export declare const AGENT_RESOURCE_PATH = "/api/mcp";
export declare const AGENT_RESOURCE_NAME = "NoticeOS";
/** The workspace actions each scope grants. Write implies read: a token that
 * may change tasks may also see them. */
export declare const AGENT_SCOPES: Readonly<Record<string, readonly string[]>>;
/** Requested by clients that want a refresh token; it grants no action. */
export declare const OFFLINE_ACCESS = "offline_access";
export declare const AGENT_ACCESS_SECONDS = 3600;
export declare const AGENT_REFRESH_SECONDS: number;
export declare function agentIssuer(origin: string): string;
export declare function agentResourceUri(origin: string): string;
/** RFC 8414 path insertion for an issuer with a path. */
export declare const AUTHORIZATION_SERVER_METADATA_PATH = "/.well-known/oauth-authorization-server/api/auth";
/** RFC 9728 path insertion for the protected resource. */
export declare const PROTECTED_RESOURCE_METADATA_PATH = "/.well-known/oauth-protected-resource/api/mcp";
export declare function protectedResourceMetadata(origin: string): Record<string, unknown>;
/** The bearer credential a request carries: none, one token, or a malformed
 * Authorization header (refused, never ignored). */
export declare function bearerToken(headers: Headers): string | null | false;
/** The actions a set of granted scopes allows, before the person's role is
 * applied. Unknown scopes grant nothing. */
export declare function agentActions(scopes: readonly string[]): readonly string[];
export declare function scopesSatisfy(granted: readonly string[], required: readonly string[]): boolean;
/** RFC 6750 §3 and MCP's scope challenge: 401 when a token is missing or
 * invalid, 403 when it lacks a scope. The body is JSON for humans; clients
 * read the header. */
export declare function bearerChallenge(origin: string, failure?: {
    readonly error: 'invalid_token' | 'insufficient_scope';
    readonly scopes?: readonly string[];
}): Response;
