// Generated by pnpm generate. Edit the sibling .mts source.
/** A JSON request's text, bounded in bytes and in time: the one reader the
 * hosted Tasks API (hosted-task-http) and the MCP endpoints (mcp-protocol)
 * share. Only `application/json` is read: a browser can send a text/plain
 * POST cross-site without a preflight, never an application/json one. Any
 * refusal throws BoundedJsonRefused; the caller chooses the answer.
 */
export declare class BoundedJsonRefused extends Error {
    name: string;
    constructor();
}
/** Whether the request declares a JSON body (parameters such as charset aside). */
export declare function jsonContentType(headers: Headers): boolean;
export declare function readBoundedJsonText(request: Request, maxBytes: number): Promise<string>;
