// Generated by pnpm generate. Edit the sibling .mts source.
/** Nonsecret selectors only: fresh server identity remains the authority. */
export declare const WORKSPACE_SELECTION_HEADER = "x-noticeos-workspace-id";
export declare const WORKSPACE_SESSION_HEADER = "x-noticeos-session-id";
/** Browser request evidence for hosted effects, including first login.
 * This validates one server-declared origin; it grants no identity or workspace authority. */
export interface BrowserRequestPolicy {
    readonly origin: string;
    assertEffect(request: Request): void;
}
export declare class BrowserRequestRefused extends Error {
    name: string;
    constructor();
}
export declare function createBrowserRequestPolicy(trustedOrigin: string): BrowserRequestPolicy;
