// Generated by pnpm generate. Edit the sibling .mts source.
/** Configuration references have their own spelling rule; the portable
 * contract owns the stricter creation vocabulary. */
import { CONFIG_ASSET_KEY_SOURCE as ASSET_ID_SOURCE } from '../packages/contract/src/configuration.mjs';
import type { JsonValue } from '../packages/contract/src/configuration.mjs';
export type { JsonValue } from '../packages/contract/src/configuration.mjs';
export { ASSET_ID_SOURCE };
/** What a field may hold. The type decides the refusal AND the control the
 * Tower renders, so there is no second table mapping one to the other. */
export type FieldType = 'string' | 'number' | 'integer' | 'boolean' | 'enum' | 'date' | 'month' | 'url'
/** A reference to a site from a configuration file (the configuration key
 * spelling, `CONFIG_ASSET_KEY_SOURCE`). */
 | 'asset-id'
/** A site's own id in the store (`ASSET_ID_RE`) — the `assets` row's key and
 * what every store lane names a site by (`SITE_ROW_FIELDS`). A different
 * spelling rule from `asset-id`, read out in the same words. */
 | 'store-asset-id'
/** A hostname such as example.com (`DOMAIN_RE`) — no scheme, no path. */
 | 'domain' | 'string-list'
/** A PostHog funnels list, judged whole by `posthogFunnelsRefusal` in the
 * portable configuration contract. */
 | 'posthog-funnels';
export interface RegisterField {
    /** The JSON key inside a row — also the last pointer token of a `file-json-set`. */
    name: string;
    /** The column heading and the input's label. */
    label: string;
    type: FieldType;
    required: boolean;
    /** The hint under the Add form's input and the column heading's hover: a
     * format or an example, label-length. A warning about editing a field is a
     * rule (`readOnly`), never a sentence here. */
    describe: string;
    /** `enum` only — the complete set of accepted values. */
    values?: readonly string[];
    /** `enum` only — what a value reads as on screen. The file keeps the value;
     * a value with no entry here shows as itself. */
    valueLabels?: Readonly<Record<string, string>>;
    /** `number` / `integer` bounds. */
    min?: number;
    max?: number;
    /** `string`-ish limits. */
    maxLength?: number;
    /** A RegExp source the whole value must match. */
    pattern?: string;
    /** Another field of the same row whose value this one takes until it is typed
     * into directly — an Add-form default, never a stored derivation (the file
     * keeps both values, because the equality is a convention, not a rule). */
    defaultFrom?: string;
    /**
     * What a runtime candidate list means for this field. `'closed'` (the
     * default): the values a page supplies are the whole value domain and
     * anything else is refused. `'suggest'`: they are what is already in use,
     * offered as a picker, and a value outside them is a legitimate edit.
     */
    candidates?: 'closed' | 'suggest';
    /**
     * May be set when the row is created and not afterwards — a join key whose
     * rename breaks something no table can show. The editor shows a lock with
     * `fixedFieldLabel`, and the write lane refuses the set too, so a
     * hand-written changeset cannot walk past it. The way to change one is
     * Remove and Add.
     */
    readOnly?: boolean;
    /** A different state than "fixed once added", label-length, for a field no
     * surface here writes. Only meaningful beside `readOnly`. */
    readOnlyReason?: string;
}
/** One "changing X dates Y" pair a register declares. Both names are fields
 * of that register. */
export interface RegisterStamp {
    /** The field whose CHANGE is the decision. */
    when: string;
    /** The date field set to the day the change was applied. */
    field: string;
}
export interface ConfigRegister {
    /** Repo-relative path of the file holding the container. */
    file: string;
    /** RFC-6901 pointer to the container. May carry `{asset}` — see ASSET_PARAM. */
    container: string;
    /** An array of rows, or an object whose keys are the rows. */
    shape: 'array' | 'object';
    /** `object` shape only: what a key must look like. `lane-id` is the one
     * register keyed by something other than an asset. */
    keyRule?: 'asset-id' | 'lane-id';
    /** `array` shape: the field that identifies a row. Absent or `null` for an object shape. */
    keyField?: string | null;
    /** Further fields no two rows may share. The key field is unique by
     * definition and is not repeated here. */
    unique?: readonly string[];
    /**
     * The row's fields, in column order (the key field first). `null` means the
     * row is OPAQUE: it may be added and removed whole, and nothing inside it may
     * be set through this register.
     */
    fields: readonly RegisterField[] | null;
    /** When set, a row MAY be the bare value of that one field rather than an
     * object wrapping it (a string list; a tracked query with no cluster). */
    scalarField?: string;
    /**
     * The field that names the group a row belongs to, where grouping downstream
     * is an exact string match; a near miss is refused where it is typed
     * (`clusterSpellingRefusal`).
     */
    clusterField?: string;
    /** The file has no empty state for the list: an entry holding `[]` is a
     * config error there, so the last row out takes the asset's whole entry
     * with it, as the first row in filed one. Only for a per-asset list (one
     * with a `holderOf` holder). */
    emptyIsAbsent?: boolean;
    /** This exact per-asset list may be initialized beside another holder field.
     * Its parent must already exist; no arbitrary parent structure is created. */
    addableContainer?: boolean;
    /** First-row Undo removes this list only, preserving a shared holder. */
    seedUndo?: 'list';
    /**
     * Rows carry a claim about another file that no field can check: `enabled`
     * on the panel-refresh roster asserts a live search lane in
     * `config/integrations.json`. The rule is `liveSearchLaneRefusal`; the facts
     * come from whoever holds them.
     */
    requiresLiveSearchLane?: boolean;
    /**
     * Dates a write moves: when a set changes a row's `when` field, the pipeline
     * sets that row's `field` to the day it applied.
     */
    stamps?: readonly RegisterStamp[];
    /** A register an asset is born into and deleted out of. `ADDABLE_CONTAINERS`
     * is derived from it, and a new one here also belongs in the delete's own
     * list of files it clears. */
    assetRegister?: boolean;
    /** The register's name in the UI. */
    label: string;
    /** What one row IS, label-length: the CLI refusal names the register by it
     * and the Tower shows it under the table's title. */
    describe: string;
    /** The README that owns the concept. */
    owner: string;
    /** Where an operator edits it. */
    surface: string;
}
export type ConfigRegisterKey = 'product-use-stages' | 'asset-integrations' | 'asset-lane' | 'asset-counters' | 'asset-pull' | 'domain-costs' | 'recurring-costs' | 'value-events' | 'value-events-assets' | 'ga4-event-params' | 'ga4-event-params-assets' | 'serp-panel-queries' | 'serp-panel-assets' | 'signal-panels' | 'task-hub-spokes' | 'data-source-catalog' | 'entities';
/**
 * What a collector reads for an asset that maps nothing on a lane, as a code
 * the card draws as a chip:
 *
 *  - `google-account-map` — the Google credential's own per-asset map
 *    (`GOOGLE_SIGNAL_ACCOUNTS → properties → <asset> → ga4_property_id /
 *    gsc_site_url`). An install that signed in with Google has no such map, so
 *    it collects nothing until a value is saved. Once every asset the
 *    credential names is mapped here, the collector stops reading that map.
 *  - `domain-match` — the asset's own domain matched against the sites the
 *    central Bing account lists as verified; no match fails loudly.
 *  - `portfolio-market` — the portfolio baseline market, location 2840
 *    (United States) and language `en`. A field left empty takes the baseline.
 *  - `none` — the lane skips this asset and records why (PostHog has no
 *    portfolio-wide project, and a guessed one would read another site's data).
 */
export type LaneFallback = 'google-account-map' | 'domain-match' | 'portfolio-market' | 'none';
/**
 * One data-source lane's mapping fields, and what the collector reads when
 * this asset maps nothing. Only the lanes that have a per-asset mapping
 * appear; every other lane's card renders none.
 */
export interface LaneMapping {
    /** Field names of `asset-lane`, in the order the card renders them. */
    fields: readonly string[];
    /** Structured fields saved as one list value, rendered by their own editor
     * below the scalar fields and not counted as the mapping step. */
    lists?: readonly string[];
    /** What an unmapped lane reads instead. */
    fallback: LaneFallback;
}
/**
 * One scalar setting at one exact pointer, beside a list in a file that is
 * deliberately not wholesale-editable. It carries a whole `RegisterField` so
 * the refusal is worded in one place, shared with every register column.
 */
export interface ConfigKnob {
    /** Repo-relative path of the file holding it. */
    file: string;
    /** The RFC-6901 pointer — exact; nothing above or below it is licensed. */
    pointer: string;
    /** The knob's name in the UI. */
    label: string;
    /** Display unit beside the control; it does not change the stored value. */
    unit: string;
    /** The rule, spelled as a register column is. `name` is the pointer's last
     * reference token, so a refusal names the key the file actually holds. */
    field: RegisterField;
    /** The README that owns the concept. */
    owner: string;
    /** Where an operator edits it. */
    surface: string;
}
export type ConfigKnobKey = 'panel-refresh-window' | 'panel-freshness-bar';
export interface KnobMatch {
    key: ConfigKnobKey;
    knob: ConfigKnob;
}
export interface RegisterMatch {
    key: ConfigRegisterKey;
    register: ConfigRegister;
    /** Reference tokens past the container: `[]`, `["3"]`, `["3","domain"]`. */
    rest: string[];
    /** The asset a per-asset container matched. */
    params: {
        asset?: string;
    };
    /** The container as it appeared in the pointer, `{asset}` already filled. */
    container: string;
}
/** The whole-asset register a per-asset list's entry has to be filed in first. */
export interface RegisterHolder {
    key: ConfigRegisterKey;
    register: ConfigRegister;
    /** The key inside the holder's entry the list lives at (`valueEvents`). */
    field: string;
}
/** The token that marks the per-asset hole in a container pointer. A register
 * carrying one is a different collection for every asset. */
export declare const ASSET_PARAM: string;
/** Data-source lane ids are the catalog's own join keys (`ga4`,
 * `bing-webmaster`) — the shape `data-source-catalog` declares for its `id`
 * column, repeated here as what a key may look like. */
export declare const LANE_ID_SOURCE: string;
/**
 * The registers, keyed by the name a UI passes. Field order is column order,
 * the key field first. `describe` is the one line the CLI prints in a refusal
 * and the Tower shows above the table.
 */
export declare const CONFIG_REGISTERS: Record<ConfigRegisterKey, ConfigRegister>;
/** When a save here reaches the collectors, as a code the card draws as a
 * chip: `next-run` when this deployment read the document from the store
 * (every collector run re-reads it), `after-restart` when it is still on the
 * compiled-in copy. */
export type LaneMappingTiming = 'next-run' | 'after-restart';
/** The one true answer, given where this deployment read the file.
 * `source` is `'store'` or `'file'`, straight off `GET /api/config`. */
export declare function laneMappingTiming(source: 'store' | 'file' | undefined): LaneMappingTiming;
/** The chip for each timing — a state, not the sentence above. */
export declare const LANE_MAPPING_TIMING_LABEL: Readonly<Record<LaneMappingTiming, string>>;
/** The chip for each fallback, beside a lane nothing is mapped on. A mapped
 * lane wears `LANE_MAPPED_LABEL` instead. */
export declare const LANE_FALLBACK_LABEL: Readonly<Record<LaneFallback, string>>;
export declare const LANE_MAPPED_LABEL: string;
/**
 * Which mapping fields each lane has, and what the collector reads when this
 * asset maps nothing. `asset-lane` declares every field a lane cell may hold;
 * no lane holds all of them. Kept beside the declaration so the fields a card
 * renders and the fields the write lane judges cannot drift. Saving a mapping
 * steers what the OS asks for, never what the provider holds.
 */
export declare const LANE_MAPPING: Record<string, LaneMapping | undefined>;
export declare const OPERATOR_LANE_STATES: readonly string[];
/**
 * The top-level `updated` a config file states about itself. Nothing reads
 * it, so a Tower write would leave it stale; `applyDocumentOps` refreshes it
 * for every entry point at once. It refreshes and never invents: a document
 * with no such pointer gains nothing.
 */
export declare const DOCUMENT_STAMPS: Readonly<Record<string, string>>;
/** The pointer a write refreshes in this file, or `null`. */
export declare function documentStamp(file: string): string | null;
/**
 * A register's `stamps`, or `[]`. A rule of the pipeline rather than a second
 * op the browser sends, so the date follows the write wherever it comes from
 * and CollectionEditor's one-changeset-per-cell contract is untouched.
 */
export declare function registerStamps(register: ConfigRegister): readonly RegisterStamp[];
/**
 * The scalar knobs, one exact pointer each. A knob licenses `file-json-set`
 * at that pointer and nowhere else — `/refresh` is refused, and so is
 * anything below it — and carries the same `RegisterField` a register column
 * does, so `fieldRefusal` judges it with the identical sentence. Widening
 * `SETTABLE_FILES` instead would license rewriting every roster note.
 *
 * Deliberately not declared: `config/beads.json` `/hub` (host, port,
 * dataDir) — how `bd` reaches the Dolt server, wiring rather than a setting.
 */
export declare const CONFIG_KNOBS: Record<ConfigKnobKey, ConfigKnob>;
/**
 * The files a `file-json-set` may edit at any pointer. Deliberately not
 * "every file with a register": these four are wholesale editable because
 * their whole contents are settings the Tower renders as knobs.
 * `config/integrations.json` is in both lists, which is how an asset's lane
 * status is written while its catalog rows are field-validated.
 */
export declare const SETTABLE_FILES: readonly string[];
/** `[key, register]` for every declaration, in file order. */
export declare function registerEntries(): [ConfigRegisterKey, ConfigRegister][];
/** Every register declared for one file, in declaration order. */
export declare function registersForFile(file: string): [ConfigRegisterKey, ConfigRegister][];
/** Every file any register names — the add/remove boundary. */
export declare function registerFiles(): string[];
/** `[key, knob]` for every scalar knob, in declaration order. */
export declare function knobEntries(): [ConfigKnobKey, ConfigKnob][];
/** Every knob declared for one file, in declaration order. */
export declare function knobsForFile(file: string): [ConfigKnobKey, ConfigKnob][];
/** The knob a pointer is, or null. Exact match only: `/refresh/windowDays`
 * is settable, `/refresh` is not. */
export declare function matchKnob(file: string, pointer: string): KnobMatch | null;
/** Escape a literal for embedding in a RegExp source. */
export declare function escapeRegExp(text: string): string;
/** The container pointer with `{asset}` filled in. Throws when a per-asset
 * register is asked for a container without one. */
export declare function resolveContainer(register: ConfigRegister, params?: {
    asset?: string;
}): string;
/** A RegExp matching this register's container at the START of a pointer, with
 * the asset (when the register has one) as capture group 1. */
export declare function containerRegExp(register: ConfigRegister): RegExp;
/**
 * Which register (if any) owns a pointer in a file, and what is left of the
 * pointer past its container.
 *
 * `rest` is the remaining reference tokens: `[]` for the container itself,
 * `['3']` for a row, `['3','domain']` for one field of a row. `params` carries
 * the asset a per-asset container matched.
 */
export declare function matchRegister(file: string, pointer: string): RegisterMatch | null;
/**
 * The register that files this per-asset list's holder entry, and the key the
 * list lives at inside it — or `null` for a register that needs no holder.
 *
 * A pointer never creates structure, so a surface adding the first row of
 * `/assets/<asset>/valueEvents` files `{ valueEvents: [row] }` at
 * `/assets/<asset>` instead: one op, and one delete reverses it. Derived: a
 * per-asset list's container is always `<holder container>/{asset}/<field>`.
 */
export declare function holderOf(register: ConfigRegister): RegisterHolder | null;
/** The one field declaration a name resolves to, or null. */
export declare function fieldOf(register: ConfigRegister, name: string): RegisterField | null;
/** Is this reference token a legal ROW address in this register's container? */
export declare function isRowToken(register: ConfigRegister, token: string): boolean;
/**
 * May an insert into this array name a position? Every array register whose
 * rows have declared fields may, which is what lets an undo of a delete put
 * the row back where it was. The one opaque array (`config/pull.json`) may
 * not: nothing reads its rows' position. An index past the end of the list
 * is refused rather than quietly appending.
 */
export declare function positionedInsert(register: ConfigRegister): boolean;
/** How a refusal spells where an entry may be added / removed. Quoting follows
 * the shape: an array append is a literal token and reads as one. */
export declare function legalRowPointer(register: ConfigRegister, kind: string): string;
/** A `YYYY-MM-DD` calendar date that exists (2026-02-30 parses and is not a date). */
export declare function isCalendarDate(value: string): boolean;
/**
 * Check one value against one field declaration: `null` when it is fine, or
 * the rule it broke as a sentence naming the field by its label — the same
 * sentence the CLI prints, the lane returns in a 422 and the Tower shows
 * under the input.
 */
export declare function fieldRefusal(field: RegisterField, value: unknown): string | null;
/** The fields of a site's row in the store. */
export type SiteRowField = 'id' | 'displayName' | 'domain' | 'status' | 'senseOnly';
/**
 * A site's row in the store (the `assets` table), field by field, as the
 * ingest's site lanes check it (`workers/ingest/src/routes/validate.ts`
 * `declaredString`). Not a register: nothing here licenses a write. Declared
 * as fields so its refusals are worded by `fieldRefusal` with the labels
 * beside the Tower's inputs, never by a request-body key.
 */
export declare const SITE_ROW_FIELDS: Readonly<Record<SiteRowField, RegisterField>>;
/**
 * A refusal and the field it is about: `field` is the declared field's `name`
 * whose rule broke, or null when the refusal is the row's or the list's as a
 * whole. The Add form outlines that one input; the lane and the CLI read only
 * `message`, through `rowRefusal` and `duplicateKey`.
 */
export interface RowIssue {
    field: string | null;
    message: string;
}
/**
 * Check a whole ROW against a register.
 *
 * A scalar register (a string list, a tracked query with no cluster) accepts the
 * bare value as well as the one-field object; everything else must be an object,
 * every required field present, and NO undeclared key — an unknown key is a
 * typo that would land in a config file nobody validates again.
 */
export declare function rowIssue(register: ConfigRegister, value: unknown): RowIssue | null;
/** `rowIssue`'s sentence alone — what the lane and the CLI print. */
export declare function rowRefusal(register: ConfigRegister, value: unknown): string | null;
/**
 * The refusal for a field that may be set when the row is created and not
 * afterwards. A lane rule, not a UI one: a hand-written changeset would still
 * rename the key, so `config-apply-core.mjs` refuses the set too — which also
 * refuses a hand-authored rename, rightly, because a rename needs matching
 * edits in files and collectors this pipeline cannot make. Adding is
 * untouched: a new row must set its key.
 */
export declare function readOnlyFieldRefusal(field: RegisterField | null | undefined): string | null;
/** The state a fixed field shows beside its lock, in the table and on the Add
 * form: a label, not a rationale. */
export declare const FIXED_FIELD_LABEL: string;
/** What a read-only field's lock says: its own state where it declares one (a
 * field no surface here writes), otherwise "Fixed once added". `null` for a
 * field that is not read-only. */
export declare function fixedFieldLabel(field: RegisterField | null | undefined): string | null;
/**
 * `readOnlyFieldRefusal` for a whole row being replaced at its own pointer
 * (a scalar row, or clearing an optional field by removing its key). The
 * question is whether the write moved a read-only value: an unchanged key
 * rides along. `before` is the op's own `expect`, the row as the file held
 * it.
 */
export declare function readOnlyRowRefusal(register: ConfigRegister, before: JsonValue, after: JsonValue): string | null;
/**
 * A value outside the candidate set a field's value domain has. `fieldRefusal`
 * can only judge shape — a declaration cannot know which asset ids this OS
 * holds — so the candidates arrive from whoever does know: the browser passes
 * the integration matrix's asset list, the apply pipeline passes the roster.
 * An empty or absent set is "nobody answered", never "nothing is allowed".
 */
export declare function candidateRefusal(field: RegisterField | null | undefined, candidates: readonly string[] | null | undefined, value: unknown): string | null;
/**
 * One cluster, one spelling. Grouping is an exact string match on the stored
 * label, and the collector (`workers/ingest/src/dataforseo-dumps.ts`
 * `trackedLabel`) refuses the asset's whole panel with `config_invalid` when
 * two spellings coexist. A rule about the list alone, so `CollectionEditor`
 * applies it without the page's help.
 *
 * `exceptToken` is the row being edited: its own spelling is not a clash with
 * itself, so recasing a cluster only one row uses is allowed. `null` for the
 * Add form. Only a near miss is refused; an exact match joins the cluster and
 * a new label starts one.
 */
export declare function clusterSpellingRefusal(register: ConfigRegister, rows: readonly JsonValue[] | null | undefined, exceptToken: string | null, field: RegisterField, value: unknown): string | null;
/**
 * The lanes `config/signal-panels.README.md` counts as a SEARCH lane. Its own
 * validation snippet reads exactly these three out of `config/integrations.json`.
 */
export declare const SEARCH_LANES: readonly string[];
/** One asset's `config/integrations.json` entry as a flat `lane → status`
 * map, the shape `liveSearchLaneRefusal` judges. Anything that is not an entry
 * reads as `null`: nobody answered. */
export declare function laneStatuses(entry: unknown): Record<string, string> | null;
/**
 * Turning a roster row on is a claim about another file: an asset is
 * `enabled` only when one of its `gsc` / `ga4` / `bing-webmaster` lanes is
 * `live` in `config/integrations.json` (config/signal-panels.README.md). A
 * refresh pass over an asset with no live lane writes an empty panel dir,
 * which is indistinguishable on disk from a collapsed one.
 *
 * `statuses` is the asset's lanes as `laneStatuses` returns them; `null` or
 * an empty map refuses nothing. Only `enabled: true` is ever refused.
 */
export declare function liveSearchLaneRefusal(field: RegisterField, statuses: Record<string, string> | null | undefined, value: unknown): string | null;
/**
 * The register whose keys are the asset ids this OS has: `config/integrations.json`
 * `/assets` carries one entry per asset, and `config/signal-panels.README.md`
 * makes "the roster's keys equal this file's keys" an invariant. Named by
 * register key so the file and container stay declared once.
 */
export declare const ASSET_ROSTER_REGISTER: ConfigRegisterKey;
/** The roster's own file — what a caller has to read before it can pass
 * candidates. */
export declare function assetRosterFile(): string;
/**
 * The asset ids a parsed roster file declares, or `[]` — which refuses
 * nothing, so a repo with no `config/integrations.json` still applies its
 * changesets.
 */
export declare function rosterAssetIds(doc: unknown): string[];
/** Every declared field of a register whose value domain is the asset roster —
 * the fields `candidateRefusal` is asked about. */
export declare function assetIdFields(register: ConfigRegister): RegisterField[];
/**
 * Is a row already using a value that has to be its own? The key field is
 * always one; a register may name more in `unique`. Read by the Tower before
 * it sends, so the operator sees it beside the field rather than as a 422.
 */
export declare function duplicateIssue(register: ConfigRegister, rows: readonly JsonValue[] | null | undefined, value: JsonValue): RowIssue | null;
/** `duplicateIssue`'s sentence alone. */
export declare function duplicateKey(register: ConfigRegister, rows: readonly JsonValue[] | null | undefined, value: JsonValue): string | null;
/** One stored item as a field map, expanding a scalar item into its one field.
 * The single way a register's rows become table rows. */
export declare function rowValue(register: ConfigRegister, item: JsonValue): {
    [key: string]: JsonValue;
};
