#!/usr/bin/env node
// THE CONFIG REGISTERS' DOCUMENTATION, GENERATED FROM THEIR DECLARATION.
//
// scripts/config-registers.mts declares every list-shaped config register and
// every scalar knob the Tower may edit: file, container, key rule, each
// field's type, rule and hint, the surface that edits it, and the README that
// owns it. The README used to restate those facts in a hand-kept table that
// could disagree with the declaration. Now each owning README carries a block
// between two markers that this script writes, and `pnpm config:docs --check`
// (run by scripts/config-docs.test.mjs) fails when a block is stale.
//
//   node scripts/config-docs.mjs            print every README's block
//   node scripts/config-docs.mjs --write    rewrite the blocks
//   node scripts/config-docs.mjs --check    exit 1 when any block is stale

import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { CONFIG_KNOBS, CONFIG_REGISTERS } from './config-registers.mjs';

export const REPO_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
export const START = '<!-- config-registers:start -->';
export const END = '<!-- config-registers:end -->';

const cell = (text) => String(text ?? '').replace(/\|/gu, '\\|').replace(/\s+/gu, ' ').trim();
const code = (text) => `\`${String(text).replace(/`/gu, '')}\``;

/** The rule a field enforces, as one short phrase. */
export function fieldRule(field) {
  const parts = [];
  if (field.values) parts.push(`one of ${field.values.map((value) => code(value)).join(', ')}`);
  if (field.min !== undefined && field.max !== undefined) parts.push(`${field.min} to ${field.max}`);
  else if (field.min !== undefined) parts.push(`at least ${field.min}`);
  else if (field.max !== undefined) parts.push(`at most ${field.max}`);
  if (field.maxLength !== undefined) parts.push(`up to ${field.maxLength} characters`);
  if (field.pattern) parts.push(`matches ${code(field.pattern)}`);
  if (field.defaultFrom) parts.push(`defaults to ${code(field.defaultFrom)}`);
  if (field.candidates && field.candidates !== 'closed') parts.push(`candidates ${field.candidates}`);
  if (field.readOnly) parts.push('fixed once written');
  return parts.join('; ') || '—';
}

export function renderFields(fields) {
  return [
    '| Field | Label | Type | Required | Hint | Rule |',
    '|---|---|---|---|---|---|',
    ...fields.map((field) =>
      `| ${code(field.name)} | ${cell(field.label)} | ${code(field.type)} | ${field.required ? 'yes' : 'no'} | ${cell(field.describe)} | ${fieldRule(field)} |`),
  ].join('\n');
}

export function renderRegister(key, register) {
  const keyed = register.keyRule ? `keyed by ${register.keyRule}` : register.keyField ? `keyed by ${code(register.keyField)}` : 'rows in order';
  const head = [
    `**${register.label}** (${code(key)}) — ${register.describe}.`,
    `Rows live at ${code(register.container || '/')} of ${code(register.file)} (${register.shape}, ${keyed})${register.surface ? `; edited from ${register.surface}` : ''}.`,
  ].join(' ');
  if (!register.fields) return `${head} Rows are added and removed whole; no field inside one is set through the register.`;
  return `${head}\n\n${renderFields(register.fields)}`;
}

export function renderKnob(key, knob) {
  const field = knob.field ?? {};
  return `**${knob.label}** (${code(key)}) — ${field.describe ?? ''}${knob.unit ? ` (${knob.unit})` : ''}. ` +
    `One value at ${code(knob.pointer)} of ${code(knob.file)}${knob.surface ? `, edited from ${knob.surface}` : ''}; ${code(field.type ?? 'value')}, ${fieldRule(field)}.`;
}

/** Every owning README with the block it should carry. */
export function blocks() {
  const byOwner = new Map();
  for (const [key, register] of Object.entries(CONFIG_REGISTERS)) {
    const entry = byOwner.get(register.owner) ?? { registers: [], knobs: [] };
    entry.registers.push(renderRegister(key, register));
    byOwner.set(register.owner, entry);
  }
  for (const [key, knob] of Object.entries(CONFIG_KNOBS)) {
    const entry = byOwner.get(knob.owner) ?? { registers: [], knobs: [] };
    entry.knobs.push(renderKnob(key, knob));
    byOwner.set(knob.owner, entry);
  }
  const result = new Map();
  for (const [owner, { registers, knobs }] of [...byOwner.entries()].sort(([a], [b]) => a.localeCompare(b))) {
    const lines = [START, '', '### What the Tower may edit here', '',
      'Generated by `pnpm config:docs -- --write` from `scripts/config-registers.mts`, the one declaration of every register and knob; `scripts/config-docs.test.mjs` fails when this block is stale.', ''];
    for (const register of registers) lines.push(register, '');
    for (const knob of knobs) lines.push(knob, '');
    lines.push(END);
    result.set(owner, lines.join('\n'));
  }
  return result;
}

export function currentBlock(text) {
  const start = text.indexOf(START);
  const end = text.indexOf(END);
  if (start < 0 || end < 0 || end < start) return null;
  return text.slice(start, end + END.length);
}

export function withBlock(text, block) {
  const current = currentBlock(text);
  // A function replacer: a `$` inside the block (a field's regex) is never a pattern.
  if (current) return text.replace(current, () => block);
  return `${text.trimEnd()}\n\n${block}\n`;
}

/** The documentation site's configuration page: every README's block under its file's heading. */
export const DOCS_PAGE = 'apps/docs/reference/configuration.md';

export function renderDocsPage(all = blocks()) {
  const lines = [
    '---',
    'title: Configuration',
    'description: Every setting the Tower may edit, generated from the one declaration of the configuration registers.',
    '---',
    '',
    '# Configuration',
    '',
    'Settings live in the store once an installation is seeded; the `config/*.json` files in the repository are the generic defaults a new installation starts from, and each has a README beside it that says why the file exists. What the Tower may edit in each file is declared once, in `scripts/config-registers.mts`, and this page is generated from that declaration. A register lists rows (a site\'s data sources, a recurring cost); a knob is one value.',
    '',
  ];
  for (const [owner, block] of all) {
    const file = `config/${path.basename(owner, '.README.md')}.json`;
    lines.push(`## ${file}`, '', `Its README: [${owner}](https://github.com/notice-cx/NoticeOS/blob/main/${owner}).`, '', block, '');
  }
  return lines.join('\n');
}

export function main(argv = process.argv.slice(2), root = REPO_ROOT) {
  let stale = 0;
  const all = blocks();
  const targets = [
    ...[...all].map(([owner, block]) => ({ file: owner, content: (text) => withBlock(text || `# ${path.basename(owner, '.README.md')}.json\n`, block), current: (text) => currentBlock(text) === block })),
    { file: DOCS_PAGE, content: () => renderDocsPage(all), current: (text) => text === renderDocsPage(all) },
  ];
  for (const target of targets) {
    const file = path.join(root, target.file);
    const text = existsSync(file) ? readFileSync(file, 'utf8') : '';
    if (argv.includes('--write')) {
      writeFileSync(file, target.content(text));
    } else if (argv.includes('--check')) {
      if (!target.current(text)) {
        stale += 1;
        process.stderr.write(`${target.file}: the registers block is stale; run pnpm config:docs -- --write\n`);
      }
    } else if (target.file !== DOCS_PAGE) {
      process.stdout.write(`## ${target.file}\n\n${all.get(target.file)}\n\n`);
    }
  }
  return stale ? 1 : 0;
}

const invoked = process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (invoked) process.exitCode = main();
