// Generated by pnpm config:generate. Edit the sibling .mts source.
/** Configuration references have their own spelling rule; they do not create
 * an asset. The portable contract also owns the stricter creation vocabulary. */
import { CONFIG_ASSET_KEY_SOURCE as ASSET_ID_SOURCE } from '../packages/contract/src/configuration.mjs';
import type { JsonValue } from '../packages/contract/src/configuration.mjs';
export type { JsonValue } from '../packages/contract/src/configuration.mjs';
export { ASSET_ID_SOURCE };
/** What a field may hold. The type decides the refusal AND the control the
 * Tower renders, so there is no second table mapping one to the other. */
export type FieldType = 'string' | 'number' | 'integer' | 'boolean' | 'enum' | 'date' | 'month' | 'url'
/** A reference to a site from a configuration file (the configuration key
 * spelling, `CONFIG_ASSET_KEY_SOURCE`). */
 | 'asset-id'
/** A site's own id in the store (`ASSET_ID_RE`) — the `assets` row's key and
 * what every store lane names a site by (`SITE_ROW_FIELDS`). A different
 * spelling rule from `asset-id`, read out in the same words. */
 | 'store-asset-id'
/** A hostname such as example.com (`DOMAIN_RE`) — no scheme, no path. */
 | 'domain' | 'string-list'
/** A PostHog funnels list (bead `ro-ghis.1`): judged whole by
 * `posthogFunnelsRefusal` in the portable configuration contract. */
 | 'posthog-funnels';
export interface RegisterField {
    /** The JSON key inside a row — also the last pointer token of a `file-json-set`. */
    name: string;
    /** The column heading and the input's label. */
    label: string;
    type: FieldType;
    required: boolean;
    /** The hint under the Add form's input and the column heading's hover: a
     * format or an example, label-length (doc 21 principle 3a — the UX gate
     * reads it). What a field MEANS is its label; what it may hold is its type
     * and rule; a warning about editing it is a rule (`readOnly`), never a
     * sentence here. */
    describe: string;
    /** `enum` only — the complete set of accepted values. */
    values?: readonly string[];
    /** `enum` only — what a value reads as on screen, where the stored value is
     * a key nobody should have to learn (bead `ro-ujb9.135`). The file keeps the
     * value; a value with no entry here shows as itself. */
    valueLabels?: Readonly<Record<string, string>>;
    /** `number` / `integer` bounds. */
    min?: number;
    max?: number;
    /** `string`-ish limits. */
    maxLength?: number;
    /** A RegExp source the whole value must match. */
    pattern?: string;
    /** Another field of the same row whose value this one takes until it is typed
     * into directly — an Add-form default, never a stored derivation (the file
     * keeps both values, because the equality is a convention, not a rule). */
    defaultFrom?: string;
    /**
     * What a RUNTIME candidate list means for this field (bead `ro-g318`).
     * `'closed'` (the default) — the values a page supplies are the whole value
     * domain, and anything else is refused naming the field; `'suggest'` — they
     * are what is already in use, offered as a picker, and a value outside them
     * is a legitimate edit. The picker and the allowlist were one prop until the
     * tracked-query Bet column needed the first without the second.
     */
    candidates?: 'closed' | 'suggest';
    /**
     * This field may be set when the row is CREATED and not afterwards (bead
     * `ro-xhy5`) — a join key whose rename breaks something no table can show.
     * The editor renders it as the value with a lock and the state "Fixed once
     * added" (`fixedFieldLabel`), the Add form marks it before it is typed, and
     * the write lane refuses the set as well, so "read-only" is a rule rather
     * than a suggestion a hand-written changeset can walk past. The way to
     * change one is the row's own Remove and the table's Add, both on screen.
     */
    readOnly?: boolean;
    /** A different STATE than "fixed once added", label-length, for a field no
     * surface here ever writes (the task project's host-linked repository).
     * Only meaningful beside `readOnly`. Never a rationale: why a key is fixed
     * is this file's comment, not the operator's reading. */
    readOnlyReason?: string;
}
/** One "changing X dates Y" pair a register declares (bead `ro-6kd6`). Both
 * names are fields of that register. */
export interface RegisterStamp {
    /** The field whose CHANGE is the decision. */
    when: string;
    /** The date field set to the day the change was applied. */
    field: string;
}
export interface ConfigRegister {
    /** Repo-relative path of the file holding the container. */
    file: string;
    /** RFC-6901 pointer to the container. May carry `{asset}` — see ASSET_PARAM. */
    container: string;
    /** An array of rows, or an object whose keys are the rows. */
    shape: 'array' | 'object';
    /** `object` shape only: what a key must look like. `lane-id` is the one
     * register keyed by something other than an asset — the data-source lanes
     * inside one asset's entry (bead `ro-vu8d.4`). */
    keyRule?: 'asset-id' | 'lane-id';
    /** `array` shape: the field that identifies a row. Absent or `null` for an object shape. */
    keyField?: string | null;
    /** Further fields no two rows may share. The key field is unique by
     * definition and is not repeated here. */
    unique?: readonly string[];
    /**
     * The row's fields, in column order (the key field first). `null` means the
     * row is OPAQUE: it may be added and removed whole, and nothing inside it may
     * be set through this register.
     */
    fields: readonly RegisterField[] | null;
    /** When set, a row MAY be the bare value of that one field rather than an
     * object wrapping it (a string list; a tracked query with no cluster). */
    scalarField?: string;
    /**
     * The field that names the GROUP a row belongs to, where grouping downstream
     * is an exact string match (bead `ro-cnsj`). Two spellings of one group are
     * two groups in the readout and one in the operator's head, so a near miss is
     * refused where it is typed — `clusterSpellingRefusal`.
     */
    clusterField?: string;
    /** This file has NO empty state for the list: an entry holding `[]` is a
     * config error there, and absence is how "none" is said. So the last row out
     * takes the asset's whole entry with it, exactly as the first row in filed
     * one. Only for a per-asset list (one with a `holderOf` holder). */
    emptyIsAbsent?: boolean;
    /** This exact per-asset list may be initialized beside another holder field.
     * Its parent must already exist; no arbitrary parent structure is created. */
    addableContainer?: boolean;
    /** First-row Undo removes this list only, preserving a shared holder. */
    seedUndo?: 'list';
    /**
     * This register's rows carry a claim about ANOTHER file that no field of a row
     * can check (bead `ro-uko8`): `enabled` on the panel-refresh roster asserts
     * that the asset has a live search lane in `config/integrations.json`. The
     * rule is `liveSearchLaneRefusal`; the facts come from whoever holds them.
     */
    requiresLiveSearchLane?: boolean;
    /**
     * Dates this register's rows carry that a write MOVES (bead `ro-6kd6`): when
     * a set changes the `when` field of a row, the pipeline sets that row's
     * `field` to the day it applied. The roster's `since` means "when the decision
     * was taken" and `enabled` is the decision, so editing them as two independent
     * cells left a flipped row claiming a day it was not decided on.
     */
    stamps?: readonly RegisterStamp[];
    /** A register an asset is BORN into and DELETED out of — the add-asset wizard
     * (bead `ro-z349.1`) and the Settings tab's Delete (bead `ro-sk7q`). The set
     * `ADDABLE_CONTAINERS` is derived from it, and a new one here also belongs in
     * the delete's own list of files it clears. */
    assetRegister?: boolean;
    /** The register's name in the UI. */
    label: string;
    /** What one row IS, label-length: the CLI refusal names the register by it
     * and the Tower shows it under the table's title. */
    describe: string;
    /** The README that owns the concept. */
    owner: string;
    /** Where an operator edits it. */
    surface: string;
}
export type ConfigRegisterKey = 'product-use-stages' | 'asset-integrations' | 'asset-lane' | 'asset-counters' | 'asset-pull' | 'domain-costs' | 'recurring-costs' | 'value-events' | 'value-events-assets' | 'ga4-event-params' | 'ga4-event-params-assets' | 'serp-panel-queries' | 'serp-panel-assets' | 'signal-panels' | 'task-hub-spokes' | 'data-source-catalog' | 'entities';
/**
 * What a collector reads for an asset that maps NOTHING on a lane (bead
 * `ro-vu8d.16`), as a code the card draws as a chip (bead `ro-ujb9.96.6.4`)
 * rather than a sentence:
 *
 *  - `google-account-map` — the Google credential's own per-asset map
 *    (`GOOGLE_SIGNAL_ACCOUNTS → properties → <asset> → ga4_property_id /
 *    gsc_site_url`). An install that signed in with Google has no such map, so
 *    it collects nothing until a value is saved. Once every asset the
 *    credential names is mapped here, the collector stops reading that map at
 *    all (bead `ro-90mr`).
 *  - `domain-match` — the asset's own domain matched against the sites the
 *    central Bing account lists as verified; no match fails loudly. A saved
 *    site is what tells two verified sites on one host apart.
 *  - `portfolio-market` — the portfolio baseline market, location 2840
 *    (United States) and language `en`. A field left empty takes the baseline;
 *    a wrong location buys the wrong market's data at the same price.
 *  - `none` — nothing to fall back to: the lane skips this asset and records
 *    why (PostHog has no portfolio-wide project, and a guessed one would read
 *    another site's data).
 */
export type LaneFallback = 'google-account-map' | 'domain-match' | 'portfolio-market' | 'none';
/**
 * One data-source lane's mapping fields, and what the collector reads when
 * THIS asset maps nothing (bead `ro-vu8d.4`). Only the lanes that HAVE a
 * per-asset mapping appear; every other lane's card renders none. A mapped lane
 * needs no code: the collector asks for the saved value, and the card says
 * "Mapped here".
 */
export interface LaneMapping {
    /** Field names of `asset-lane`, in the order the card renders them. */
    fields: readonly string[];
    /** Structured fields saved as one list value, rendered by their own editor
     * below the scalar fields and not counted as the mapping step (bead
     * `ro-ghis.1`: PostHog's funnels). */
    lists?: readonly string[];
    /** What an UNMAPPED lane reads instead (bead `ro-vu8d.16`). */
    fallback: LaneFallback;
}
/**
 * ONE SCALAR SETTING, at one exact pointer (bead `ro-x5gu.8`).
 *
 * A register describes a list; this describes a single number or string sitting
 * beside one, in a file that is deliberately not wholesale-editable. It carries
 * a whole `RegisterField` rather than a bare type so the refusal an operator
 * reads is written in exactly one place, shared with every register column.
 */
export interface ConfigKnob {
    /** Repo-relative path of the file holding it. */
    file: string;
    /** The RFC-6901 pointer — exact; nothing above or below it is licensed. */
    pointer: string;
    /** The knob's name in the UI. */
    label: string;
    /** Display unit beside the control; it does not change the stored value. */
    unit: string;
    /** The rule, spelled as a register column is. `name` is the pointer's last
     * reference token, so a refusal names the key the file actually holds.
     * What changing it COSTS is not a sentence here: /settings draws it as the
     * value beside the field (`collectionVisual`, bead `ro-ujb9.96.6.3`). */
    field: RegisterField;
    /** The README that owns the concept. */
    owner: string;
    /** Where an operator edits it. */
    surface: string;
}
export type ConfigKnobKey = 'panel-refresh-window' | 'panel-freshness-bar';
export interface KnobMatch {
    key: ConfigKnobKey;
    knob: ConfigKnob;
}
export interface RegisterMatch {
    key: ConfigRegisterKey;
    register: ConfigRegister;
    /** Reference tokens past the container: `[]`, `["3"]`, `["3","domain"]`. */
    rest: string[];
    /** The asset a per-asset container matched. */
    params: {
        asset?: string;
    };
    /** The container as it appeared in the pointer, `{asset}` already filled. */
    container: string;
}
/** The whole-asset register a per-asset list's entry has to be filed in first. */
export interface RegisterHolder {
    key: ConfigRegisterKey;
    register: ConfigRegister;
    /** The key inside the holder's entry the list lives at (`valueEvents`). */
    field: string;
}
/** The token that marks the per-asset hole in a container pointer. A register
 * carrying one is scoped to a single asset: `/assets/{asset}/valueEvents` is a
 * different collection for every asset, and the surface editing it is that
 * asset's own page. */
export declare const ASSET_PARAM: string;
/** Data-source lane ids are the catalog's own join keys (`ga4`,
 * `bing-webmaster`, `affiliate-cj`) — the same shape `data-source-catalog`
 * declares for its `id` column, repeated here because it is what a KEY may look
 * like rather than what a field may hold. `scripts/config-registers.test.mjs`
 * asserts every committed lane key matches it. */
export declare const LANE_ID_SOURCE: string;
/**
 * The registers, keyed by the name a UI passes.
 *
 * Field order is COLUMN ORDER — the key field first, then what an operator reads
 * next. `describe` is one line, and it is the same line the CLI prints in a
 * refusal and the Tower shows above the table; two sentences would drift.
 */
export declare const CONFIG_REGISTERS: Record<ConfigRegisterKey, ConfigRegister>;
/** When a save here reaches the collectors, as a code the card draws as a
 * chip (bead `ro-ujb9.96.6.4`): `next-run` when this deployment read the
 * document from the store (every collector run re-reads it), `after-restart`
 * when it is still on the copy compiled in (a hand-edited file reaches the
 * collectors on the next restart or deploy; saving here puts the document in
 * the store, and every run after that reads it). */
export type LaneMappingTiming = 'next-run' | 'after-restart';
/** The one true answer, given where this deployment read the file.
 * `source` is `'store'` or `'file'`, straight off `GET /api/config`. */
export declare function laneMappingTiming(source: 'store' | 'file' | undefined): LaneMappingTiming;
/** The chip for each timing — a state, not the sentence above. */
export declare const LANE_MAPPING_TIMING_LABEL: Readonly<Record<LaneMappingTiming, string>>;
/** The chip for each fallback, beside a lane nothing is mapped on. A mapped
 * lane wears `LANE_MAPPED_LABEL` instead. */
export declare const LANE_FALLBACK_LABEL: Readonly<Record<LaneFallback, string>>;
export declare const LANE_MAPPED_LABEL: string;
/**
 * WHICH MAPPING FIELDS EACH LANE HAS, and WHO READS THEM (bead `ro-vu8d.4`).
 *
 * `asset-lane` declares eight fields because eight is what a lane cell may
 * hold; no lane holds all eight. GA4 maps to a property id, Search Console and
 * Bing to a site, DataForSEO to a location + language. This is that table, and
 * it lives beside the declaration rather than in the Tower so the fields a card
 * renders and the fields the write lane judges cannot drift apart.
 *
 * TWO HONEST STATES, and the card shows whichever is true of THIS asset (beads
 * `ro-vu8d.16`, `ro-ujb9.96.6.4`): "Mapped here" — the collector asks for the
 * value in these fields — or the lane's `fallback`, named per lane in
 * `LaneFallback`. Saving a mapping still does NOT reach into a provider — it
 * steers what the OS asks for, never what the provider holds.
 *
 * WHEN A SAVE TAKES EFFECT IS NOT ONE ANSWER (beads `ro-syok.7`, `ro-7xv2`).
 * Both Workers read the stored document when there is one and the compiled
 * copy when there is not, so `laneMappingTiming` takes the file's entry in
 * `GET /api/config`'s `sources` — the same field the page was built from — and
 * the chip and the behaviour cannot drift.
 */
export declare const LANE_MAPPING: Record<string, LaneMapping | undefined>;
export declare const OPERATOR_LANE_STATES: readonly string[];
/**
 * A DATE A FILE STATES ABOUT ITSELF, AND WHO KEEPS IT TRUE (bead `ro-auav`).
 *
 * Two config files carry a top-level `updated` beside their `version` — the
 * file's own claim about when it last changed. Nothing READS it,
 * which is exactly why it went stale the moment the Tower could write: the
 * add-asset wizard files a roster row, an asset's Sources tab records a posture,
 * and both left the file naming a date before the change. A file that states a
 * fact about itself and is allowed to state it falsely is the same class of
 * defect as a timeline that stops without saying it stopped.
 *
 * SO THE WRITE KEEPS IT. Declared here, once per file that carries one, and
 * applied by `applyDocumentOps` for every entry point at once — the terminal,
 * the dev write lane and the ingest Worker — because a stamp only one of the
 * three made would be a third answer to "when did this file last change".
 *
 * IT REFRESHES, IT NEVER INVENTS. A document that carries no such pointer gains
 * nothing: "we never create structure" is the oldest rule in this pipeline, and a
 * file that has never claimed a date is not lying about one.
 */
export declare const DOCUMENT_STAMPS: Readonly<Record<string, string>>;
/** The pointer a write refreshes in this file, or `null`. */
export declare function documentStamp(file: string): string | null;
/**
 * THE DATES A ROW MOVES WHEN A DECISION MOVES (bead `ro-6kd6`).
 *
 * A register may declare `stamps: [{ when, field }]` — "when a write CHANGES the
 * `when` field of a row, set that row's `field` to the day it was applied". The
 * roster's `since` is the case it was built for: it means *when the decision was
 * taken*, and `enabled` is the decision, so the two were one fact edited as two
 * independent cells and a flip left the row claiming a day it was not decided on.
 *
 * It is a rule of the PIPELINE rather than a second op the browser sends, so the
 * date follows the write wherever the write comes from — a Save, `pnpm
 * config:apply`, or the deployed door — and CollectionEditor's one-changeset-
 * per-cell contract is untouched.
 *
 * `[]` for a register that declares none, which is all of them but one.
 */
export declare function registerStamps(register: ConfigRegister): readonly RegisterStamp[];
/**
 * THE SCALAR KNOBS, declared one pointer at a time (bead `ro-x5gu.8`).
 *
 * A register licenses a LIST — its rows, and the declared fields inside them.
 * Beside those lists sit plain numbers that are every bit as much settings, in
 * files that are deliberately NOT wholesale-editable: `config/signal-panels.json`'s
 * `/refresh` pair. Until this declaration they were reachable from nowhere at
 * all, and `/settings` rendered them as rows pointing at their file because a
 * Save would have been refused.
 *
 * `config/counters.json` `intervalMinutes` was the third, and is retired (bead
 * `ro-ujb9.222`): how often the counter cards are read is the counters job's
 * schedule (`scripts/scheduled-jobs.mts`, changed in Settings → Data
 * collection), and the Tower ages the cards against that schedule.
 *
 * WIDENING `SETTABLE_FILES` WOULD HAVE BEEN THE WRONG FIX. Putting
 * `config/signal-panels.json` there licenses rewriting every roster note. No
 * surface asks for that. So this is the narrow option: one entry per
 * scalar POINTER, carrying the same `RegisterField` a register's column carries
 * — so `fieldRefusal` judges it with the identical sentence — and licensing
 * `file-json-set` at that exact pointer and nowhere else. One level up
 * (`/refresh`) is refused, and so is one level down.
 *
 * ONE DECLARATION, TWO READERS, exactly as with the registers: the core
 * licenses the set from these lines, and the Tower's `KnobEditor` row reads the
 * same label and the same rule from them.
 *
 * WHAT CHANGING ONE COSTS IS DRAWN, NOT WRITTEN (beads `ro-ujb9.96.6.3`,
 * `ro-ujb9.96.6.17`). A cadence knob with no visible cost is an invitation to
 * make the OS read more often and find out afterwards what that bought — so
 * /settings puts the cost beside the field as a value (`collectionVisual`:
 * the price per pass, the freshness bar's fit inside the window). The
 * `consequence` paragraphs that used to live here were rendered by nothing
 * once that shipped; what each knob costs is in the comment above it.
 *
 * DELIBERATELY NOT DECLARED: `config/beads.json` `/hub` (host, port, dataDir).
 * That is how `bd` reaches the Dolt server on this machine — wiring rather than
 * a portfolio setting, and nothing a browser should be able to move.
 */
export declare const CONFIG_KNOBS: Record<ConfigKnobKey, ConfigKnob>;
/**
 * The files a `file-json-set` may edit at ANY pointer — the original safety
 * allowlist, unchanged in meaning since it was written.
 *
 * It is deliberately NOT "every file with a register": a register licenses its
 * own declared fields and nothing else, while these four are wholesale editable
 * because their whole contents are settings the Tower renders as knobs.
 * `config/integrations.json` is in both lists, which is how an asset's lane
 * status is still written while its catalog rows are field-validated.
 */
export declare const SETTABLE_FILES: readonly string[];
/** `[key, register]` for every declaration, in file order. */
export declare function registerEntries(): [ConfigRegisterKey, ConfigRegister][];
/** Every register declared for one file, in declaration order. */
export declare function registersForFile(file: string): [ConfigRegisterKey, ConfigRegister][];
/** Every file any register names — the add/remove boundary. */
export declare function registerFiles(): string[];
/** `[key, knob]` for every scalar knob, in declaration order. */
export declare function knobEntries(): [ConfigKnobKey, ConfigKnob][];
/** Every knob declared for one file, in declaration order. */
export declare function knobsForFile(file: string): [ConfigKnobKey, ConfigKnob][];
/**
 * The knob a pointer IS, or null.
 *
 * An exact match and nothing else — no prefix, no parent, no child. That is the
 * whole permission: `/refresh/windowDays` is settable, `/refresh` is not, and
 * neither is anything below either of them.
 */
export declare function matchKnob(file: string, pointer: string): KnobMatch | null;
/** The container pointer with `{asset}` filled in. Throws when a per-asset
 * register is asked for a container without one. */
export declare function resolveContainer(register: ConfigRegister, params?: {
    asset?: string;
}): string;
/** A RegExp matching this register's container at the START of a pointer, with
 * the asset (when the register has one) as capture group 1. */
export declare function containerRegExp(register: ConfigRegister): RegExp;
/**
 * Which register (if any) owns a pointer in a file, and what is left of the
 * pointer past its container.
 *
 * `rest` is the remaining reference tokens: `[]` for the container itself,
 * `['3']` for a row, `['3','domain']` for one field of a row. `params` carries
 * the asset a per-asset container matched.
 */
export declare function matchRegister(file: string, pointer: string): RegisterMatch | null;
/**
 * The register that files this per-asset list's HOLDER entry, and the key the
 * list lives at inside it — or `null` for a register that needs no holder.
 *
 * A pointer never creates structure, and `/assets/<asset>/valueEvents` cannot be
 * appended to until `/assets/<asset>` exists. An asset with NO entry is the
 * common case in every one of these files (absence is "not declared", by
 * design), so a surface adding the FIRST row has to file the whole entry
 * instead: `{ valueEvents: [row] }` at `/assets/<asset>`. That stays one op and
 * one changeset, and one delete at the same pointer reverses it exactly.
 *
 * It is DERIVED, never declared twice: a per-asset list's container is always
 * `<holder container>/{asset}/<field>`, so the holder is the object register in
 * the same file whose container is that prefix. A register pair therefore
 * cannot drift, and a new pair needs nothing here.
 */
export declare function holderOf(register: ConfigRegister): RegisterHolder | null;
/** The one field declaration a name resolves to, or null. */
export declare function fieldOf(register: ConfigRegister, name: string): RegisterField | null;
/** Is this reference token a legal ROW address in this register's container? */
export declare function isRowToken(register: ConfigRegister, token: string): boolean;
/**
 * MAY AN INSERT INTO THIS ARRAY NAME A POSITION? (bead `ro-asj9`)
 *
 * A delete SPLICES a row out, so an undo that could only append returned it at
 * the END of the list — the row came back, its neighbours' order did not, which
 * is visible wherever the table is drawn in file order (/financials is). An
 * indexed insert is what RFC 6902's `add` has always meant for an array, and it
 * is what makes an undo an undo.
 *
 * Every array register whose rows have DECLARED FIELDS may name one. The one
 * that may not is the only opaque array in this map, `config/pull.json`: its
 * rows are whole asset endpoints the wizard files and unfiles, nothing reads
 * their position, and an index there would be a claim about nothing. Derived
 * rather than declared a second time, because those are the same fact — a
 * register whose rows are opaque is one nothing addresses INSIDE.
 *
 * The guard is not weakened. An insert has never carried an `expect` (its guard
 * is fixed at "nothing is there yet"), so the position an append landed at was
 * never checked either; what is new is that an index past the end of the list is
 * refused loudly instead of quietly appending as if it had said `-`.
 */
export declare function positionedInsert(register: ConfigRegister): boolean;
/** How a refusal spells where an entry may be added / removed. Quoting follows
 * the shape: an array append is a literal token and reads as one. */
export declare function legalRowPointer(register: ConfigRegister, kind: string): string;
/**
 * Check one value against one field declaration.
 *
 * Returns `null` when it is fine, or the RULE it broke as a sentence that
 * names the field by its label — the same sentence the CLI prints, the lane
 * returns in a 422 and the Tower shows under the input, because a refusal an
 * operator reads twice in two wordings is two refusals.
 */
export declare function fieldRefusal(field: RegisterField, value: unknown): string | null;
/** The fields of a site's row in the store. */
export type SiteRowField = 'id' | 'displayName' | 'domain' | 'status' | 'senseOnly';
/**
 * A SITE'S ROW IN THE STORE (the `assets` table), field by field, as the
 * ingest's site lanes check it — Add a site's create, the Settings tab's column
 * writes, the empty-site delete, and every lane that names a site in its body
 * (`workers/ingest/src/routes/validate.ts` `declaredString`, bead
 * `ro-ujb9.183`).
 *
 * Not a register: the row lives in the store, not in a file, and nothing here
 * licenses a write. It is declared as fields so that its refusals are worded by
 * `fieldRefusal`, like every register's — "Domain must be a hostname such as
 * example.com", "Site must be a site id" — and never by the key a request body
 * carries or the retired noun "property" (D31). The labels are the ones beside
 * the Tower's inputs (Add a site's Domain; the Settings tab's Display name and
 * Automation).
 */
export declare const SITE_ROW_FIELDS: Readonly<Record<SiteRowField, RegisterField>>;
/**
 * A refusal and the field it is about (bead `ro-ujb9.184`): `field` is the
 * declared field's `name` whose rule broke, or null when the refusal is the
 * row's or the list's as a whole (not an object, an undeclared key, no room).
 * The Add form outlines that one input and no other; the lane and the CLI read
 * only `message`, through `rowRefusal` and `duplicateKey`.
 */
export interface RowIssue {
    field: string | null;
    message: string;
}
/**
 * Check a whole ROW against a register.
 *
 * A scalar register (a string list, a tracked query with no cluster) accepts the
 * bare value as well as the one-field object; everything else must be an object,
 * every required field present, and NO undeclared key — an unknown key is a
 * typo that would land in a config file nobody validates again.
 */
export declare function rowIssue(register: ConfigRegister, value: unknown): RowIssue | null;
/** `rowIssue`'s sentence alone — what the lane and the CLI print. */
export declare function rowRefusal(register: ConfigRegister, value: unknown): string | null;
/**
 * A FIELD MAY BE SET WHEN THE ROW IS CREATED AND NOT AFTERWARDS (bead `ro-xhy5`).
 *
 * The declared keys whose rename silently breaks something the table cannot
 * show — the data-source catalog's `id` (every asset entry and every collector
 * names the source by it), a recurring cost's `id` (part of the ledger's
 * idempotency key, so a rename re-books every month already booked), a domain
 * order's `domain` (what the registrar's next export is reconciled against),
 * an entity's `slug` — and one figure, a recurring cost's monthly amount (every
 * booked month was booked at it). Each once carried the warning in a sentence;
 * this is the control that does not offer the edit, and the lock with "Fixed
 * once added" (`fixedFieldLabel`) is all the table says (bead
 * `ro-ujb9.96.6.17`).
 *
 * IT IS A LANE RULE, NOT A UI ONE. A UI-only read-only field is a suggestion: a
 * hand-written changeset would still rename the key, and the pipeline would
 * apply it. So `config-apply-core.mjs` refuses the set too — which also refuses
 * a hand-authored RENAME changeset, and that is the right answer, because a
 * rename needs matching edits in files (and collectors) this pipeline cannot
 * make. The way to change one is the way the money and the code already went:
 * remove the row and record the new one.
 *
 * ADDING IS UNTOUCHED. A new row must set its key, so `blankRow`, the Add form
 * and `file-json-insert` never ask this.
 */
export declare function readOnlyFieldRefusal(field: RegisterField | null | undefined): string | null;
/** The state a fixed field shows beside its lock, in the table and on the Add
 * form: a label, not a rationale. */
export declare const FIXED_FIELD_LABEL: string;
/** What a read-only field's lock says: its own state where it declares one (a
 * field no surface here writes), otherwise "Fixed once added". `null` for a
 * field that is not read-only. */
export declare function fixedFieldLabel(field: RegisterField | null | undefined): string | null;
/**
 * `readOnlyFieldRefusal` for a whole ROW being replaced at its own pointer.
 *
 * A row is set whole for two honest reasons — a scalar row has nothing below it
 * to address, and clearing an optional field removes the key rather than writing
 * `null` — and neither of them touches a read-only field. So the question is not
 * "is the row settable" but "did this write MOVE a read-only value": an
 * unchanged key rides along, a changed one is the rename above by another
 * pointer. `before` is the op's own `expect`, which is the row as the file held
 * it, so no second read is needed.
 */
export declare function readOnlyRowRefusal(register: ConfigRegister, before: JsonValue, after: JsonValue): string | null;
/**
 * A value outside the CANDIDATE SET a field's value domain actually has, as the
 * same kind of sentence every other refusal here is (bead `ro-x5gu.10`).
 *
 * `fieldRefusal` can only judge SHAPE, because a declaration cannot know which
 * asset ids this OS holds — those are rows in the store and keys in
 * `config/integrations.json`, neither of which this plain-Node module may read.
 * So the candidates arrive from whoever DOES know: the browser passes the
 * integration matrix's asset list (`CollectionEditor`'s `fieldOptions`), and the
 * apply pipeline passes the roster below. Same function, same sentence, so a
 * typo cannot be refused in one wording upstream and another downstream.
 *
 * AN EMPTY OR ABSENT SET IS "NOBODY ANSWERED", never "nothing is allowed": a
 * page whose own source has not loaded, and a temp repo with no roster file,
 * both refuse nothing rather than refusing everything.
 */
export declare function candidateRefusal(field: RegisterField | null | undefined, candidates: readonly string[] | null | undefined, value: unknown): string | null;
/**
 * ONE CLUSTER, ONE SPELLING (bead `ro-cnsj`).
 *
 * `config/serp-panel.README.md`'s rule, and the collector's: grouping is an
 * exact string match on the stored label, so "Item head" and "Item Head" are two
 * bets in the readout and one bet in the operator's head. The collector
 * (`workers/ingest/src/dataforseo-dumps.ts` `trackedLabel`) refuses the asset's
 * WHOLE panel for that run with `config_invalid`, so relabelling one row of a
 * six-row cluster writes a config that fails next Monday rather than one that
 * reads wrong — loud, but a week late and a whole panel wide.
 *
 * This is a rule about the LIST, and the only fact it needs is the list itself,
 * which is why `CollectionEditor` applies it without the page's help: nothing
 * outside the rows decides it.
 *
 * `exceptToken` is the row being edited — its own current spelling is not a
 * clash with itself, so recasing a cluster only ONE row uses is allowed, and
 * that is the honest reading: the collector refuses two spellings coexisting,
 * never a rename. `null` for the Add form, where every row is somebody else's.
 *
 * Only a NEAR MISS is refused. A label that matches an existing one exactly
 * joins that cluster, and a genuinely new label starts a new one — moving a term
 * between bets is a legitimate edit the collector has no opinion about.
 */
export declare function clusterSpellingRefusal(register: ConfigRegister, rows: readonly JsonValue[] | null | undefined, exceptToken: string | null, field: RegisterField, value: unknown): string | null;
/**
 * The lanes `config/signal-panels.README.md` counts as a SEARCH lane. Its own
 * validation snippet reads exactly these three out of `config/integrations.json`.
 */
export declare const SEARCH_LANES: readonly string[];
/** One asset's `config/integrations.json` entry as a flat `lane → status` map —
 * the shape `liveSearchLaneRefusal` judges, so the browser (which holds the same
 * facts in the Tower's own richer shape) and the pipeline hand it the same
 * thing. Anything that is not an entry reads as `null`: nobody answered. */
export declare function laneStatuses(entry: unknown): Record<string, string> | null;
/**
 * TURNING A ROSTER ROW ON IS A CLAIM ABOUT ANOTHER FILE (bead `ro-uko8`).
 *
 * `config/signal-panels.README.md` states the rule — *an asset is `enabled`
 * here when at least one of its `gsc` / `ga4` / `bing-webmaster` lanes is `live`
 * in `config/integrations.json`* — and its own validation snippet fails the
 * roster with the sentence below. Before the Growth tab, the check was a person
 * reading that README beside the file; a click needs the rule itself.
 *
 * WHY IT MATTERS: a refresh pass over an asset with no live lane writes an EMPTY
 * panel dir, and doc 20 says an empty panel dir is indistinguishable on disk
 * from a collapsed one — the exact ambiguity the roster exists to prevent.
 *
 * `statuses` is that asset's lanes as `laneStatuses` returns them. `null` or an
 * empty map is "nobody answered" and refuses nothing, the same reading every
 * other runtime-fact rule here gives an absent answer. Only `enabled: true` is
 * ever refused: turning a row OFF is always allowed, and always should be.
 */
export declare function liveSearchLaneRefusal(field: RegisterField, statuses: Record<string, string> | null | undefined, value: unknown): string | null;
/**
 * WHICH REGISTER'S KEYS ARE THE ASSET IDS THIS OS HAS (bead `ro-x5gu.10`).
 *
 * `config/integrations.json` `/assets` carries one entry per asset — the
 * add-asset wizard files it on Create, the Settings tab's Delete removes it, and
 * `config/signal-panels.README.md` makes "the roster's keys equal this file's
 * keys" a stated invariant. It is also exactly the list the Tower's integration
 * matrix filters the store by, which is why the browser and the pipeline end up
 * checking the same names.
 *
 * It is named by register KEY rather than by path so the file and container are
 * still declared once, above.
 */
export declare const ASSET_ROSTER_REGISTER: ConfigRegisterKey;
/** The roster's own file — what a caller has to read before it can pass
 * candidates. */
export declare function assetRosterFile(): string;
/**
 * The asset ids a PARSED roster file declares, or `[]`.
 *
 * `[]` means "this file said nothing" and therefore refuses nothing — the same
 * reading `candidateRefusal` gives an empty list, and the reason a throwaway
 * repo with no `config/integrations.json` still applies its changesets.
 */
export declare function rosterAssetIds(doc: unknown): string[];
/** Every declared field of a register whose value domain is the asset roster —
 * the fields `candidateRefusal` is asked about. */
export declare function assetIdFields(register: ConfigRegister): RegisterField[];
/**
 * Is a row already using a value that has to be its own? The uniqueness the
 * shapes imply but the pointer cannot express — a duplicate `id` in
 * recurring-costs re-books a month, a duplicate `domain` double-counts an order.
 * Read by the Tower before it sends, so the operator sees it beside the field
 * rather than as a 422.
 *
 * The key field is always one of these. A register may name MORE in `unique`,
 * for the columns that are not the row's identity but still may not repeat — a
 * task-hub project's bead prefix and its database, either of which appearing
 * twice makes two projects indistinguishable downstream.
 */
export declare function duplicateIssue(register: ConfigRegister, rows: readonly JsonValue[] | null | undefined, value: JsonValue): RowIssue | null;
/** `duplicateIssue`'s sentence alone. */
export declare function duplicateKey(register: ConfigRegister, rows: readonly JsonValue[] | null | undefined, value: JsonValue): string | null;
/** One stored item as a field map, expanding a scalar item into its one field.
 * The single way a register's rows become table rows. */
export declare function rowValue(register: ConfigRegister, item: JsonValue): {
    [key: string]: JsonValue;
};
