// Generated by pnpm generate. Edit the sibling .mts source.
import type { JsonValue } from './config-documents.mjs';
/** Preserve the ordinary Worker's existing coordination-file exclusion. */
export declare function collectorDefaultDocument(file: string): JsonValue | null;
