// Generated by pnpm config:generate. Edit the sibling .mts source.
import type { Changeset, DocumentReader, Mismatch, Resolved, StoreLane } from './config-documents.mjs';
export { ADDABLE_CONTAINERS, ADDABLE_DOCUMENTS, ALLOWED_FILES, ASSET_ID_RE, ASSET_STATUS, CONFIG_DOCUMENT_FILES, CONFIG_KNOBS, CONFIG_REGISTERS, ChangesetError, DISPLAY_NAME_MAX, DOCUMENT_STAMPS, MISSING, STORE_COLUMNS, applyDocumentOps, deepEqual, expectsAbsent, parsePointer, pointerDelete, pointerGet, pointerInsert, pointerSet, resolveOps, serializeDocument, validateSchemaAndSafety, } from './config-documents.mjs';
export type { Changeset, ChangesetOp, DocumentReader, FileJsonDeleteOp, FileJsonInsertOp, FileJsonSetOp, JsonValue, Mismatch, Resolved, StoreAssetSetOp, StoreLane, } from './config-documents.mjs';
export interface RepoOption {
    repoRoot?: string;
}
/** This repo, as seen from scripts/. Every function takes an override. */
export declare const DEFAULT_REPO_ROOT: string;
/** Where an applied changeset is archived: `changesets/` in this
 * installation's folder, absolute. */
export declare function changesetsDir({ repoRoot }?: RepoOption): string;
/**
 * Read one config document off disk, parsed — the `readDocument` the filesystem
 * entry points hand to `resolveOps`.
 *
 * It throws a plain Error; `resolveOps` is what turns that into the
 * `could not read/parse <file>: <why>` refusal both lanes have always printed.
 */
export declare function fileDocumentReader({ repoRoot }?: RepoOption): DocumentReader;
/**
 * The product's own default for one document — the copy both Workers compile
 * in and every reader falls back to per key — as the `readBuiltIn` the
 * filesystem entry points hand to `resolveOps` (bead `ro-dk4u`).
 */
export declare function builtInDocumentReader({ repoRoot }?: RepoOption): DocumentReader;
export declare function resolve(cs: Changeset, store: StoreLane | null, { repoRoot }?: RepoOption): Promise<{
    resolved: Resolved[];
    mismatches: Mismatch[];
    fileCache: Map<string, unknown>;
}>;
export declare function applyFileOps(resolved: Resolved[], fileCache: Map<string, unknown>, { repoRoot, at }?: RepoOption & {
    at?: string;
}): Promise<string[]>;
/**
 * Write one whole document to this installation's copy — what
 * `pnpm config:export` does for every document the store holds, in the same
 * bytes a Save would have left. Returns the path written, as a commit names it.
 */
export declare function writeDocumentFile(rel: string, doc: unknown, { repoRoot }?: RepoOption): Promise<string>;
/** Read one config document off disk, parsed — the seed side of the same coin:
 * this installation's copy, else the product's default. Neither there answers
 * `null` rather than throwing, because "this install does not carry that
 * register" is an ordinary state for a seed to be in. */
export declare function readDocumentFile(rel: string, { repoRoot }?: RepoOption): Promise<unknown>;
/** Read this installation's own copy of a document, or `null` when it has
 * none — what `pnpm config:export` compares the store against. The product
 * default never stands in: an export is the installation's own. */
export declare function readInstalledDocument(rel: string, { repoRoot }?: RepoOption): Promise<unknown>;
export declare function nextArchiveNumber({ repoRoot }?: RepoOption): Promise<number>;
/** Write the applied changeset to its numbered archive; returns its path as a
 * commit names it, which is also what the caller commits. */
export declare function archiveChangeset(cs: Changeset, { repoRoot }?: RepoOption): Promise<string>;
/** `annotations.kind` for a stage move. Not a new kind: `annotations.kind` is a
 * CHECK constraint in db/0001, and `config` is the closest honest member — a
 * stage is a stored setting on the asset. */
export declare const LIFECYCLE_ANNOTATION_KIND: string;
/** What a lifecycle-move `ref` starts with, so an operator-written ref can never
 * be mistaken for one. */
export declare const LIFECYCLE_REF_PREFIX: string;
/**
 * The `ref` one stage move is stored under — `lifecycle:baselining>retired`.
 *
 * Machine-readable ASCII, and part of the row's `(asset, at, kind, ref)`
 * identity, so a retried write collapses into one row and two different moves
 * recorded in the same second stay two.
 */
export declare function lifecycleMoveRef({ from, to }: {
    from: string;
    to: string;
}): string;
