// Generated by pnpm generate. Edit the sibling .mts source.
import type { Changeset, DocumentReader, Mismatch, Resolved, StoreLane } from './config-documents.mjs';
export { ADDABLE_CONTAINERS, ADDABLE_DOCUMENTS, ALLOWED_FILES, ASSET_ID_RE, ASSET_STATUS, CONFIG_DOCUMENT_FILES, CONFIG_KNOBS, CONFIG_REGISTERS, ChangesetError, DISPLAY_NAME_MAX, DOCUMENT_STAMPS, MISSING, STORE_COLUMNS, applyDocumentOps, deepEqual, expectsAbsent, parsePointer, pointerDelete, pointerGet, pointerInsert, pointerSet, resolveOps, serializeDocument, validateSchemaAndSafety, } from './config-documents.mjs';
export type { Changeset, ChangesetOp, DocumentReader, FileJsonDeleteOp, FileJsonInsertOp, FileJsonSetOp, JsonValue, Mismatch, Resolved, StoreAssetSetOp, StoreLane, } from './config-documents.mjs';
export interface RepoOption {
    repoRoot?: string;
}
/** This repo, as seen from scripts/. Every function takes an override. */
export declare const DEFAULT_REPO_ROOT: string;
/** Where an applied changeset is archived: `changesets/` in this
 * installation's folder, absolute. */
export declare function changesetsDir({ repoRoot }?: RepoOption): string;
/**
 * The `readDocument` the filesystem entry points hand to `resolveOps`. It
 * throws a plain Error; `resolveOps` turns that into the `could not
 * read/parse` refusal.
 */
export declare function fileDocumentReader({ repoRoot }?: RepoOption): DocumentReader;
/**
 * The product's own default for one document — the copy every reader falls
 * back to per key — as the `readBuiltIn` the filesystem entry points hand to
 * `resolveOps`.
 */
export declare function builtInDocumentReader({ repoRoot }?: RepoOption): DocumentReader;
/** `resolveOps` over the files on disk. `fileCache` is the `documents` map:
 * the parsed files, read once and mutated by `applyFileOps`. */
export declare function resolve(cs: Changeset, store: StoreLane | null, { repoRoot }?: RepoOption): Promise<{
    resolved: Resolved[];
    mismatches: Mismatch[];
    fileCache: Map<string, unknown>;
}>;
/**
 * Apply the file half: each touched file written exactly once, to this
 * installation's copy. The store half belongs to the caller. Returns the
 * written paths, as a commit names them. `at` is the changeset's own
 * `createdAt`, passed through to the stamps a write refreshes; absent ⇒ now.
 */
export declare function applyFileOps(resolved: Resolved[], fileCache: Map<string, unknown>, { repoRoot, at }?: RepoOption & {
    at?: string;
}): Promise<string[]>;
/**
 * Write one whole document to this installation's copy — what
 * `pnpm config:export` does for every document the store holds, in the same
 * bytes a Save would have left. Returns the path written, as a commit names it.
 */
export declare function writeDocumentFile(rel: string, doc: unknown, { repoRoot }?: RepoOption): Promise<string>;
/** This installation's copy, else the product's default, parsed; `null` when
 * neither is there, because "this install does not carry that register" is
 * an ordinary state for a seed to be in. */
export declare function readDocumentFile(rel: string, { repoRoot }?: RepoOption): Promise<unknown>;
/** Read this installation's own copy of a document, or `null` when it has
 * none — what `pnpm config:export` compares the store against. The product
 * default never stands in: an export is the installation's own. */
export declare function readInstalledDocument(rel: string, { repoRoot }?: RepoOption): Promise<unknown>;
export declare function nextArchiveNumber({ repoRoot }?: RepoOption): Promise<number>;
/** Write the applied changeset to its numbered archive; returns its path as a
 * commit names it, which is also what the caller commits. */
export declare function archiveChangeset(cs: Changeset, { repoRoot }?: RepoOption): Promise<string>;
