// Generated by pnpm config:generate. Edit the sibling .mts source.
/** Shared server registry identity. This exports no executable capability. */
export declare const DEMO_ACTIVITY_DEFINITION: Readonly<{
    key: "demo-activity";
    version: "v1";
    steps: readonly [Readonly<{
        key: "observations";
        kind: "database";
        action: "workflows.run";
    }>, Readonly<{
        key: "task";
        kind: "effect";
        action: "tasks.write";
    }>, Readonly<{
        key: "task-summary";
        kind: "database";
        action: "workflows.run";
    }>];
}>;
export declare function demoActivityPrefix(scenarioHash: string): string;
