// Generated by pnpm config:generate. Edit the sibling .mts source.
import { type DemoScenario } from './demo-scenario.mjs';
export declare const DEMO_ACTIVITY_VERSION = 2;
export declare const DEMO_ACTIVITY_LIMITS: Readonly<{
    daysPerBatch: 7;
    daysFromAnchor: 36525;
}>;
export interface DemoActivitySignal {
    integration: 'ga4' | 'gsc';
    propertyRef: string;
    credentialRef: 'synthetic-demo';
    timeZone: 'UTC';
    /** Null is a deliberately missing report, never a reported zero. */
    observations: {
        date: string;
        metric: string;
        value: number;
    }[] | null;
}
export interface DemoActivityPulse {
    asset: string;
    generatedAt: string;
    capabilities: string[];
    metrics: Record<string, {
        last24h: number;
        avg7d: number;
        total: number;
    }>;
}
export interface DemoActivityMoney {
    asset: string;
    kind: 'revenue' | 'cost';
    family: string;
    period: string;
    amountMinor: number;
    currency: 'USD';
    bookingState: 'reconciled';
    source: 'demo-simulator' | 'mediavine';
    externalId: string;
    note: string;
    coverageStart: string;
    coverageEnd: string;
    coverageComplete: boolean;
}
export interface DemoTaskIntention {
    asset: string;
    key: string;
    phase: 'create' | 'start' | 'complete';
    title: string;
    description: string;
    acceptance: string;
    closeReason: string;
}
/** A synthetic change recorded when a site's ship task closes, with the
 * 28-day comparison the ordinary watch-window writer registers for it. The
 * release's outcome check reads the comparison later; nothing here claims a
 * result. */
export interface DemoChange {
    asset: string;
    at: string;
    kind: 'deploy';
    ref: string;
    note: string;
    watch: {
        metricIntegration: 'ga4';
        metric: 'sessions';
        baselineStart: string;
        baselineEnd: string;
        checkOffsets: number[];
        thresholds: {
            ship: {
                direction: 'up';
                min_delta_pct: number;
            };
            kill: {
                direction: 'down';
                min_delta_pct: number;
            };
        };
        note: string;
    };
}
export interface DemoSearchMover {
    query: string;
    currentImpressions: number;
    previousImpressions: number;
    impressionDelta: number;
    impressionDeltaPercent: number;
    currentPosition: number;
    previousPosition: number;
    positionImprovement: number;
}
export interface DemoSearchFinding {
    key: string;
    kind: 'insight' | 'warning';
    title: string;
    summary: string;
    whyItMatters: string;
    primary: {
        value: string;
        label: string;
    };
    confidence: 'medium';
    windowStart: string;
    windowEnd: string;
    evidence: {
        label: string;
        value: string;
        detail?: string;
    }[];
    sources: string[];
    caveat: string;
}
/** A site's weekly synthetic search report, in the shape the executive
 * snapshot writer stores and the Overview's Search movers read: this week's
 * queries against last week's, and the one finding the week leads with. */
export interface DemoSearchReport {
    schemaVersion: 1;
    asset: string;
    generatedAt: string;
    windowStart: string;
    windowEnd: string;
    sourceArchiveCount: number;
    items: DemoSearchFinding[];
    suppressedItems: never[];
    methodology: string[];
    searchQueries: {
        google: {
            provider: 'google';
            currentStart: string;
            currentEnd: string;
            previousStart: string;
            previousEnd: string;
            daysPerWindow: 7;
            movers: DemoSearchMover[];
            evidence: {
                label: string;
                value: string;
                detail?: string;
            }[];
            source: string;
            caveat: string;
        };
        bing: null;
        dataforseo: null;
    };
}
/** One quarter-hour refresh of today's provisional traffic and search
 * (the `counters` lane's Google step). A missing day stays missing. */
export interface DemoActivityCollection {
    synthetic: true;
    version: 2;
    scenarioHash: string;
    at: string;
    date: string;
    assets: {
        asset: string;
        signals: DemoActivitySignal[];
    }[];
}
export interface DemoActivityDay {
    synthetic: true;
    version: 2;
    scenarioHash: string;
    date: string;
    key: string;
    assets: {
        asset: string;
        signals: DemoActivitySignal[];
        pulse: DemoActivityPulse | null;
    }[];
    money: DemoActivityMoney[];
    /** Each site's weekly cycle, in site order; a day may hold several. */
    tasks: DemoTaskIntention[];
    changes: DemoChange[];
    reports: DemoSearchReport[];
}
/** Share of a day's activity in each UTC hour: quiet overnight, busiest early
 * afternoon, an evening bump. The live minute pulse and the quarter-hour
 * refresh read the same day shape. */
export declare const DEMO_HOUR_SHARE: readonly number[];
/** The share of a UTC day's activity counted by the end of `minuteOfDay`. */
export declare function demoDayShare(minuteOfDay: number): number;
/** Capture one original scenario. Advancing time never regenerates its seed,
 * asset identities, historical incidents, task history or accounting anchor.
 * Cumulative counters use bounded closed-form sums, not a scan of elapsed days.
 * This factory is pure; deployment separately binds workspace and authority. */
export declare function createDemoActivity(input: DemoScenario): {
    day(date: string): DemoActivityDay;
    batch(first: string, last: string): DemoActivityDay[];
    collection(at: string): DemoActivityCollection;
    adRevenue(asset: string, date: string): number;
};
