// Generated by pnpm config:generate. Edit the sibling .mts source.
import { type DemoScenario } from './demo-scenario.mjs';
export declare const DEMO_ACTIVITY_VERSION = 1;
export declare const DEMO_ACTIVITY_LIMITS: Readonly<{
    daysPerBatch: 7;
    daysFromAnchor: 36525;
}>;
export interface DemoActivitySignal {
    integration: 'ga4' | 'gsc';
    propertyRef: string;
    credentialRef: 'synthetic-demo';
    timeZone: 'UTC';
    /** Null is a deliberately missing report, never a reported zero. */
    observations: {
        date: string;
        metric: string;
        value: number;
    }[] | null;
}
export interface DemoActivityPulse {
    asset: string;
    generatedAt: string;
    capabilities: string[];
    metrics: Record<string, {
        last24h: number;
        avg7d: number;
        total: number;
    }>;
}
export interface DemoActivityMoney {
    asset: string;
    kind: 'revenue' | 'cost';
    family: string;
    period: string;
    amountMinor: number;
    currency: 'USD';
    bookingState: 'reconciled';
    source: 'demo-simulator';
    externalId: string;
    note: string;
    coverageStart: string;
    coverageEnd: string;
    coverageComplete: boolean;
}
export interface DemoTaskIntention {
    asset: string;
    key: string;
    phase: 'create' | 'start' | 'complete';
    title: string;
    description: string;
    acceptance: string;
    closeReason: string;
}
export interface DemoActivityDay {
    synthetic: true;
    version: 1;
    scenarioHash: string;
    date: string;
    key: string;
    assets: {
        asset: string;
        signals: DemoActivitySignal[];
        pulse: DemoActivityPulse | null;
    }[];
    money: DemoActivityMoney[];
    task: DemoTaskIntention | null;
}
/** Capture one original scenario. Advancing time never regenerates its seed,
 * asset identities, historical incidents, task history or accounting anchor.
 * Cumulative counters use bounded closed-form sums, not a scan of elapsed days.
 * This factory is pure; deployment separately binds workspace and authority. */
export declare function createDemoActivity(input: DemoScenario): {
    day(date: string): DemoActivityDay;
    batch(first: string, last: string): DemoActivityDay[];
};
