// Generated by pnpm config:generate. Edit the sibling .mts source.
import { type DemoScenario } from './demo-scenario.mjs';
interface SavedDocument {
    file: string;
    version: number | null;
    source: string;
    body: unknown;
}
interface DisplayHelpers {
    getConfigDocuments(capability: unknown, files: string[]): Promise<SavedDocument[]>;
    seedConfigDocuments(capability: unknown, input: {
        actor: string;
        documents: ReturnType<typeof generateDemoDisplay>;
    }, now: number): Promise<{
        ok: boolean;
        skipped?: unknown[];
    }>;
}
/** Only observed nightly totals are selected; no counter fetch source exists. */
export declare function generateDemoDisplay(scenario: DemoScenario): {
    'config/tower.json': {
        readme: string;
        wall: {
            layout: import("./wall-layout.mjs").WallLayout;
            history: never[];
        };
        countdown: {
            emoji: string;
            label: string;
            targetAt: string;
        };
    };
    'config/counters.json': {
        assets: {
            [k: string]: {
                heading: string;
                cards: {
                    metric: string;
                    label: string;
                }[];
            };
        };
    };
};
/** The normal versioned writer; existing documents or exports are never adopted. */
export declare function seedDemoDisplay({ home, installation, scenario, capability, helpers }: {
    home: string;
    installation: string;
    scenario: DemoScenario;
    capability: unknown;
    helpers: DisplayHelpers;
}): Promise<{
    files: string[];
    documents: {
        'config/tower.json': {
            readme: string;
            wall: {
                layout: import("./wall-layout.mjs").WallLayout;
                history: never[];
            };
            countdown: {
                emoji: string;
                label: string;
                targetAt: string;
            };
        };
        'config/counters.json': {
            assets: {
                [k: string]: {
                    heading: string;
                    cards: {
                        metric: string;
                        label: string;
                    }[];
                };
            };
        };
    };
}>;
export {};
