// Generated by pnpm config:generate. Edit the sibling .mts source.
export type DemoTaskStatus = 'open' | 'in_progress' | 'blocked' | 'deferred' | 'closed';
export interface DemoTaskEvent {
    at: string;
    status: DemoTaskStatus;
    assignee: string;
}
export interface DemoTaskFact {
    id: string;
    asset: string;
    prefix: string;
    title: string;
    description: string;
    acceptance: string;
    issueType: 'task' | 'epic' | 'gate';
    priority: number;
    events: DemoTaskEvent[];
    parent?: string;
    blocks?: string;
    dependsOn?: string;
    human?: boolean;
    deferUntil?: string;
    closeEvidence?: string;
    comments: {
        author: string;
        text: string;
        at: string;
    }[];
}
type Asset = {
    id: string;
    prefix: string;
    name: string;
    createdAt: string;
};
/** Facts describe fictional work, never provider execution or causal returns. */
export declare function generateDemoTaskFacts({ assets, seed, referenceDate, cutoff }: {
    assets: readonly Asset[];
    seed: string;
    referenceDate: string;
    cutoff: string;
}): {
    projects: {
        asset: string;
        prefix: string;
        database: string;
    }[];
    tasks: DemoTaskFact[];
    storyIds: {
        repair: string;
        readback: string;
        problem: string;
        ship: string;
        shipReadback: string;
    };
};
/** Import the dated facts through bd; no task-table SQL writer exists here. */
export declare function demoTaskIssuesAt(tasks: readonly DemoTaskFact[], instant: string): Record<string, unknown>[];
export {};
