// Generated by pnpm generate. Edit the sibling .mts source.
import { type DemoScenario } from './demo-scenario.mjs';
export declare const DEMO_REALTIME_VERSION = 1;
export interface DemoRealtimeHour {
    hour: number;
    today: number | null;
    sameDayLastWeek: number;
}
export interface DemoRealtimeReading {
    asset: string;
    status: 'success';
    observedAt: string;
    activeUsers5m: number;
    activeUsers30m: number;
    activeUsersByMinute: number[];
    hourlyActiveUsers: DemoRealtimeHour[];
    timeZone: 'UTC';
    hourlyObservedAt: string;
    hourlyErrorCode: null;
    quota: null;
    errorCode: null;
}
export interface DemoRealtimePayload {
    generatedAt: string;
    assets: DemoRealtimeReading[];
}
/** Live readings for every demo site with traffic, from the validated scenario. */
export declare function createDemoRealtime(input: DemoScenario): {
    read(nowMs: number): DemoRealtimePayload;
};
