// Generated by pnpm config:generate. Edit the sibling .mts source.
export declare const SCENARIO_VERSION = 4;
export interface DemoAsset {
    id: string;
    name: string;
    prefix: string;
    days: number;
    sessions: number | null;
    revenue: number | null;
    revenueFamily: 'subs' | 'licensing' | null;
    cost: number;
    event: string | null;
    isOs?: boolean;
    /** Ad income per 1,000 sessions, in cents, before season and weekday; only an ad-supported site has one. */
    adRpm?: number;
}
export interface DemoSite extends DemoAsset {
    createdAt: string;
    domain: string | null;
    status: string;
}
export interface DemoDay {
    asset: string;
    date: string;
    sessions: number;
    age: number;
    pageViews: number;
    activeUsers: number;
    events: number;
    eventCount: number;
    clicks: number;
    impressions: number;
    ctr: number;
    position: number;
    reportMissing: boolean;
    provisional: boolean;
}
export interface DemoLedger {
    key: string;
    currency: string;
    note: string;
    asset: string;
    period: string;
    kind: 'revenue' | 'cost';
    family: string;
    minor: number;
    state: 'estimated' | 'reconciled';
    source: string;
    recordedAt: string;
    coverageStart?: string;
    coverageEnd?: string;
    coverageComplete?: boolean;
    supersedes?: string;
}
/** One synthetic daily ad-network estimate, recorded once that day is reported. */
export interface DemoAdDay {
    asset: string;
    siteId: string;
    date: string;
    minor: number;
    recordedAt: string;
}
export interface DemoPulse {
    asset: string;
    date: string;
    generatedAt: string;
    capabilities: string[];
    metrics: Record<string, {
        last24h: number;
        avg7d: number;
        total: number;
    }>;
}
export interface DemoInput {
    seed: string;
    cutoff: string;
    release: string;
    timeZone?: string;
}
export declare const DEMO_ASSETS: readonly DemoAsset[];
export declare function shiftDemoDay(day: string, offset: number): string;
export declare function shiftDemoMonth(period: string, offset: number): string;
/** Each site's demand by weekday, Sunday first: software is used on workdays,
 * recipes are cooked at weekends. The simulator continues the same shape. */
export declare function demoWeekShape(prefix: string): readonly number[];
/** How a visit turns into pages, users, tracked actions and search results.
 * A recipe site: more pages a visit, more of it from search, higher in results. */
export declare function demoTrafficShape(prefix: string): {
    pages: number;
    pagesSpread: number;
    activeUsers: number;
    events: number;
    clicks: number;
    impressionsPerClick: number;
    position: number;
    positionSpread: number;
};
/** A recipe site's year peaks in late November (day 328) and is quietest in
 * early summer: demand is `1 + DEMO_RECIPE_SEASON × cos(angle)`. */
export declare const DEMO_RECIPE_SEASON = 0.22;
export declare function demoRecipeSeasonAngle(date: string): number;
/** The ad network's site identity for a fictional ad-supported site. */
export declare function demoAdSiteId(asset: Pick<DemoAsset, 'prefix'>): string;
/** One day's synthetic ad estimate in cents. Ad income follows visits; the
 * subscription and licensing income above never does. */
export declare function demoAdRevenueMinor(seed: string, asset: Pick<DemoAsset, 'id' | 'adRpm'>, date: string, sessions: number): number;
/** A month of ad estimates is paid on the sixth of the second month after it,
 * close to but rarely exactly the estimates' sum. */
export declare function demoAdPayment(seed: string, asset: Pick<DemoAsset, 'id'>, month: string, dailyMinor: readonly number[]): {
    minor: number;
    paidOn: string;
};
/** The last day an ad network has reported by `instant`: yesterday once the
 * morning report is in (14:10 UTC is after it in every season), otherwise the
 * day before. */
export declare function demoAdReportedThrough(instant: string): string;
/** All identities, times, traffic and money originate in this manifest. */
export declare function generateDemoScenario({ seed, cutoff, release, timeZone }: DemoInput): {
    manifest: {
        synthetic: boolean;
        scenarioVersion: number;
        seed: string;
        cutoff: string;
        release: string;
        timeZone: string;
        providerTimeZone: string;
        referenceDate: string;
        referencePeriod: string;
        workspaceId: `${string}-${string}-${string}-${string}-${string}`;
        identities: {
            id: string;
            prefix: string;
            name: string;
            createdAt: string;
        }[];
        taskProjects: {
            asset: string;
            prefix: string;
            database: string;
        }[];
        adSites: {
            asset: string;
            siteId: string;
        }[];
        stories: {
            repair: {
                asset: string;
                findingDate: string;
                ref: string;
                readbackTaskId: string;
                annotationAt: string;
                registeredAt: string;
                baselineStart: string;
                baselineEnd: string;
                checkAt: string;
                watchId: string;
            };
            problem: {
                asset: string;
                ref: string;
                date: string;
                metric: string | null;
            };
        };
    };
    assets: {
        id: string;
        createdAt: string;
        domain: string | null;
        status: string;
        name: string;
        prefix: string;
        days: number;
        sessions: number | null;
        revenue: number | null;
        revenueFamily: "subs" | "licensing" | null;
        cost: number;
        event: string | null;
        isOs?: boolean;
        /** Ad income per 1,000 sessions, in cents, before season and weekday; only an ad-supported site has one. */
        adRpm?: number;
    }[];
    daily: DemoDay[];
    ledger: DemoLedger[];
    adRevenue: DemoAdDay[];
    pulses: DemoPulse[];
    tasks: import("./demo-task-facts.mjs").DemoTaskFact[];
};
export declare function demoScenarioHash(scenario: DemoScenario): string;
export type DemoScenario = ReturnType<typeof generateDemoScenario>;
