// Generated by pnpm config:generate. Edit the sibling .mts source.
export declare const DEMO_VISIT_TTL_MS: number;
export declare const DEMO_LAUNCH_MAX_MS: number;
export declare const DEMO_GENERATION_MAX_MS: number;
export declare const DEMO_REQUEST_MAX_MS: number;
export declare const DEMO_CLEANUP_MAX_MS: number;
export declare const DEMO_MAX_VISITS = 1024;
export declare const DEMO_MAX_VISIT_REQUESTS = 8;
export declare class DemoVisitRefusal extends Error {
    readonly status: number;
    readonly code: string;
    constructor(status: number, code: string);
}
export interface DemoVisit {
    readonly id: string;
    readonly generation: string;
    readonly issuedAt: number;
    readonly expiresAt: number;
}
export interface DemoVisitRequest {
    readonly visit: Readonly<DemoVisit>;
    readonly path: string;
    readonly release: () => void;
}
/** Only the dedicated gateway issues visits. Polls, navigation and refresh
 * resolve the original visit instead of touching its recorded deadline. */
export declare class DemoVisits {
    private readonly newId;
    private readonly visits;
    private readonly requests;
    private current;
    private previous;
    readonly deadline: number;
    constructor(current: string, startedAt: number, durationMs: number, newId: () => string);
    state(): Readonly<{
        current: string;
        previous: Readonly<{
            generation: string;
            retireAt: number;
        }> | null;
        deadline: number;
    }>;
    begin(now: number): Readonly<DemoVisit>;
    resolve(requestPath: string, now: number): DemoVisitRequest;
    /** Called once, only after the caller has qualified and durably published
     * the exact complete candidate. No third backend is adopted or queued. */
    publish(generation: string, now: number): void;
    retired(generation: string, now: number): void;
    private live;
}
