// Generated by pnpm generate. Edit the sibling .mts source.
import type { WorkflowRun } from '../packages/contract/src/workflows.js';
import { type DemoScenario } from './demo-scenario.mjs';
export interface DemoTaskRunEvidence {
    synthetic: boolean;
    scenarioHash: string;
    workspaceId: string;
    release: string;
    projects: readonly {
        asset: string;
    }[];
    tasks: number;
    snapshots: number;
}
export interface DemoWatchRunEvidence {
    evaluatedAt: string;
    result: {
        readings: number;
        closed: readonly {
            id: string;
            outcome: string;
        }[];
        failed: readonly unknown[];
    };
    reading: {
        outcome: string;
        checked_at: string;
        baseline: string;
        post: string;
    };
}
export interface DemoJobRunInput {
    job: string;
    startedAt: string;
    ms: number;
    outcome: 'ran' | 'failed';
    detail: string;
}
export interface DemoJobRecord {
    job: string;
    at: string;
    ms: number;
    outcome: 'ran' | 'failed';
    detail: string;
}
/** Values come from the scenario and completed seed receipts, not provider calls. */
export declare function generateDemoWorkflows({ scenario, watch, tasks }: {
    scenario: DemoScenario;
    watch: DemoWatchRunEvidence;
    tasks: DemoTaskRunEvidence;
}): {
    version: 1;
    synthetic: true;
    scenarioHash: string;
    workspaceId: `${string}-${string}-${string}-${string}-${string}`;
    release: string;
    cutoff: string;
    records: DemoJobRecord[];
    traces: WorkflowRun[];
    runs: DemoJobRunInput[];
    links: {
        collectionFailure: string;
        collectionRecovery: string;
        outcomeCheck: string;
        taskRefresh: string;
    };
};
export type DemoWorkflowHistory = ReturnType<typeof generateDemoWorkflows>;
/** Caller supplies only the unchanged job-run writer bound to its owned STORE. */
export declare function writeDemoWorkflowHistory({ home, history, writeRuns }: {
    home: string;
    history: DemoWorkflowHistory;
    writeRuns: (input: {
        runs: DemoJobRunInput[];
    }, nowMs: number) => Promise<{
        ok: boolean;
        created?: number;
        duplicate?: number;
        stale?: number;
        pruned?: number;
    }>;
}): Promise<{
    version: number;
    synthetic: boolean;
    scenarioHash: string;
    files: Record<string, string>;
    mirror: {
        ok: boolean;
        created?: number;
        duplicate?: number;
        stale?: number;
        pruned?: number;
    };
    links: {
        collectionFailure: string;
        collectionRecovery: string;
        outcomeCheck: string;
        taskRefresh: string;
    };
}>;
