// Generated by pnpm config:generate. Edit the sibling .mts source.
import { demoIntegrationAssets, generateDemoDisplay } from './demo-display.mjs';
import { type DoltProfile } from './dolt-profile.mjs';
import { type DemoViewerDescriptor } from './demo-viewer-policy.mjs';
export interface DemoViewerInstallation {
    readonly home: string;
    readonly viewer: Readonly<DemoViewerDescriptor>;
    readonly tree: string;
    readonly postgresProject: string;
    readonly postgresPort: number;
    /** The application address stays in private custody, never a receipt or argv. */
    readonly databaseFile: string;
    readonly dolt: Readonly<DoltProfile>;
    readonly projects: readonly Readonly<{
        asset: string;
        prefix: string;
        database: string;
        repo: string;
    }>[];
    readonly assetIds: readonly string[];
    readonly client: Readonly<{
        version: string;
        sha256: string;
    }>;
    readonly display: ReturnType<typeof generateDemoDisplay>;
    readonly integrations: ReturnType<typeof demoIntegrationAssets>;
}
/** File validation only. The launcher must separately prove exact resource and
 * read-only store identity before it starts a viewer. No defaults are accepted. */
export declare function readDemoViewerInstallation({ root, home, release, tree, now }: {
    root: string;
    home: string;
    release: string;
    tree: string;
    now?: number;
}): Readonly<DemoViewerInstallation>;
export interface DemoViewerLaunch {
    readonly installation: Readonly<DemoViewerInstallation>;
    readonly runtime: string;
    readonly towerPort: number;
    readonly doorPort: number;
}
/** The Vite configuration accepts only a launch declaration that still matches
 * completed custody and every local runtime binding. Ordinary installs do no IO. */
export declare function readDemoViewerLaunch(root: string, env?: Readonly<Record<string, string | undefined>>): Readonly<DemoViewerLaunch> | null;
