#!/usr/bin/env node
// dev-secrets.mjs — readable local secret source → Wrangler's dotenv input.
//
// Cloudflare Workers receive secrets as string bindings. That is appropriate at
// runtime, but it makes nested local maps painful to maintain when they are
// hand-minified inside `.dev.vars`. The operator instead edits the gitignored,
// formatted `workers/ingest/.dev.secrets.json`; `os:up` compiles it to the
// `.dev.vars` file Wrangler expects before starting the Worker.
//
// Service-account payloads are larger than the small routing map around them.
// The readable source keeps each account together, while sync extracts every
// encoded key into its own generated Worker binding. This prevents a
// multi-account GOOGLE_SIGNAL_ACCOUNTS value from crossing Cloudflare's
// per-binding size ceiling.
//
// Since the credential store landed (epic `ro-vu8d`), these local files are the
// LEGACY path: a credential entered on the Tower's Integrations page lives
// encrypted in D1 and wins over any binding here. `import` is the one-way door
// between them — it reads the same `.dev.secrets.json` and PUTs each provider
// through the running Tower once, so the operator's existing secrets move
// without being retyped into a form.
//
// That door is ALSO a button: the Legacy env explainer on an Integrations card
// posts to a local dev-server lane which calls `importDevSecrets` below, in
// process (bead `ro-vu8d.7`). One function, so pressing the button and pasting
// the command cannot come to different conclusions.
//
//   pnpm dev:secrets:migrate  # one-time .dev.vars → formatted JSON
//   pnpm dev:secrets:sync     # rebuild generated .dev.vars
//   pnpm dev:secrets:import   # .dev.secrets.json → the credential store

import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { readProductEnv } from './product-env.mjs';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(__dirname, '..');
// The secrets belong to the installation's HOME, not to wherever this code is:
// `NOTICEOS_HOME` (scripts/os-runtime.mjs HOME_ENV, read the same way as
// apps/tower/vite/lane.ts) names it for the managed service's runtime copy and
// for `pnpm start`'s own folder, so a lane in either never reads another
// installation's bearer. Unset, home is this checkout, as it always was.
const NAMED_HOME = readProductEnv(process.env, 'home');
const HOME_ROOT = NAMED_HOME ? path.resolve(NAMED_HOME) : REPO_ROOT;
export const DEFAULT_DEV_VARS = path.join(HOME_ROOT, 'workers', 'ingest', '.dev.vars');
export const DEFAULT_DEV_SECRETS = path.join(
  HOME_ROOT,
  'workers',
  'ingest',
  '.dev.secrets.json',
);

const KEY_RE = /^[A-Z][A-Z0-9_]*$/;

/**
 * The fourth bootstrap secret (docs/06-operations.md, bead ro-ujb9.76.7.2): the
 * application login's connection string to the installation's Postgres. It is
 * kept in this file beside the other three, and read from it by the runner and
 * `pnpm start` (scripts/database-address.mts), which hand it to the dev server
 * in its environment only, as the POSTGRES binding's local address. It is never
 * a Worker binding, so it is never compiled into `.dev.vars`: a Worker reaches
 * Postgres through its Hyperdrive binding alone.
 */
export const DATABASE_URL = 'DATABASE_URL';
const NOT_WORKER_BINDINGS = new Set([DATABASE_URL]);
const GOOGLE_SIGNAL_ACCOUNTS = 'GOOGLE_SIGNAL_ACCOUNTS';
const GOOGLE_SERVICE_ACCOUNT_PREFIX = 'GOOGLE_SERVICE_ACCOUNT_';
const GENERATED_HEADER = [
  '# GENERATED from .dev.secrets.json by scripts/dev-secrets.mjs.',
  '# Edit .dev.secrets.json, then restart `pnpm os:up` (or run `pnpm dev:secrets:sync`).',
  '# Do not edit this file by hand; both files are gitignored.',
  '',
].join('\n');

function isPlainObject(value) {
  return value !== null && typeof value === 'object' && !Array.isArray(value);
}

/** Convert the readable JSON representation to Worker string bindings. */
export function normalizeSecretBindings(document) {
  if (!isPlainObject(document)) {
    throw new Error('.dev.secrets.json must contain one top-level JSON object');
  }

  const bindings = {};
  for (const [key, value] of Object.entries(document)) {
    if (!KEY_RE.test(key)) {
      throw new Error(`invalid secret binding name ${JSON.stringify(key)}`);
    }
    if (typeof value === 'string') {
      bindings[key] = value;
      continue;
    }
    if (value === null || typeof value !== 'object') {
      throw new Error(
        `${key} must be a string, object, or array (received ${value === null ? 'null' : typeof value})`,
      );
    }
    bindings[key] = JSON.stringify(value);
  }
  return bindings;
}

function googleServiceAccountBinding(account) {
  const suffix = account
    .trim()
    .toUpperCase()
    .replace(/[^A-Z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '');
  if (!suffix) {
    throw new Error('Google service-account labels must contain a letter or number');
  }
  return `${GOOGLE_SERVICE_ACCOUNT_PREFIX}${suffix}`;
}

/**
 * Compile the readable local document into bounded Worker bindings.
 *
 * `.dev.secrets.json` deliberately keeps service_account_b64 beside the
 * properties it supports. At runtime the routing map carries only a safe
 * `service_account_binding` pointer and each encoded key occupies one secret.
 */
export function compileWorkerBindings(document) {
  const bindings = normalizeSecretBindings(document);
  for (const name of NOT_WORKER_BINDINGS) delete bindings[name];
  const accounts = document[GOOGLE_SIGNAL_ACCOUNTS];
  if (!isPlainObject(accounts)) return bindings;

  const routedAccounts = {};
  const generatedNames = new Set();
  const generatedBindings = {};
  for (const [account, value] of Object.entries(accounts)) {
    if (!isPlainObject(value) || typeof value.service_account_b64 !== 'string') {
      routedAccounts[account] = value;
      continue;
    }

    const binding = googleServiceAccountBinding(account);
    if (generatedNames.has(binding)) {
      throw new Error(
        `Google service-account labels collide after binding normalization: ${binding}`,
      );
    }
    if (Object.hasOwn(document, binding)) {
      throw new Error(`${binding} is generated from GOOGLE_SIGNAL_ACCOUNTS; remove the top-level key`);
    }
    generatedNames.add(binding);
    const { service_account_b64: encoded, ...routing } = value;
    routedAccounts[account] = {
      ...routing,
      service_account_binding: binding,
    };
    generatedBindings[binding] = encoded;
  }

  return {
    ...bindings,
    [GOOGLE_SIGNAL_ACCOUNTS]: JSON.stringify(routedAccounts),
    ...generatedBindings,
  };
}

/** Parse the dotenv subset Wrangler uses for `.dev.vars`. */
export function parseDevVars(text) {
  const bindings = {};
  const linePattern =
    /(?:^|^)\s*(?:export\s+)?([\w.-]+)(?:\s*=\s*?|:\s+?)(\s*'(?:\\'|[^'])*'|\s*"(?:\\"|[^"])*"|\s*`(?:\\`|[^`])*`|[^#\r\n]+)?\s*(?:#.*)?(?:$|$)/gm;
  const normalized = text.replace(/\r\n?/g, '\n');
  let match;
  while ((match = linePattern.exec(normalized)) !== null) {
    const key = match[1];
    if (!KEY_RE.test(key)) continue;
    let value = (match[2] || '').trim();
    const quote = value[0];
    value = value.replace(/^(['"`])([\s\S]*)\1$/gm, '$2');
    if (quote === '"') {
      value = value.replace(/\\n/g, '\n').replace(/\\r/g, '\r');
    }
    bindings[key] = value;
  }
  return bindings;
}

/** Lift JSON-looking map values back into nested values for the readable file. */
export function structureLegacyBindings(bindings) {
  const document = {};
  for (const [key, value] of Object.entries(bindings)) {
    const trimmed = value.trim();
    if (
      (trimmed.startsWith('{') && trimmed.endsWith('}')) ||
      (trimmed.startsWith('[') && trimmed.endsWith(']'))
    ) {
      try {
        document[key] = JSON.parse(trimmed);
        continue;
      } catch {
        // Keep malformed JSON as a string. The consuming lane will report the
        // precise config error instead of migration silently changing it.
      }
    }
    document[key] = value;
  }
  return document;
}

function encodeDevVar(value, key) {
  if (!value.includes("'")) return `'${value}'`;
  if (!value.includes('`')) return `\`${value}\``;
  throw new Error(
    `${key} contains both single quotes and backticks; cannot encode it losslessly in .dev.vars`,
  );
}

function encodeDevVars(bindings) {
  return (
    GENERATED_HEADER +
    Object.entries(bindings)
      .map(([key, value]) => `${key}=${encodeDevVar(value, key)}`)
      .join('\n') +
    '\n'
  );
}

async function atomicSecretWrite(file, contents) {
  const tmp = `${file}.tmp-${process.pid}`;
  await fs.writeFile(tmp, contents, { encoding: 'utf8', mode: 0o600 });
  await fs.chmod(tmp, 0o600);
  await fs.rename(tmp, file);
  await fs.chmod(file, 0o600);
}

export async function readDevSecretBindings({
  secretsFile = DEFAULT_DEV_SECRETS,
  varsFile = DEFAULT_DEV_VARS,
} = {}) {
  try {
    const raw = await fs.readFile(secretsFile, 'utf8');
    return {
      bindings: normalizeSecretBindings(JSON.parse(raw)),
      sourceFile: secretsFile,
      structured: true,
    };
  } catch (error) {
    if (error?.code !== 'ENOENT') {
      throw new Error(`could not read ${secretsFile}: ${error.message}`);
    }
  }

  try {
    return {
      bindings: parseDevVars(await fs.readFile(varsFile, 'utf8')),
      sourceFile: varsFile,
      structured: false,
    };
  } catch (error) {
    throw new Error(`could not read ${varsFile}: ${error.message}`);
  }
}

export async function syncDevVars({
  secretsFile = DEFAULT_DEV_SECRETS,
  varsFile = DEFAULT_DEV_VARS,
} = {}) {
  const raw = await fs.readFile(secretsFile, 'utf8');
  const bindings = compileWorkerBindings(JSON.parse(raw));
  await atomicSecretWrite(varsFile, encodeDevVars(bindings));
  return { keys: Object.keys(bindings), secretsFile, varsFile };
}

export async function syncDevVarsIfPresent(options = {}) {
  try {
    await fs.access(options.secretsFile ?? DEFAULT_DEV_SECRETS);
  } catch (error) {
    if (error?.code === 'ENOENT') return null;
    throw error;
  }
  return syncDevVars(options);
}

export async function migrateDevVars({
  secretsFile = DEFAULT_DEV_SECRETS,
  varsFile = DEFAULT_DEV_VARS,
} = {}) {
  try {
    await fs.access(secretsFile);
    throw new Error(`${secretsFile} already exists; refusing to overwrite it`);
  } catch (error) {
    if (error?.code !== 'ENOENT') throw error;
  }

  const bindings = parseDevVars(await fs.readFile(varsFile, 'utf8'));
  const document = structureLegacyBindings(bindings);
  await atomicSecretWrite(secretsFile, JSON.stringify(document, null, 2) + '\n');
  await syncDevVars({ secretsFile, varsFile });
  return { keys: Object.keys(bindings), secretsFile, varsFile };
}

/** Where a local `pnpm os:up` serves the Tower (scripts/runner/config.mjs CONFIG). */
export const DEFAULT_TOWER_ORIGIN = 'http://127.0.0.1:5173';

/** The OS's answer to "what is connected". Written once: the import below and
 * `creds:check` both ask it, and two spellings of one path would be two ways to
 * be wrong about whether the OS is running. */
export const INTEGRATION_PROVIDERS_PATH = '/api/integrations/providers';

/**
 * Ask the running Tower what it holds — the provider catalog straight out of
 * `packages/contract`, plus each provider's connection state.
 *
 * THROWS when the OS is not running, and says so: every caller has to decide
 * what that means for it (the import stops; the checker falls back to reading
 * the env bindings and says it did).
 */
export async function fetchIntegrationProviders({
  origin = DEFAULT_TOWER_ORIGIN,
  fetchImpl = fetch,
} = {}) {
  const url = `${origin}${INTEGRATION_PROVIDERS_PATH}`;
  const listed = await fetchImpl(url, { headers: { accept: 'application/json' } });
  if (!listed.ok) {
    throw new Error(`GET ${url} answered ${listed.status} — is \`pnpm os:up\` running?`);
  }
  return listed.json();
}

/**
 * Which providers can be imported from these bindings, and with which fields.
 *
 * The provider catalog is NOT duplicated here — it is read from the running
 * Tower (`GET /api/integrations/providers`), which serves
 * `INTEGRATION_PROVIDERS` straight out of `packages/contract`. One declaration,
 * and a provider added there is importable the same day with no edit to this
 * file.
 *
 * A provider missing a required binding is SKIPPED with its reason rather than
 * half-imported: an incomplete credential in the store would shadow a complete
 * one in the env, which is the one outcome worse than not importing at all.
 */
/**
 * What is still missing before this provider could be stored — the SAME rule as
 * `credentialAuthState` in `packages/contract`.
 *
 * Mirrored rather than imported because that package ships TypeScript with no
 * build output, and this is a Node script. The DATA is still single-sourced:
 * `authPaths` and `required` arrive on the wire from
 * `GET /api/integrations/providers`, which serves the contract's own catalog.
 * What is duplicated is eight lines of predicate, and the contract's own test
 * pins the behaviour both copies have to agree on.
 *
 * Google is why this exists: it declares two ways in and marks NEITHER field
 * required, because "required" cannot express *either a sign-in or a service
 * account*. Reading only `required` would call an empty Google credential
 * complete and PUT a row with no fields — which would then shadow a working env
 * binding, the one outcome worse than not importing at all.
 */
function providerShortfall(provider, held) {
  const paths = provider.authPaths ?? [];
  if (paths.length === 0) {
    const required = (provider.fields ?? []).filter((field) => field.required);
    const missing = required
      .filter((field) => !held.includes(field.name))
      .map((field) => field.name);
    return required.length === 0 ? ['(nothing to import)'] : missing;
  }
  let closest = null;
  for (const path of paths) {
    const missing = (path.fields ?? []).filter((name) => !held.includes(name));
    if (missing.length === 0) return [];
    if (closest === null || missing.length < closest.length) closest = missing;
  }
  return closest ?? [];
}

/**
 * One field's value out of these bindings, with a legacy single-asset binding
 * folded into the asset map it belongs to (bead `ro-vu8d.24`).
 *
 * Mirrored from `readEnvCredential` in `packages/contract` for the reason
 * `providerShortfall` is: that package ships TypeScript and this is Node. The
 * DECLARATION is single-sourced — `legacyAssetBinding` arrives on the wire from
 * `GET /api/integrations/providers` — so what is duplicated is the fold, not the
 * fact that Clarity has one. The map WINS wherever both name the asset, and a
 * map that does not parse is left exactly as it is so the route's own refusal is
 * what the operator sees.
 *
 * WHICH ASSET is the route's answer too (bead `ro-ujb9.118`): it fills
 * `legacyAssetBinding.asset` from the installation's own register
 * (`legacyBindingAsset`). No answer, no fold — never a guessed site.
 */
function fieldValue(field, bindings) {
  const direct = bindings[field.name];
  let value = typeof direct === 'string' && direct.trim() !== '' ? direct : undefined;
  const legacy = field.legacyAssetBinding;
  if (!legacy || field.kind !== 'asset-map') return value;
  if (typeof legacy.asset !== 'string' || legacy.asset === '') return value;
  const raw = bindings[legacy.name];
  const token = typeof raw === 'string' ? raw.trim() : '';
  if (token === '') return value;
  if (value === undefined) return JSON.stringify({ [legacy.asset]: token });
  let parsed;
  try {
    parsed = JSON.parse(value);
  } catch {
    return value;
  }
  if (parsed === null || typeof parsed !== 'object' || Array.isArray(parsed)) return value;
  const held = parsed[legacy.asset];
  if (typeof held === 'string' && held.trim() !== '') return value;
  return JSON.stringify({ ...parsed, [legacy.asset]: token });
}

export function credentialImportPlan(bindings, providers) {
  const planned = [];
  const skipped = [];
  for (const entry of providers) {
    const provider = entry.provider ?? entry;
    const fields = {};
    for (const field of provider.fields ?? []) {
      const value = fieldValue(field, bindings);
      if (value !== undefined) fields[field.name] = value;
    }
    const missing = providerShortfall(provider, Object.keys(fields));
    if (missing.length > 0) {
      skipped.push({ provider: provider.id, missing });
      continue;
    }
    // The VALUES ride in `fields` and are never logged; only the names are.
    planned.push({ provider: provider.id, fields, names: Object.keys(fields) });
  }
  return { planned, skipped };
}

/**
 * PUT each planned credential through the Tower's same-origin route.
 *
 * One request per provider, and the outcome is reported by NAME — a failure
 * says which provider and what the route answered, never what was sent.
 */
export async function runCredentialImport({
  bindings,
  origin = DEFAULT_TOWER_ORIGIN,
  fetchImpl = fetch,
} = {}) {
  const payload = await fetchIntegrationProviders({ origin, fetchImpl });
  if (payload.keyPresent === false) {
    throw new Error(payload.keyReason ?? 'CREDENTIALS_KEY is not set.');
  }

  const { planned, skipped } = credentialImportPlan(bindings, payload.providers ?? []);
  const imported = [];
  const failed = [];
  for (const entry of planned) {
    const response = await fetchImpl(
      `${origin}/api/integrations/${encodeURIComponent(entry.provider)}/credential`,
      {
        method: 'PUT',
        headers: { 'content-type': 'application/json', origin },
        body: JSON.stringify({ fields: entry.fields }),
      },
    );
    if (response.status === 204) {
      imported.push({ provider: entry.provider, names: entry.names });
      continue;
    }
    let detail = `HTTP ${response.status}`;
    try {
      const body = await response.json();
      detail = body.detail ?? body.error ?? detail;
    } catch {
      // A non-JSON refusal is still a refusal; the status is the whole message.
    }
    failed.push({ provider: entry.provider, detail });
  }
  return { imported, skipped, failed };
}

/**
 * The WHOLE of `pnpm dev:secrets:import`, minus the printing.
 *
 * Extracted so the Tower's Import button runs this exact code rather than a
 * second implementation of it — and runs it in-process, never by shelling out
 * to `pnpm`: a web request that spawns a package manager is a different and
 * much larger thing to guard than a web request that reads one file.
 *
 * `secretsFile` is a parameter and not a default read of `DEFAULT_DEV_SECRETS`
 * because the Vite lane BUNDLES this module before executing it, so the repo
 * root derived here from `import.meta.url` is a fact about that bundler's temp
 * directory rather than about the checkout. The lane walks up to the real root
 * (vite/lane.ts `findRepoRoot`) and passes the path it found.
 */
export async function importDevSecrets({
  secretsFile = DEFAULT_DEV_SECRETS,
  origin = DEFAULT_TOWER_ORIGIN,
  fetchImpl = fetch,
} = {}) {
  const raw = await fs.readFile(secretsFile, 'utf8');
  const bindings = normalizeSecretBindings(JSON.parse(raw));
  return runCredentialImport({ bindings, origin, fetchImpl });
}

function relative(file) {
  return path.relative(REPO_ROOT, file);
}

async function importCommand() {
  const originArg = process.argv.indexOf('--origin');
  const origin = originArg > 0 ? process.argv[originArg + 1] : DEFAULT_TOWER_ORIGIN;
  const { imported, skipped, failed } = await importDevSecrets({ origin });

  for (const entry of imported) {
    process.stdout.write(`imported ${entry.provider} (${entry.names.join(', ')})\n`);
  }
  for (const entry of skipped) {
    process.stdout.write(
      `skipped  ${entry.provider} — ${entry.missing.join(', ')} not in ${relative(DEFAULT_DEV_SECRETS)}\n`,
    );
  }
  for (const entry of failed) {
    process.stderr.write(`failed   ${entry.provider} — ${entry.detail}\n`);
  }
  process.stdout.write(
    `\n${imported.length} imported, ${skipped.length} skipped, ${failed.length} failed` +
      ` (origin ${origin}).\nThe store now wins over the bindings in ` +
      `${relative(DEFAULT_DEV_VARS)}; they stay as the fallback.\n`,
  );
  if (failed.length > 0) process.exitCode = 1;
}

async function main() {
  const command = process.argv[2];
  if (command === 'import') return importCommand();
  if (command !== 'migrate' && command !== 'sync') {
    process.stderr.write(
      'usage: node scripts/dev-secrets.mjs <migrate|sync|import>\n' +
        '  migrate  one-time .dev.vars → formatted .dev.secrets.json\n' +
        '  sync     compile .dev.secrets.json → generated .dev.vars\n' +
        '  import   PUT each provider in .dev.secrets.json into the credential\n' +
        '           store through a running Tower (--origin, default ' +
        DEFAULT_TOWER_ORIGIN +
        ')\n',
    );
    process.exitCode = 2;
    return;
  }

  const result = command === 'migrate' ? await migrateDevVars() : await syncDevVars();
  process.stdout.write(
    `${command === 'migrate' ? 'Migrated' : 'Synced'} ${result.keys.length} secret binding` +
      `${result.keys.length === 1 ? '' : 's'} (${result.keys.join(', ')})\n` +
      `  source: ${relative(result.secretsFile)}\n` +
      `  wrangler input: ${relative(result.varsFile)}\n`,
  );
}

if (path.resolve(process.argv[1] ?? '') === fileURLToPath(import.meta.url)) {
  main().catch((error) => {
    process.stderr.write(`dev secrets failed: ${error.message}\n`);
    process.exitCode = 1;
  });
}
