// Generated by pnpm generate. Edit the sibling .mts source.
import { type IncomingMessage } from 'node:http';
import { type HostedTaskRuntimeAdapters, type HostedTaskRuntimeOptions } from './hosted-task-runtime.mjs';
import { type HostedDemoRuntimeOptions } from './hosted-demo-runtime.mjs';
export interface HostedDemoServerOptions {
    readonly version: 1;
    readonly publicOrigin: string;
    /** An unpublished Docker-network or loopback listener, never inferred from headers. */
    readonly listen: {
        readonly host: '127.0.0.1' | '0.0.0.0';
        readonly port: number;
    };
    readonly artifactRoot: string;
    readonly workerStateRoot: string;
    readonly workspaceDatabaseUrl: string;
    readonly tasks: HostedTaskRuntimeOptions;
    readonly activity: HostedDemoRuntimeOptions;
}
export interface DemoWorkerArtifact {
    readonly main: string;
    readonly modulesRoot: string;
    readonly compatibilityDate: string;
    readonly compatibilityFlags: readonly string[];
}
export interface DemoArtifactManifest {
    readonly version: 1;
    readonly release: string;
    readonly client: 'client';
    readonly tower: DemoWorkerArtifact;
    readonly ingest: DemoWorkerArtifact;
    readonly files: Readonly<Record<string, string>>;
    readonly publicFiles: readonly string[];
}
interface Runtime {
    handle(request: Request): Promise<Response>;
    close(): Promise<void>;
}
interface Activity {
    status(): {
        running: boolean;
        error: string | null;
    };
    close(): Promise<void>;
}
interface Workers {
    getWorker(name: string): Promise<{
        fetch(request: Request): Promise<Response>;
    }>;
    dispatchFetch(url: string, init: {
        method: string;
        headers: Record<string, string>;
        body?: ArrayBuffer;
        signal: AbortSignal;
    }): Promise<Response>;
    dispose(): Promise<void>;
}
/** Trusted in-process test composition only. Never read from JSON or env. */
export interface HostedDemoServerAdapters {
    openTasks(options: HostedTaskRuntimeOptions, adapters?: HostedTaskRuntimeAdapters): Promise<Runtime>;
    startActivity(options: HostedDemoRuntimeOptions): Promise<Activity>;
    openWorkers(options: Record<string, unknown>): Workers;
}
/** Read a bounded private file without following links or exposing its values. */
export declare function readHostedDemoRuntimeFile(filename: string): HostedDemoServerOptions;
export declare function captureHostedDemoServerOptions(input: HostedDemoServerOptions): HostedDemoServerOptions;
/** The same file inventory is checked before any pool, timer or listener. */
export declare function readDemoArtifact(rootInput: string): DemoArtifactManifest;
/** The demo page's head names absolute URLs (canonical, social preview) by
 * this placeholder (apps/tower/vite/demo-head.html). It is filled from the
 * configured public origin after the artifact's hash is verified. */
export declare const PUBLIC_ORIGIN_PLACEHOLDER = "__NOTICEOS_PUBLIC_ORIGIN__";
export declare function publicPage(bytes: Uint8Array, origin: string, tail?: string): string;
/** The operator's Statcounter project for the demo's pages, from their
 * private env file as `project:security` (deploy/demo/README.md). Product
 * code names no account, so another operator's demo counts nothing until
 * they set their own. The app changes views without loading a page, so
 * each path change also records a page view. */
export declare function statcounterTag(value: string | undefined): string;
/** Request URL is reconstructed from configured public authority, never a
 * forwarded header. The listener must remain behind the declared TLS edge. */
export declare function demoRequestTarget(origin: string, incoming: IncomingMessage): URL;
export declare function startHostedDemoServer(input: HostedDemoServerOptions, adapters?: HostedDemoServerAdapters, presentation?: {
    readonly statcounter?: string;
}): Promise<{
    readonly publicOrigin: string;
    close(): Promise<void>;
}>;
export {};
