// Generated by pnpm generate. Edit the sibling .mts source.
/** The journal identity of a server registry. Callers validate their registry
 * before using this pure serialization; callbacks never enter its digest. */
export declare function hostedJobDefinitionHash(version: string, steps: readonly {
    readonly key: string;
    readonly kind: 'database' | 'effect';
    readonly action: string;
}[]): string;
