// Generated by pnpm generate. Edit the sibling .mts source.
import type { HostedTaskOperations } from './hosted-task-operations.mjs';
export declare const MCP_PATH = "/api/mcp";
/** Marks this endpoint's own forwarded call to the Worker's read-model tools,
 * so a front door passes it through rather than answering it again. Routing
 * only: the Worker admits the forwarded call like any other. */
export declare const READ_MODELS_HEADER = "x-noticeos-mcp-part";
export interface HostedMcpWorkspace {
    readonly workspaceId: string;
    readonly displayName: string;
    readonly role: 'owner' | 'operator' | 'viewer';
    readonly status: 'active' | 'provisioning' | 'suspended';
}
export interface HostedMcpOptions {
    readonly profile: 'hosted' | 'demo';
    readonly trustedOrigin: string;
    readonly demoWorkspaceId?: string;
    readonly operations: HostedTaskOperations;
    /** Hosted only, and required there: the request's verified token, and its
     * person's workspaces. Admission verifies again, per workspace, per call. */
    readonly agents?: {
        verify(request: Request): Promise<{
            readonly scopes: readonly string[];
        } | null>;
        workspaces(request: Request): Promise<readonly HostedMcpWorkspace[] | null>;
    };
    /** Sends one read-model MCP call to the Tower Worker. Without it, only the
     * task tools are offered. */
    readonly readModels?: (request: Request) => Promise<Response>;
}
export declare function createHostedMcp(options: HostedMcpOptions): (original: Request) => Promise<Response>;
