// Generated by pnpm config:generate. Edit the sibling .mts source.
/** The task tools of NoticeOS's MCP endpoint (epic ro-cvl9; served by
 * hosted-mcp.mts). Every tool is a shared hosted task operation
 * (hosted-task-operations), the same ones the Tasks HTTP API calls, under the
 * same current admission. Results speak in tasks and comments; storage names
 * and command output never reach a client.
 *
 * Human decisions (respond, dismiss, resolve) are not tools: write access
 * must not give an agent a route to answer its own question. Writes require
 * an idempotency key so an agent can retry an interrupted call safely.
 */
import { type HostedTaskOperations } from './hosted-task-operations.mjs';
type Args = Record<string, unknown>;
export interface ToolContext {
    readonly proof: Request;
    readonly workspaceId: string;
    readonly operations: HostedTaskOperations;
}
export interface TaskTool {
    readonly name: string;
    readonly description: string;
    readonly inputSchema: Record<string, unknown>;
    readonly annotations: Record<string, unknown>;
    run(context: ToolContext, args: Args): Promise<unknown>;
}
export declare const TASK_MCP_TOOLS: readonly TaskTool[];
export {};
