// Generated by pnpm generate. Edit the sibling .mts source.
type Tool = {
    path: string;
    sha256: string;
};
export interface HostedDemoSetupRequest {
    version: 1;
    stateRoot: string;
    sourceRoot: string;
    artifactRoot: string;
    workerStateRoot: string;
    publicOrigin: string;
    listen: {
        host: '127.0.0.1' | '0.0.0.0';
        port: number;
    };
    seed: string;
    cutoff: string;
    release: string;
    serviceExpiresAt: string;
    postgres: {
        adminUrl: string;
    };
    dolt: {
        host: string;
        port: number;
        adminUser: string;
        adminPassword: string;
        tls: false;
    };
    binary: Tool;
    doltBinary: Tool;
}
/** No selectors from process.env, inherited providers or installed profiles. */
export declare function captureHostedDemoSetupRequest(value: unknown): HostedDemoSetupRequest;
export declare function readHostedDemoSetupRequest(file: string): HostedDemoSetupRequest;
/** Never resumes a partial operation. Repeat setup adopts only its completed,
 * hash-bound configuration. Seed provenance is independent of later releases. */
export declare function setupHostedDemo(input: HostedDemoSetupRequest): Promise<{
    created: boolean;
    runtimeFile: string;
    workspaceId: string;
    scenarioHash: string;
}>;
export declare function main(argv?: string[]): Promise<number>;
export {};
