// Generated by pnpm generate. Edit the sibling .mts source.
import type { TaskDirectory, TaskProjectCatalogEntry } from '../packages/postgres/src/task-directory.mjs';
import { type TaskReceipts } from '../packages/postgres/src/task-receipts.mjs';
import type { WorkspaceActor } from '../packages/postgres/src/identity.mjs';
import type { WorkspaceAdmission } from './workspace-admission.mjs';
import type { HostedTaskExecutor } from './hosted-task-executor.mjs';
import { type HostedTaskRequest, type HostedTaskStatus } from './hosted-task-command.mjs';
export interface HostedTaskOperationsOptions {
    readonly admission: WorkspaceAdmission;
    readonly directory: Pick<TaskDirectory, 'catalog'>;
    readonly executor: Pick<HostedTaskExecutor, 'execute'>;
    readonly workspaceActors?: (workspaceId: string) => Promise<readonly WorkspaceActor[]>;
    /** Absent: a write that carries an idempotency key is refused as unavailable. */
    readonly receipts?: TaskReceipts;
    /** How long an unfinished attempt is presumed still running (default 5 minutes:
     * the executor's 30-second budget plus room for an orphaned child). */
    readonly pendingMs?: number;
    readonly now?: () => number;
}
export type HostedTaskWriteOutcome = {
    readonly status: 'done';
    readonly value: unknown;
    readonly replayed: boolean;
}
/** An attempt may still be running, or its outcome could not be established. */
 | {
    readonly status: 'pending';
}
/** The key was first used with another project or request. */
 | {
    readonly status: 'conflict';
};
export interface HostedTaskCapabilities {
    readonly live: true;
    readonly writable: boolean;
    readonly projectSelection: true;
    readonly operations: readonly string[];
    readonly editableFields: readonly string[];
}
export interface HostedTaskOperations {
    projects(proof: Request, workspaceId: string): Promise<readonly TaskProjectCatalogEntry[]>;
    capabilities(proof: Request, workspaceId: string): Promise<HostedTaskCapabilities>;
    board(proof: Request, workspaceId: string, projectId: string, statuses: readonly HostedTaskStatus[]): Promise<Record<string, unknown>>;
    task(proof: Request, workspaceId: string, projectId: string, taskId: string): Promise<Record<string, unknown>>;
    history(proof: Request, workspaceId: string, projectId: string, taskId: string, limit: number): Promise<unknown>;
    write(proof: Request, workspaceId: string, request: HostedTaskRequest, idempotencyKey?: string): Promise<HostedTaskWriteOutcome>;
}
/** A write's key cannot be honored on this server: no receipt store is configured. */
export declare class HostedTaskReceiptsUnavailable extends Error {
    name: string;
    constructor();
}
export declare const EDITABLE_TASK_FIELDS: readonly string[];
export declare function createHostedTaskOperations(options: HostedTaskOperationsOptions): HostedTaskOperations;
