// Generated by pnpm config:generate. Edit the sibling .mts source.
import { type HostedTaskOperations } from './hosted-task-operations.mjs';
export declare const TASK_MCP_PATH = "/api/tasks/mcp";
export interface HostedTaskMcpOptions {
    readonly profile: 'hosted' | 'demo';
    readonly trustedOrigin: string;
    readonly demoWorkspaceId?: string;
    readonly operations: HostedTaskOperations;
    /** Agent sign-in (agent-access.mts), hosted only: verifies a bearer
     * request's token for this endpoint. Without it, a bearer request is
     * refused. Admission verifies it again, with fresh membership, per call. */
    readonly agents?: {
        verify(request: Request): Promise<{
            readonly workspaceId: string;
            readonly scopes: readonly string[];
        } | null>;
    };
}
type Args = Record<string, unknown>;
interface ToolContext {
    readonly proof: Request;
    readonly workspaceId: string;
    readonly operations: HostedTaskOperations;
}
interface Tool {
    readonly name: string;
    readonly description: string;
    readonly inputSchema: Record<string, unknown>;
    readonly annotations: Record<string, unknown>;
    run(context: ToolContext, args: Args): Promise<unknown>;
}
export declare const TASK_MCP_TOOLS: readonly Tool[];
export declare function createHostedTaskMcp(options: HostedTaskMcpOptions): (original: Request) => Promise<Response>;
export {};
