// Generated by pnpm config:generate. Edit the sibling .mts source.
/** Tower-compatible Tasks API in the trusted Node server. The private directory
 * supplies selectors, not authorization; every child command independently
 * reloads current session, workspace and physical mapping before dispatch.
 */
import type { TaskDirectory } from '../packages/postgres/src/task-directory.mjs';
import type { WorkspaceAdmission } from './workspace-admission.mjs';
import type { HostedTaskExecutor } from './hosted-task-executor.mjs';
import type { WorkspaceActor } from '../packages/postgres/src/identity.mjs';
export interface HostedTasksApiOptions {
    readonly profile: 'hosted' | 'demo';
    readonly trustedOrigin: string;
    readonly demoWorkspaceId?: string;
    readonly admission: WorkspaceAdmission;
    readonly directory: Pick<TaskDirectory, 'catalog'>;
    readonly executor: Pick<HostedTaskExecutor, 'execute'>;
    readonly workspaceActors?: (workspaceId: string) => Promise<readonly WorkspaceActor[]>;
}
export declare function createHostedTasksApi(options: HostedTasksApiOptions): (original: Request) => Promise<Response>;
