// Generated by pnpm config:generate. Edit the sibling .mts source.
import type { IncomingMessage, ServerResponse } from 'node:http';
import { type HostedTaskRuntimeOptions, type HostedTaskRuntime } from './hosted-task-runtime.mjs';
interface ViteServer {
    listen(): Promise<unknown>;
    close(): Promise<void>;
}
export interface HostedTaskViteOptions {
    readonly root: string;
    readonly configFile: string;
    readonly plugins: readonly ReturnType<typeof hostedTasksPlugin>[];
    readonly logLevel: 'error';
    readonly server: {
        readonly host: '127.0.0.1';
        readonly port: number;
        readonly strictPort: true;
        readonly open: false;
    };
}
interface MiddlewareServer {
    middlewares: {
        use(work: (request: IncomingMessage, response: ServerResponse, next: () => void) => void): void;
    };
}
/** The actual native middleware never delegates a recognized task request to
 * a Worker or standalone lane. Host/target comes from the real native request;
 * forwarded Host/profile/actor/context headers confer no authority. */
export declare function hostedTasksPlugin(runtime: HostedTaskRuntime): {
    name: string;
    enforce: "pre";
    apply: "serve";
    configureServer(server: MiddlewareServer): void;
};
/** Private file is operator-supplied composition, not tenant input or a secret
 * fallback. Regular canonical owner-only files prevent accidental public use. */
export declare function readHostedTaskRuntimeFile(filename: string): HostedTaskRuntimeOptions;
export declare function startHostedTaskServer(options: {
    readonly runtime: HostedTaskRuntimeOptions;
    /** Explicit trusted configs; no installation/default root fallback. */
    readonly workerConfigRoot: string;
    /** Trusted composition seam for local fixture config rebinding. Not read
     * from runtime JSON, environment, requests, or the command-line interface. */
    readonly createViteServer?: (options: HostedTaskViteOptions) => Promise<ViteServer>;
}): Promise<{
    readonly runtime: HostedTaskRuntime;
    close(): Promise<void>;
}>;
export {};
