// Generated by pnpm config:generate. Edit the sibling .mts source.
import type { WorkspaceStore } from '../packages/postgres/src/store.mjs';
import type { WorkspaceServiceGrant } from '../packages/postgres/src/service-grant.mjs';
import { type HostedJobReceipt } from './hosted-job-runner.mjs';
import type { HostedTaskExecutor } from './hosted-task-executor.mjs';
import type { BeadsSnapshotInput } from '../packages/contract/src/task-snapshot.mjs';
import { type DemoActivityDay } from './demo-activity.mjs';
import { type DemoScenario } from './demo-scenario.mjs';
export interface DemoActivityWriter {
    write(store: WorkspaceStore, day: DemoActivityDay): Promise<{
        written: number;
        assets: number;
        date: string;
    }>;
    snapshot(store: WorkspaceStore, snapshot: BeadsSnapshotInput): Promise<{
        written: number;
    }>;
}
export interface HostedDemoOptions {
    readonly workspaceId: string;
    readonly serviceId: string;
    readonly scenario: DemoScenario;
    readonly store: WorkspaceStore;
    readonly grant: WorkspaceServiceGrant;
    readonly writer: DemoActivityWriter;
    readonly tasks: Pick<HostedTaskExecutor, 'execute'>;
    readonly projects: readonly {
        readonly asset: string;
        readonly projectId: string;
        readonly prefix: string;
    }[];
    /** Server composition may supply a controlled clock in disposable tests. */
    readonly now?: () => number;
}
export interface HostedDemoTick {
    readonly synthetic: true;
    readonly through: string;
    readonly days: readonly {
        readonly date: string;
        readonly receipt: HostedJobReceipt;
    }[];
}
export declare class HostedDemoRefused extends Error {
    name: string;
    constructor();
}
/** Owns store and grant. Deployment owns and closes the task executor's
 * directory after this handle closes. No filesystem or physical task selector
 * crosses tick(). All task commands still pass through the real hosted service.
 */
export declare function createHostedDemo(options: HostedDemoOptions): {
    tick(): Promise<HostedDemoTick>;
    close(): Promise<void>;
};
