// Generated by pnpm config:generate. Edit the sibling .mts source.
/** Server-composed task photograph. Reuses the ordinary poller's summary;
 * neither project labels nor a snapshot carry task or workspace authority. */
import type { BeadsSnapshotInput } from '../packages/contract/src/task-snapshot.mjs';
import type { HostedTaskExecutor, TaskVerificationControls } from './hosted-task-executor.mjs';
export interface HostedTaskSnapshotProject {
    readonly projectId: string;
    readonly asset: string;
    readonly prefix: string;
}
export interface HostedTaskSnapshotOptions {
    readonly workspaceId: string;
    readonly projects: readonly HostedTaskSnapshotProject[];
    readonly executor: Pick<HostedTaskExecutor, 'execute'>;
}
export type HostedBeadsSnapshot = BeadsSnapshotInput & {
    capturedAt: string;
};
export interface HostedTaskSnapshotReader {
    snapshot(original: Request, controls?: Omit<TaskVerificationControls, 'expectedPrefix'>): Promise<HostedBeadsSnapshot>;
}
export declare function createHostedTaskSnapshot(options: HostedTaskSnapshotOptions): HostedTaskSnapshotReader;
