// Generated by pnpm config:generate. Edit the sibling .mts source.
import type { Transaction, WorkspaceStore } from '../packages/postgres/src/store.mjs';
import type { WorkspaceServiceGrant } from '../packages/postgres/src/service-grant.mjs';
import { type WorkspaceAction, type WorkspaceContext } from './workspace-admission.mjs';
import type { WorkflowStepOutput } from '../packages/contract/src/workflows.js';
/** The registry is executable deployment code, never a request or saved config.
 * Inputs are validated by that code, kept in memory, and persisted only as a
 * digest. Retrying requires supplying the identical validated input again. */
export type JobInput = null | boolean | number | string | readonly JobInput[] | {
    readonly [key: string]: JobInput;
};
interface StepCall {
    readonly context: WorkspaceContext;
    readonly occurrence: string;
    readonly input: JobInput;
    /** Adapters must honor cancellation and await their owned resource cleanup. */
    readonly signal: AbortSignal;
}
export type HostedJobStep = {
    readonly key: string;
    readonly action: WorkspaceAction;
} & ({
    readonly kind: 'database';
    readonly run: (call: StepCall, tx: Transaction) => Promise<unknown>;
} | {
    readonly kind: 'effect';
    readonly run: (call: StepCall) => Promise<unknown>;
});
export interface HostedJobDefinition {
    readonly key: string;
    /** Change when the implementation or its interpretation of input changes. */
    readonly version: string;
    readonly parseInput: (input: unknown) => JobInput;
    readonly steps: readonly HostedJobStep[];
}
type State = 'running' | 'retryable' | 'succeeded' | 'uncertain' | 'blocked' | 'exhausted';
interface Evidence {
    readonly state: 'succeeded' | 'skipped';
    readonly summary: string;
    readonly attempt?: number;
    readonly startedAt?: string;
    readonly finishedAt?: string;
    readonly output?: WorkflowStepOutput;
}
export interface HostedJobReceipt {
    readonly state: State | 'busy';
    readonly attempt: number;
    readonly steps: Readonly<Record<string, Evidence>>;
}
export interface HostedJobRunner {
    run(lane: string, occurrence: string, input: unknown): Promise<HostedJobReceipt>;
    close(): Promise<void>;
}
export declare class HostedJobRefused extends Error {
    name: string;
    constructor();
}
/** Owns the supplied store/grant, which deployment must bind to this workspace.
 * Only this registry's callbacks receive fresh action contexts. No platform,
 * operator session, filesystem root or bearer proof is accepted by run(). */
export declare function createHostedJobRunner(options: {
    readonly workspaceId: string;
    readonly serviceId: string;
    readonly grant: WorkspaceServiceGrant;
    readonly store: WorkspaceStore;
    readonly definitions: readonly HostedJobDefinition[];
}): HostedJobRunner;
export {};
