// Generated by pnpm config:generate. Edit the sibling .mts source.
/** Browser-visible protocol names only; none grants identity or membership. */
export declare const EMAIL_CODE_PATHS: Readonly<{
    request: "/api/auth/email-otp/send-verification-otp";
    verify: "/api/auth/sign-in/email-otp";
    logout: "/api/auth/sign-out";
}>;
export declare const EMAIL_ENROLLMENT_HEADERS: Readonly<{
    kind: "x-noticeos-enrollment-kind";
    id: "x-noticeos-enrollment-id";
}>;
export declare const MEMBERSHIP_PATH = "/api/memberships";
export declare const ACCEPT_INVITATION_PATH = "/api/invitations/accept";
export interface EmailEnrollment {
    readonly kind: 'platform' | 'invitation';
    readonly id: string;
}
export type EmailEnrollmentLanding = Readonly<{
    kind: 'none';
}> | Readonly<{
    kind: 'invalid';
}> | Readonly<{
    kind: 'enrollment';
    enrollment: EmailEnrollment;
    cleanUrl: string;
}>;
/** A mailbox-bound enrollment selector, never email, code or authority. */
export declare function emailEnrollmentUrl(origin: string, enrollment: EmailEnrollment): string;
/** Capture once, then remove the fragment before making a request. Unknown or
 * malformed sign-in links must not become ordinary account login. */
export declare function parseEmailEnrollmentLanding(input: string): EmailEnrollmentLanding;
