// Generated by pnpm config:generate. Edit the sibling .mts source.
// installation.mts — where THIS installation's files are, and where the
// product's generic defaults are (bead ro-ujb9.125; decisions D22, D30, D33).
//
// Two folders, one rule:
//
//   config/         the product's defaults. Generic: no site, no task project,
//                   no repository path, UTC. Every clone carries them, and a
//                   fresh clone's `pnpm config:seed` loads them.
//   installation/   one installation's own documents, its applied changesets
//                   and its host-only files (the task repository links, the
//                   task hub's server config, the offsite backup folder). `pnpm config:export` and a Save
//                   in the Tower write here; `pnpm config:seed` prefers a copy
//                   here over the default. The private repository tracks it;
//                   the public release leaves it out.
//
// `NOTICEOS_INSTALLATION_DIR` moves the second folder — absolute, or relative
// to the checkout (an older installation's `REINDEX_OS_INSTALLATION_DIR` is
// still read, scripts/product-env.mts). Unset, it is `installation/` in the
// checkout.
//
// A config document keeps its NAME, `config/pull.json`: that is its key in the
// store (`config_documents.file`) and in every changeset op, and a key that
// moved would orphan every saved row. This module only says where its FILE is.
//
// One resolver, so seed, export, apply, the Tower's local lanes, the runner,
// backups and the neutral-code gate cannot each decide it differently. Node
// only: a deployed Worker has no filesystem and reads the store.
import { existsSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { PRODUCT_ENV, readProductEnv } from './product-env.mjs';
const REPO_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
/** The environment variable that moves this installation's folder. */
export const INSTALLATION_DIR_ENV = PRODUCT_ENV.installationDir.name;
/** The folder's place when the variable is unset, relative to the checkout. */
export const DEFAULT_INSTALLATION_DIR = 'installation';
/** The product's defaults, relative to the checkout. Also the prefix of every
 * config document's store key. */
export const PRODUCT_DEFAULTS_DIR = 'config';
/** The applied-changeset archive, inside the installation folder. */
export const CHANGESETS_DIR = 'changesets';
/** The host's task repository links (host-only, never in the store). */
export const TASK_HOST_FILE = 'task-host.json';
/** Where this host copies each night's finished backup off the machine
 * (host-only, never in the store; bead ro-ujb9.120). */
export const HOST_BACKUP_FILE = 'host-backup.json';
/** The names this installation's database and bucket were made under, when
 * they are not the checked-in Worker configs' (host-only, never in the store;
 * bead ro-ujb9.77.8; read by scripts/resource-names.mts readResourceNames). A
 * new installation has none. */
export const RESOURCE_NAMES_FILE = 'resource-names.json';
/** This installation's folder, absolute. */
export function installationDir({ root = REPO_ROOT, env = process.env } = {}) {
    const named = readProductEnv(env, 'installationDir');
    return path.resolve(root, named ? named : DEFAULT_INSTALLATION_DIR);
}
/**
 * A file's name inside either folder: a store key (`config/pull.json`) loses
 * its `config/` prefix; a bare name (`task-host.json`, `changesets`) is kept.
 */
export function fileName(name) {
    const prefix = `${PRODUCT_DEFAULTS_DIR}/`;
    const bare = name.startsWith(prefix) ? name.slice(prefix.length) : name;
    const parts = bare.split('/');
    if (bare === '' || path.isAbsolute(bare) || parts.some((part) => part === '' || part === '.' || part === '..')) {
        throw new Error(`not an installation file name: ${JSON.stringify(name)}`);
    }
    return bare;
}
/** Where this installation's copy of `name` is (whether or not it exists yet).
 * Every write goes here. */
export function installationPath(name, options = {}) {
    return path.join(installationDir(options), fileName(name));
}
/** Where the product's generic default for `name` is. */
export function productDefaultPath(name, { root = REPO_ROOT } = {}) {
    return path.join(root, PRODUCT_DEFAULTS_DIR, fileName(name));
}
/**
 * The file to READ for `name`: this installation's copy when it has one, else
 * the product's default. A fresh clone therefore reads the defaults, and an
 * installation that saved a document reads its own.
 */
export function readablePath(name, options = {}) {
    const own = installationPath(name, options);
    return existsSync(own) ? own : productDefaultPath(name, options);
}
/**
 * How a path is written for an operator and for `git add`: relative to the
 * checkout, with forward slashes, when it is inside it; absolute otherwise (an
 * installation folder kept outside the checkout is committed by its own repo).
 */
export function checkoutRelative(file, { root = REPO_ROOT } = {}) {
    const relative = path.relative(root, file);
    if (relative === '' || relative.startsWith('..') || path.isAbsolute(relative))
        return file;
    return relative.split(path.sep).join('/');
}
