// Generated by pnpm generate. Edit the sibling .mts source.
/** The environment variable that moves this installation's folder. */
export declare const INSTALLATION_DIR_ENV: string;
/** The folder's place when the variable is unset, relative to the checkout. */
export declare const DEFAULT_INSTALLATION_DIR: string;
/** The product's defaults, relative to the checkout. Also the prefix of every
 * config document's store key. */
export declare const PRODUCT_DEFAULTS_DIR: string;
/** The applied-changeset archive, inside the installation folder. */
export declare const CHANGESETS_DIR: string;
/** The host's task repository links (host-only, never in the store). */
export declare const TASK_HOST_FILE: string;
/** Where this host copies each night's finished backup off the machine
 * (host-only, never in the store). */
export declare const HOST_BACKUP_FILE: string;
/** The names this installation's database and bucket were made under, when
 * they are not the checked-in Worker configs' (host-only, never in the store;
 * read by scripts/resource-names.mts readResourceNames). A new installation
 * has none. */
export declare const RESOURCE_NAMES_FILE: string;
export interface InstallationOptions {
    /** The checkout: the home checkout for the live runner and its lanes. */
    root?: string;
    /** Where `NOTICEOS_INSTALLATION_DIR` (or its legacy name) is read. */
    env?: Readonly<Record<string, string | undefined>>;
}
/** This installation's folder, absolute. */
export declare function installationDir({ root, env }?: InstallationOptions): string;
/**
 * A file's name inside either folder: a store key (`config/pull.json`) loses
 * its `config/` prefix; a bare name (`task-host.json`, `changesets`) is kept.
 */
export declare function fileName(name: string): string;
/** Where this installation's copy of `name` is (whether or not it exists yet).
 * Every write goes here. */
export declare function installationPath(name: string, options?: InstallationOptions): string;
/** Where the product's generic default for `name` is. */
export declare function productDefaultPath(name: string, { root }?: InstallationOptions): string;
/**
 * The file to READ for `name`: this installation's copy when it has one, else
 * the product's default. A fresh clone therefore reads the defaults, and an
 * installation that saved a document reads its own.
 */
export declare function readablePath(name: string, options?: InstallationOptions): string;
/**
 * How a path is written for an operator and for `git add`: relative to the
 * checkout, with forward slashes, when it is inside it; absolute otherwise (an
 * installation folder kept outside the checkout is committed by its own repo).
 */
export declare function checkoutRelative(file: string, { root }?: InstallationOptions): string;
