// Generated by pnpm config:generate. Edit the sibling .mts source.
export declare const MCP_MODERN_VERSIONS: readonly string[];
export declare const MCP_LEGACY_VERSIONS: readonly string[];
export declare const MCP_ERRORS: Readonly<{
    parse: -32700;
    invalidRequest: -32600;
    methodNotFound: -32601;
    invalidParams: -32602;
    internal: -32603;
    headerMismatch: -32020;
    unsupportedVersion: -32022;
}>;
export interface McpTool {
    readonly name: string;
    readonly description: string;
    readonly inputSchema: Readonly<Record<string, unknown>>;
    readonly annotations?: Readonly<Record<string, unknown>>;
}
export interface McpServer {
    readonly info: Readonly<{
        name: string;
        version: string;
    }>;
    readonly instructions?: string;
    readonly tools: readonly McpTool[];
    /** Runs a listed tool. Throw McpToolError for an answer the model should
     * read; anything else is a fault and is never echoed. */
    call(name: string, args: Record<string, unknown>): Promise<unknown>;
}
export interface McpServeOptions {
    /** The only browser origin allowed to call; by default the request's own. */
    readonly origin?: string;
    readonly maxBytes?: number;
    /** Sees the parsed body before any method runs and may answer instead. */
    readonly screen?: (body: unknown) => Response | null;
    /** Sees each request's message before its method runs and may answer
     * instead: the place an endpoint asks for a scope the call needs. */
    readonly authorize?: (message: McpMessage) => Response | null;
}
/** A tool's own refusal, returned to the model as an error result it can read. */
export declare class McpToolError extends Error {
    name: string;
}
/** A JSON-RPC message refused before any method runs. */
export declare class McpRefused extends Error {
    readonly code: number;
    readonly status: number;
    readonly id: string | number | null;
    readonly data?: unknown | undefined;
    name: string;
    constructor(code: number, message: string, status: number, id?: string | number | null, data?: unknown | undefined);
}
export interface McpMessage {
    /** Absent for a notification. */
    readonly id?: string | number;
    readonly method: string;
    readonly params: Readonly<Record<string, unknown>>;
    /** The 2026-07-28 era's marker: the version named in `params._meta`. */
    readonly version: string | null;
}
/** JSON with no duplicate keys and bounded depth and size: a hidden duplicate
 * cannot make two readers of one request disagree. */
export declare function strictJson(text: string, maxNodes?: number, maxDepth?: number): unknown;
export declare const MCP_METHODS: readonly string[];
export declare function parseMcpMessage(value: unknown): McpMessage;
/** One MCP POST, either era. The caller has already chosen the route and
 * established whatever admission its tools need. */
export declare function serveMcp(request: Request, server: McpServer, options?: McpServeOptions): Promise<Response>;
