// Generated by pnpm config:generate. Edit the sibling .mts source.
/** One line of the host's deploy log, as `record()` writes it. */
export interface OsDeployRecord {
    at: string;
    action: 'deploy' | 'rollback';
    /** A rollback the deploy made by itself after a failed restart. */
    automatic?: boolean;
    from: string | null;
    to: string;
    slot?: string;
    result: 'prepared' | 'failed' | 'healthy';
}
/** What a forwarder reads deploys from. */
export interface OsDeploySource {
    read(): Promise<OsDeployRecord[]>;
}
/** An install with no deploy log: nothing to forward, never an error. */
export declare const NO_DEPLOY_SOURCE: OsDeploySource;
export type OsDeployOutcome = 'deployed' | 'rolled-back' | 'failed';
/** The note each outcome is stored with — and the only notes the feed reads as
 * an OS deploy. Short sentences, no commit, host, path or folder in them. */
export declare const OS_DEPLOY_NOTES: Readonly<Record<OsDeployOutcome, string>>;
/** The annotation one deploy becomes, in the ingest's own input shape. */
export interface OsDeployAnnotation {
    asset: string;
    at: string;
    kind: 'deploy';
    ref: string;
    note: string;
}
/** What a record means, or null for one that moved nothing live (a prepared
 * copy the service does not run yet) or that cannot be read. */
export declare function osDeployOutcomeOf(record: unknown): OsDeployOutcome | null;
/**
 * The annotation for one recorded deploy, or null when it is not one to show.
 * Only the recorded time and the target commit leave the record: never the
 * runtime folder it moved into, which is a host path.
 */
export declare function osDeployAnnotation(record: unknown, osAsset: string): OsDeployAnnotation | null;
/** The reverse, for a reader holding a stored annotation's note. */
export declare function osDeployOutcome(note: string | null | undefined): OsDeployOutcome | null;
