// Generated by pnpm generate. Edit the sibling .mts source.
/** Redact common credential shapes without knowing or loading any secret. */
export declare function redactLogText(value: unknown): string;
