// Generated by pnpm config:generate. Edit the sibling .mts source.
/** Wrangler's documented variable for the POSTGRES Hyperdrive binding's local
 * connection string: how a test's dev server or Workers pool hands both
 * Workers their store, as the runner and `pnpm start` do
 * (scripts/database-address.mts). */
export { LOCAL_CONNECTION_VARIABLE } from './database-address.mjs';
/** An address nothing answers: what the binding names where a test's Workers
 * must declare it (wrangler refuses one without a local address) and nothing
 * reads the store, or before a test replaces it with its own copy's. */
export declare const UNREACHABLE_STORE_URL = "postgresql://noticeos_app:unused@127.0.0.1:9/noticeos_unused_dev?sslmode=disable";
/** Plain data a test process uses to reach the run's cluster; handed over in memory (Vitest's `provide`) or in a child process's environment, never written to a file. */
export interface TestClusterHandle {
    /** The application role's loopback connection string for the template; a copy's differs only in its database. */
    readonly appUrl: string;
    /** The installation's one workspace, the same in every copy. */
    readonly workspaceId: string;
    /** The unix socket of the starting process's copy service. */
    readonly copyService: string;
}
/** What a test run does with its cluster. */
export interface TestClusterOperations {
    /** The installation's one workspace, the same in every copy. */
    readonly workspaceId: string;
    /** The application role's loopback connection string for one of the cluster's databases. */
    url(database: string): string;
    /** A new copy of the template; returns its name (a fresh one unless `name` is given). */
    createDatabase(name?: string): Promise<string>;
    /** The copy made again from the template, under the same name: every
     * connection to it is ended and everything written to it is gone. */
    resetDatabase(name: string): Promise<string>;
    /** Refresh planner statistics for this copy through its owner's service. */
    analyzeDatabase(name: string): Promise<void>;
    /** Drop a copy, ending any connection to it. */
    dropDatabase(name: string): Promise<void>;
    /** Give back a copy a test is done with: every connection to it is ended and
     * its name is gone, as after a drop, and the cluster may hand it, emptied and
     * under a new name, to the next test that asks (scripts/postgres-test-cluster.mts). */
    releaseDatabase(name: string): Promise<void>;
}
/** `name`, when it can name a copy. */
export declare function checkCopyName(name: unknown): string;
/** The application role's connection string for `database`, from the template's. */
export declare function copyUrl(appUrl: string, database: string): string;
/** The fixed operations a test process may request on its own copy. */
export type CopyRequest = {
    readonly op: 'create';
    readonly name?: string;
} | {
    readonly op: 'reset';
    readonly name: string;
} | {
    readonly op: 'analyze';
    readonly name: string;
} | {
    readonly op: 'drop';
    readonly name: string;
} | {
    readonly op: 'release';
    readonly name: string;
};
/** The operations on the run's cluster, from a test process. */
export declare function attachTestCluster(handle: TestClusterHandle): TestClusterOperations;
