// Generated by pnpm generate. Edit the sibling .mts source.
/** A Postgres migration filename: four digits, then lower-case letters,
 * digits or underscores. Capture 1 is its version; no filesystem or store
 * access is needed to recognize a name. */
export declare const MIGRATION_FILE: RegExp;
