#!/usr/bin/env node
// Generated Postgres model docs: the revision-rule matrix
// from model.json, constraints from a disposable migrated cluster, and the
// schema-qualified SQL consumer inventory. No legacy schema is loaded.
// --write regenerates the model and constraints; --consumers reads current source.

import { existsSync, readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const REPO_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

const MODEL = path.join(REPO_ROOT, 'db', 'postgres');
export const MATRIX_START = '<!-- matrix:start (generated by node scripts/postgres-docs.mjs --write) -->';
export const MATRIX_END = '<!-- matrix:end -->';
export const CONSTRAINTS_PATH = path.join(MODEL, 'constraints.md');

function revisionWords(target) {
  if (!target) return '—';
  if (target.view) return 'read-only view';
  const { insert, update, delete: remove } = target.revision;
  if (!insert) return 'read-only';
  if (update === 'all') return remove ? 'insert, update, delete' : 'insert, update';
  if (update.length === 0) return remove ? 'insert, delete' : 'append-only';
  return `insert; update only ${update.join(', ')}${remove ? '; delete' : ''}`;
}

/** The README's operational revision-rule matrix, from model.json. */
export function matrixMarkdown(model) {
  const rows = ['| Postgres table or view | What the application may do | Rule |', '|---|---|---|'];
  for (const [name, target] of Object.entries(model.targets).sort(([a], [b]) => a.localeCompare(b))) {
    rows.push(`| \`${name}\`${target.view ? ' (view)' : ''} | ${revisionWords(target)} | ${target.rule ?? 'Read through workspace row security.'} |`);
  }
  return rows.join('\n');
}

// ─── The constraint matrix, read from what Postgres built ───────────────────

/** One query: every table in schemas noticeos and noticeos_ref (the shared
 * vocabulary, named with its schema, after the rest) with its columns,
 * constraints, standalone unique indexes and triggers, as JSON. Metadata only. */
const CATALOG_SQL = `
SELECT json_agg(t ORDER BY t.shared, t.name) FROM (
  SELECT CASE WHEN n.nspname = 'noticeos' THEN c.relname ELSE n.nspname || '.' || c.relname END AS name,
    n.nspname <> 'noticeos' AS shared,
    (SELECT json_agg(json_build_object(
              'name', a.attname,
              'type', format_type(a.atttypid, a.atttypmod),
              'notNull', a.attnotnull,
              'identity', a.attidentity <> '',
              'default', pg_get_expr(d.adbin, d.adrelid)) ORDER BY a.attnum)
       FROM pg_attribute a
       LEFT JOIN pg_attrdef d ON d.adrelid = a.attrelid AND d.adnum = a.attnum
      WHERE a.attrelid = c.oid AND a.attnum > 0 AND NOT a.attisdropped) AS columns,
    (SELECT coalesce(json_agg(json_build_object(
              'name', k.conname,
              'kind', k.contype,
              'def', pg_get_constraintdef(k.oid),
              'columns', (SELECT json_agg(a.attname ORDER BY x.ord)
                            FROM unnest(k.conkey) WITH ORDINALITY x(attnum, ord)
                            JOIN pg_attribute a ON a.attrelid = c.oid AND a.attnum = x.attnum))
            ORDER BY k.contype, k.conname), '[]')
       FROM pg_constraint k WHERE k.conrelid = c.oid) AS constraints,
    (SELECT coalesce(json_agg(json_build_object(
              'name', i.relname,
              'def', pg_get_indexdef(x.indexrelid),
              'predicate', pg_get_expr(x.indpred, x.indrelid),
              'nullsNotDistinct', x.indnullsnotdistinct,
              'columns', (SELECT json_agg(a.attname ORDER BY k.ord)
                            FROM unnest(x.indkey::int2[]) WITH ORDINALITY k(attnum, ord)
                            JOIN pg_attribute a ON a.attrelid = c.oid AND a.attnum = k.attnum))
            ORDER BY i.relname), '[]')
       FROM pg_index x JOIN pg_class i ON i.oid = x.indexrelid
      WHERE x.indrelid = c.oid AND x.indisunique
        AND NOT EXISTS (SELECT 1 FROM pg_constraint k WHERE k.conindid = x.indexrelid)) AS unique_indexes,
    (SELECT coalesce(json_agg(json_build_object('name', g.tgname, 'def', pg_get_triggerdef(g.oid)) ORDER BY g.tgname), '[]')
       FROM pg_trigger g WHERE g.tgrelid = c.oid AND NOT g.tgisinternal) AS triggers
  FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
  WHERE n.nspname IN ('noticeos', 'noticeos_ref') AND c.relkind = 'r') t`;

/** Every table's catalog entry, read through a superuser `psql` runner. */
export function readCatalog(psql) {
  return JSON.parse(psql(CATALOG_SQL).trim());
}

/** A constraint or index expression, shortened for reading: no `::text`
 * casts, no outer CHECK wrapper, `=` ANY(ARRAY[...]) spelled IN (...). */
function readable(def) {
  return def
    .replace(/::(text|character varying|bpchar|integer|bigint|numeric|date|timestamp with time zone|double precision|jsonb|json)\b(\[\])?/gu, '')
    .replace(/^CHECK \((.*)\)$/su, '$1')
    .replace(/ = ANY \(ARRAY\[([^\]]*)\]\)/gu, ' IN ($1)')
    .replace(/\|/gu, '\\|');
}

/** The columns a table's constraint names, as `(a, b)`. */
const list = (columns) => `(${columns.join(', ')})`;

/** db/postgres/constraints.md, from `readCatalog`. */
export function constraintsMarkdown(catalog) {
  const lines = [
    '# Constraint matrix',
    '',
    'Generated by `node scripts/postgres-docs.mjs --write` from what Postgres',
    'builds out of [`migrations/`](migrations/); do not edit',
    'by hand. `scripts/postgres-model.test.mjs` fails while it disagrees.',
    '',
    'Every table below but the shared vocabulary (`noticeos_ref.*`, last) also has',
    'row security enabled and forced, with the `workspace_isolation` policy on',
    'reads and writes; `workspaces` also lets its owner read the whole list',
    '(`owner_lists_workspaces`, which `noticeos.only_workspace()` needs)',
    '([`tests/rls-denial.sql`](tests/rls-denial.sql) proves both),',
    'and every view runs with the caller\'s rights. What a NULL means in a key or a',
    'link is decided per column in [`model.json`](model.json) `nullIdentity`;',
    'which rows leave for the analytical store, and when, is its `retention`.',
    '',
  ];
  for (const table of catalog) {
    const columnChecks = new Map();
    const rowChecks = [];
    for (const constraint of table.constraints.filter((k) => k.kind === 'c')) {
      if (constraint.columns.length === 1) {
        const [column] = constraint.columns;
        columnChecks.set(column, [...(columnChecks.get(column) ?? []), readable(constraint.def)]);
      } else {
        rowChecks.push(readable(constraint.def));
      }
    }
    lines.push(`## \`${table.name}\``, '', '| Column | Type | Required | Checks |', '|---|---|---|---|');
    for (const column of table.columns) {
      const type = column.identity ? `${column.type}, identity` : column.type;
      const checks = (columnChecks.get(column.name) ?? []).map((check) => `\`${check}\``).join('; ');
      lines.push(`| \`${column.name}\` | ${type} | ${column.notNull ? 'yes' : 'no'} | ${checks} |`);
    }
    lines.push('');
    const keys = table.constraints
      .filter((k) => k.kind === 'p' || k.kind === 'u')
      .map((k) => `${k.kind === 'p' ? 'primary' : 'unique'} ${list(k.columns)}${/NULLS NOT DISTINCT/u.test(k.def) ? ', NULLs not distinct' : ''}`);
    for (const index of table.unique_indexes) {
      keys.push(`unique ${list(index.columns)}${index.predicate ? ` where \`${readable(index.predicate)}\`` : ''}${index.nullsNotDistinct ? ', NULLs not distinct' : ''}`);
    }
    lines.push(`- **Keys:** ${keys.join('; ')}`);
    const links = table.constraints
      .filter((k) => k.kind === 'f')
      .map((k) => {
        const [, schema, table] = /REFERENCES (noticeos(?:_ref)?)\.([a-z_]+)/u.exec(k.def);
        const shown = schema === 'noticeos' ? table : `${schema}.${table}`;
        return `${list(k.columns)} → \`${shown}\`${/ON DELETE CASCADE/u.test(k.def) ? ' (removed with it)' : ''}`;
      });
    if (links.length) lines.push(`- **Links:** ${links.join('; ')}`);
    if (rowChecks.length) lines.push(`- **Row checks:** ${rowChecks.map((check) => `\`${check}\``).join('; ')}`);
    if (table.triggers.length) {
      const triggers = table.triggers.map((trigger) => {
        const [, when, event] = / (BEFORE|AFTER) (.*?) ON /u.exec(trigger.def);
        return `\`${trigger.name}\` (${when.toLowerCase()} ${event.toLowerCase()})`;
      });
      lines.push(`- **Triggers:** ${triggers.join('; ')}`);
    }
    lines.push('');
  }
  return `${lines.join('\n').trimEnd()}\n`;
}

/**
 * `{ 'table.column': { unique?: 'one'|'many'|'excluded' } }` for every
 * nullable column that takes part in a unique key or a link — the decisions
 * model.json `nullIdentity` must record, in its own vocabulary.
 */
export function nullableIdentityColumns(catalog) {
  const found = {};
  for (const table of catalog) {
    const nullable = new Set(table.columns.filter((c) => !c.notNull).map((c) => c.name));
    const note = (column, unique) => {
      const key = `${table.name}.${column}`;
      found[key] ??= {};
      if (unique) found[key].unique = unique;
    };
    for (const constraint of table.constraints) {
      for (const column of constraint.columns ?? []) {
        if (!nullable.has(column)) continue;
        if (constraint.kind === 'u' || constraint.kind === 'p') {
          note(column, /NULLS NOT DISTINCT/u.test(constraint.def) ? 'one' : 'many');
        } else if (constraint.kind === 'f') {
          note(column, null);
        }
      }
    }
    for (const index of table.unique_indexes) {
      for (const column of index.columns) {
        if (!nullable.has(column)) continue;
        const skips = index.predicate && new RegExp(`\\b${column} IS NOT NULL\\b`, 'u').test(index.predicate);
        note(column, skips ? 'excluded' : index.nullsNotDistinct ? 'one' : 'many');
      }
    }
  }
  return found;
}

// ─── Consumers of each Postgres table ─────────────────────────────────────────────

const ROOTS = ['apps/tower', 'workers/ingest', 'packages', 'scripts'];
const SKIP_DIRS = new Set(['node_modules', 'dist', '.wrangler', 'playwright-report', 'test-results', '.vite']);
const EXTENSIONS = new Set(['.ts', '.tsx', '.mts', '.mjs', '.js']);

function existsBeside(file, extension) {
  try {
    return statSync(file.replace(/\.[^.]+$/u, extension)).isFile();
  } catch {
    return false;
  }
}

/** A folder the walk never enters: dependencies, build and test output (a
 * `dist-` folder too, like the one the contract's load check builds while
 * the tests run), and anything hidden. */
const skipped = (name) => SKIP_DIRS.has(name) || name.startsWith('dist-') || name.startsWith('.');

function* sourceFiles(dir) {
  // In name order, so the list reads the same on every file system.
  if (!existsSync(dir)) return;
  const entries = readdirSync(dir, { withFileTypes: true }).sort((a, b) => (a.name < b.name ? -1 : a.name > b.name ? 1 : 0));
  for (const entry of entries) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      if (!skipped(entry.name)) yield* sourceFiles(full);
    } else if (EXTENSIONS.has(path.extname(entry.name))) {
      // A generated .mjs beside its authored .mts is the same consumer.
      if (entry.name.endsWith('.mjs') && existsBeside(full, '.mts')) continue;
      yield full;
    }
  }
}

function isTest(relative) {
  return /(^|\/)(test|test-fixtures|e2e)\//u.test(relative) || /\.(test|spec)\.[a-z]+$/u.test(relative);
}

/** Schema-qualified tables/views from the operational model and shared vocabulary. */
export function findConsumers(root = REPO_ROOT) {
  const model = JSON.parse(readFileSync(path.join(root, 'db/postgres/model.json'), 'utf8'));
  const names = [...Object.keys(model.targets).map(name => `noticeos.${name}`),
    ...Object.keys(model.reference).filter(name => !name.startsWith('_')).map(name => `noticeos_ref.${name}`)].sort();
  const patterns = names.map((name) => {
    const qualified = name.split('.').map(part => `"?${part}"?`).join('\\s*\\.\\s*');
    return [name, new RegExp(`\\b(?:FROM|JOIN|INTO|UPDATE|REFERENCES|TABLE(?:\\s+IF\\s+(?:NOT\\s+)?EXISTS)?)\\s+${qualified}(?![a-z0-9_])`, 'iu')];
  });
  const found = Object.fromEntries(names.map((name) => [name, { runtime: [], tests: [] }]));
  for (const base of ROOTS) {
    for (const file of sourceFiles(path.join(root, base))) {
      const relative = path.relative(root, file);
      if (relative === 'scripts/postgres-docs.mjs') continue;
      const text = readFileSync(file, 'utf8');
      for (const [name, pattern] of patterns) {
        if (pattern.test(text)) found[name][isTest(relative) ? 'tests' : 'runtime'].push(relative);
      }
    }
  }
  return found;
}

export function consumersMarkdown(found) {
  const lines = [
    '# Database consumers of the Postgres store',
    '',
    'Current source references, read by `pnpm postgres:consumers`.',
    'Every file whose SQL names each schema-qualified table or view.',
    'A keyword match, so a comment that reads like SQL can appear.',
    '',
  ];
  for (const [name, { runtime, tests }] of Object.entries(found)) {
    const files = (names) => (names.length ? names.map((f) => `\`${f}\``).join(', ') : 'none');
    lines.push(`## \`${name}\``, '', `Runtime (${runtime.length}): ${files(runtime)}`, '', `Tests (${tests.length}): ${files(tests)}`, '');
  }
  return `${lines.join('\n').trimEnd()}\n`;
}

/** The README with its matrix block replaced by `matrix`. */
export function withMatrix(readme, matrix) {
  const start = readme.indexOf(MATRIX_START);
  const end = readme.indexOf(MATRIX_END);
  if (start < 0 || end < start) throw new Error('db/postgres/README.md has no matrix markers');
  return `${readme.slice(0, start + MATRIX_START.length)}\n${matrix}\n${readme.slice(end)}`;
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  if (process.argv.includes('--consumers')) {
    process.stdout.write(consumersMarkdown(findConsumers()));
  } else {
    const model = JSON.parse(readFileSync(path.join(MODEL, 'model.json'), 'utf8'));
    const matrix = matrixMarkdown(model);
    if (process.argv.includes('--write')) {
      const readmePath = path.join(MODEL, 'README.md');
      writeFileSync(readmePath, withMatrix(readFileSync(readmePath, 'utf8'), matrix));
      const { PostgresUnavailable, withDisposablePostgres } = await import('./postgres-dev.mjs');
      const { applyMigrations } = await import('./postgres-migrate.mjs');
      try {
        const constraints = await withDisposablePostgres(async (dev) => {
          applyMigrations(dev);
          return constraintsMarkdown(readCatalog(dev.psql));
        });
        writeFileSync(CONSTRAINTS_PATH, constraints);
      } catch (error) {
        if (!(error instanceof PostgresUnavailable)) throw error;
        process.stderr.write(`wrote the README matrix; constraints.md needs a Postgres server: ${error.message}\n`);
        process.exitCode = 3;
      }
    } else {
      process.stdout.write(`${matrix}\n\n${consumersMarkdown(findConsumers())}`);
    }
  }
}
