// Generated by pnpm generate. Edit the sibling .mts source.
// The environment variables NoticeOS reads, by their NoticeOS names.
//
// Every variable the product itself defines is named NOTICEOS_*. An operator's
// shell may still set the name an earlier release read, and those keep
// working: the NoticeOS name wins when it is set, the legacy one is read when
// it is not. Writers (the runner, `pnpm start`, the container image) set only
// the NoticeOS names.
//
// The four bootstrap secrets (CREDENTIALS_KEY, OPERATOR_TOKEN, ASSET_TOKENS,
// DATABASE_URL) carry no product name and are not here; docs/06-operations.md
// § Bootstrap secrets names them.
//
// Authored TypeScript: `pnpm generate` writes the `.mjs` the runner, the
// scripts and the Tower's dev server import, and the `.d.mts` beside it.
export const PRODUCT_ENV = Object.freeze({
    /** The home folder the installation's state lives in (scripts/os-runtime.mjs). */
    home: Object.freeze({ name: "NOTICEOS_HOME" }),
    /** The installation's own folder (scripts/installation.mts). */
    installationDir: Object.freeze({ name: "NOTICEOS_INSTALLATION_DIR", legacy: "REINDEX_OS_INSTALLATION_DIR" }),
    /** Where both Worker configs are read from when an installation runs out of a folder of its own (`pnpm start`). */
    workerConfigRoot: Object.freeze({ name: "NOTICEOS_WORKER_CONFIG_ROOT", legacy: "REINDEX_OS_WORKER_CONFIG_ROOT" }),
    /** A second name for OPERATOR_TOKEN, read by the CLI imports after OPERATOR_TOKEN itself. */
    operatorToken: Object.freeze({ name: "NOTICEOS_OPERATOR_TOKEN", legacy: "REINDEX_OPERATOR_TOKEN" }),
    /** Server-selected workspace entry; never a VITE/client value. */
    workspaceProfile: Object.freeze({ name: "NOTICEOS_WORKSPACE_PROFILE" }),
    workspaceOrigin: Object.freeze({ name: "NOTICEOS_WORKSPACE_ORIGIN" }),
    workspaceDatabase: Object.freeze({ name: "NOTICEOS_WORKSPACE_DATABASE_URL" }),
    identityDatabase: Object.freeze({ name: "NOTICEOS_IDENTITY_DATABASE_URL" }),
    identitySecret: Object.freeze({ name: "NOTICEOS_IDENTITY_SESSION_SECRET" }),
    identityEdge: Object.freeze({ name: "NOTICEOS_IDENTITY_EDGE" }),
    identityEmailFrom: Object.freeze({ name: "NOTICEOS_IDENTITY_EMAIL_FROM" }),
    demoWorkspace: Object.freeze({ name: "NOTICEOS_DEMO_WORKSPACE_ID" }),
    demoActivityService: Object.freeze({ name: "NOTICEOS_DEMO_ACTIVITY_SERVICE_ID" }),
    demoScenarioHash: Object.freeze({ name: "NOTICEOS_DEMO_SCENARIO_HASH" }),
    /** The public demo operator's optional Statcounter project, `project:security`. */
    demoStatcounter: Object.freeze({ name: "NOTICEOS_DEMO_STATCOUNTER" }),
});
/** Authority is selected by server composition, never by a client or fallback.
 * Unlike ordinary optional settings, whitespace and absence are refused. */
export function workspaceProfile(env) {
    if (!env || typeof env !== 'object')
        throw new Error('Workspace profile is unavailable.');
    const selected = env[PRODUCT_ENV.workspaceProfile.name];
    if (selected !== 'standalone' && selected !== 'hosted' && selected !== 'demo') {
        throw new Error('Workspace profile is unavailable.');
    }
    return selected;
}
/**
 * The variable's value, trimmed: the NoticeOS name when it holds anything,
 * else the legacy name, else undefined. Blank counts as unset, the way every
 * reader of these variables already treated it.
 */
export function readProductEnv(env, variable) {
    const { name, legacy } = PRODUCT_ENV[variable];
    for (const key of [name, legacy]) {
        if (key === undefined)
            continue;
        const value = env?.[key];
        if (typeof value === "string" && value.trim() !== "")
            return value.trim();
    }
    return undefined;
}
