// Generated by pnpm generate. Edit the sibling .mts source.
export interface ProductEnvVariable {
    /** The name NoticeOS sets and reads first. */
    readonly name: string;
    /** The name an installation from before the rename may still set. */
    readonly legacy?: string;
}
export declare const PRODUCT_ENV: Readonly<{
    /** The home folder the installation's state lives in (scripts/os-runtime.mjs). */
    home: Readonly<{
        name: "NOTICEOS_HOME";
    }>;
    /** The installation's own folder (scripts/installation.mts). */
    installationDir: Readonly<{
        name: "NOTICEOS_INSTALLATION_DIR";
        legacy: "REINDEX_OS_INSTALLATION_DIR";
    }>;
    /** Where both Worker configs are read from when an installation runs out of a folder of its own (`pnpm start`). */
    workerConfigRoot: Readonly<{
        name: "NOTICEOS_WORKER_CONFIG_ROOT";
        legacy: "REINDEX_OS_WORKER_CONFIG_ROOT";
    }>;
    /** A second name for OPERATOR_TOKEN, read by the CLI imports after OPERATOR_TOKEN itself. */
    operatorToken: Readonly<{
        name: "NOTICEOS_OPERATOR_TOKEN";
        legacy: "REINDEX_OPERATOR_TOKEN";
    }>;
    /** Server-selected workspace entry; never a VITE/client value. */
    workspaceProfile: Readonly<{
        name: "NOTICEOS_WORKSPACE_PROFILE";
    }>;
    workspaceOrigin: Readonly<{
        name: "NOTICEOS_WORKSPACE_ORIGIN";
    }>;
    workspaceDatabase: Readonly<{
        name: "NOTICEOS_WORKSPACE_DATABASE_URL";
    }>;
    identityDatabase: Readonly<{
        name: "NOTICEOS_IDENTITY_DATABASE_URL";
    }>;
    identitySecret: Readonly<{
        name: "NOTICEOS_IDENTITY_SESSION_SECRET";
    }>;
    identityEdge: Readonly<{
        name: "NOTICEOS_IDENTITY_EDGE";
    }>;
    identityEmailFrom: Readonly<{
        name: "NOTICEOS_IDENTITY_EMAIL_FROM";
    }>;
    demoWorkspace: Readonly<{
        name: "NOTICEOS_DEMO_WORKSPACE_ID";
    }>;
    demoActivityService: Readonly<{
        name: "NOTICEOS_DEMO_ACTIVITY_SERVICE_ID";
    }>;
    demoScenarioHash: Readonly<{
        name: "NOTICEOS_DEMO_SCENARIO_HASH";
    }>;
    /** The public demo operator's optional Statcounter project, `project:security`. */
    demoStatcounter: Readonly<{
        name: "NOTICEOS_DEMO_STATCOUNTER";
    }>;
}>;
export type ProductEnvName = keyof typeof PRODUCT_ENV;
export type WorkspaceProfile = 'standalone' | 'hosted' | 'demo';
/** Authority is selected by server composition, never by a client or fallback.
 * Unlike ordinary optional settings, whitespace and absence are refused. */
export declare function workspaceProfile(env: object): WorkspaceProfile;
/**
 * The variable's value, trimmed: the NoticeOS name when it holds anything,
 * else the legacy name, else undefined. Blank counts as unset, the way every
 * reader of these variables already treated it.
 */
export declare function readProductEnv(env: Readonly<Record<string, string | undefined>> | undefined, variable: ProductEnvName): string | undefined;
