// Generated by pnpm config:generate. Edit the sibling .mts source.
/** The read-model MCP tools: what they are called, what
 * they answer and the arguments they take. The Tower Worker runs them
 * (apps/tower/worker/mcp-route.ts); the hosted MCP endpoint lists them with
 * the task tools (scripts/hosted-mcp.mts). One derivation for both. */
export interface ReadModelTool {
    readonly name: string;
    readonly description: string;
    readonly inputSchema: Readonly<Record<string, unknown>>;
}
export declare const READ_MODEL_TOOLS: readonly ReadModelTool[];
export declare const READ_MODEL_TOOL_NAMES: readonly string[];
