// Generated by pnpm config:generate. Edit the sibling .mts source.
import { type InstallationOptions } from './installation.mjs';
export declare const NEW_INSTALL_NAMES: Readonly<{
    /** The Tower's Worker (`name` in its Worker config). */
    towerWorker: "noticeos-tower";
    /** The ingest Worker, which the Tower reaches through its INGEST binding. */
    ingestWorker: "noticeos-ingest";
    /** The R2 bucket the ingest binds as RAW_SIGNALS. */
    rawSignalsBucket: "noticeos-raw-signals";
    /** The launchd label of the managed local service on a Mac. */
    serviceLabel: "com.noticeos.local";
    /** The Postgres database a new installation's store lives in. */
    postgresDatabase: "noticeos";
    /** The Postgres role the Workers connect as. */
    postgresRole: "noticeos_app";
}>;
/** The launchd label a service installed before the rename still carries
 * (docs/06-operations.md § Legacy names). */
export declare const LEGACY_RESOURCE_NAMES: Readonly<{
    serviceLabel: "com.reindexos.local";
}>;
/**
 * The names an installation's own store was made under, where they differ from
 * the checked-in Worker configs: its folder's `resource-names.json`. Absent keys
 * keep the configs' names.
 */
export interface ResourceNames {
    /** Ignored historical metadata, accepted so existing resource-name files still load. */
    database?: string;
    /** The R2 bucket bound as RAW_SIGNALS. Locally miniflare keeps the objects under this name. */
    rawSignalsBucket?: string;
}
/** Why `value` is not a resource-names document, or null. */
export declare function resourceNamesRefusal(value: unknown): string | null;
interface WorkerResources {
    r2_buckets?: {
        binding: string;
        bucket_name?: string;
    }[];
}
/**
 * Apply an installation's RAW_SIGNALS bucket name to a Worker config. In
 * place because that is how the Tower's Cloudflare plugin takes a change to a
 * config it read (a returned partial is merged, and its lists appended).
 */
export declare function applyResourceNames(config: WorkerResources, names: ResourceNames): void;
/**
 * The managed service's launchd label on this Mac: the label it was installed
 * under when a plist from before the rename is installed (only the operator
 * reinstalls it), else the NoticeOS label a new installation gets.
 */
export declare function serviceLabel(legacyPlistInstalled: boolean): string;
/**
 * The names this installation's store was made under (its folder's
 * resource-names.json), or `{}` when it has no such file and keeps the
 * checked-in names. A file that is there but unreadable throws, naming it:
 * running on the checked-in names instead would quietly open an empty bucket
 * beside the installation's archives.
 */
export declare function readResourceNames(options?: InstallationOptions): ResourceNames;
export {};
