// Generated by pnpm generate. Edit the sibling .mts source.
export interface ScheduledJob {
    id: string;
    surface: 'workflow' | 'system';
    label: string;
    group: string;
    cron: string;
    source?: string;
    keywords?: string[];
    local?: boolean;
    /** How System health's operations footer names this job's work, for a local
     * job an installation runs only once it is set up. */
    footer?: string;
    /** Steps of this job an operator can run now for chosen sites. */
    collectNow?: CollectNowStep[];
    /**
     * The integration connections whose Manage panel changes this collection's
     * schedule. A job several connections feed lists each, and its one schedule
     * shows in each panel under the job's own label. A collection with none
     * (nightly reports, live counters, local research) is changed in Settings →
     * Data collection.
     */
    connections?: string[];
}
/**
 * One step of a scheduled job, run now for chosen sites.
 *
 * The connect panel's Start collecting runs a provider's first collection at
 * once instead of at the job's next tick. It is not a second collector: the
 * ingest's dispatch (workers/ingest/src/dispatch.ts `runCollectNow`) runs this
 * same job step, on the same stored config, through the lane's own egress
 * gate, lease and budget gate, and refuses while the job is paused. `step` is
 * the dispatch's own step id for that lane (its workflow trace names it), and
 * `metered` marks a step that spends money, which the panel previews first.
 * A provider appears on at most one job.
 */
export interface CollectNowStep {
    provider: string;
    step: string;
    metered?: boolean;
}
export interface JobSchedule {
    enabled: boolean;
    cron: string;
    timezone?: string;
}
export type ScheduleOverrides = Record<string, JobSchedule>;
/**
 * Why the runner's last read of the saved schedules failed, as a state the
 * Tower renders rather than a sentence it would have to print: `held` — the
 * schedules armed before stay in effect and new changes
 * wait; `waiting` — nothing was ever armed, so every job waits for the settings
 * service. A status file written before the codes carries a sentence here; a
 * reader treats any other non-null value as `held`, which is what it meant.
 */
export type ScheduleReadFailure = 'held' | 'waiting';
export declare const SCHEDULES_HELD: ScheduleReadFailure;
export declare const SCHEDULES_WAITING: ScheduleReadFailure;
export interface ScheduleStatus {
    updatedAt: string;
    sessionId?: string;
    error: ScheduleReadFailure | string | null;
    jobs: {
        id: string;
        enabled: boolean;
        cron: string;
        timezone?: string;
        nextRun: string | null;
    }[];
    /**
     * Whether this installation runs the host's own lanes (the jobs marked
     * `local`). An installation `pnpm start` runs does not: it runs only the
     * `local` jobs it lists in `jobs`, each once set up, and the Tower lists
     * those beside the ingest's. Absent: it runs them all.
     */
    hostLanes?: boolean;
    /** Hosted composition executes only the jobs its deployment registered. */
    onlyListedJobs?: boolean;
    /** Deployment registry, available even before the first settings read. */
    registeredJobs?: readonly string[];
}
export declare const SCHEDULES_FILE = "config/constants.json";
export declare const SCHEDULES_POINTER = "/schedules";
export declare const SCHEDULE_STATUS_FILE: string;
export declare const WORKFLOW_GROUPS: {
    label: string;
}[];
export declare const SCHEDULED_JOBS: ScheduledJob[];
/**
 * The job one scheduled fire names. A job the ingest runs
 * (not `local`) is fired by its `cron`, the dispatch key: the runner fires that
 * key whatever time the operator saved, and the deployed Worker's triggers are
 * these keys (workers/ingest/wrangler.jsonc, pinned by
 * workers/ingest/test/crons.test.ts). Null for any other expression, which the
 * dispatch refuses as `unknown_cron` rather than guess at.
 */
export declare function ingestJobForCron(cron: string): ScheduledJob | null;
/** The job step that collects `provider` now, or null when none does. */
export declare function collectNowStep(provider: string): {
    job: ScheduledJob;
    step: CollectNowStep;
} | null;
export declare function scheduleFor(job: ScheduledJob, overrides?: ScheduleOverrides): JobSchedule;
export declare function scheduleTimezone(schedule: Pick<JobSchedule, 'timezone'>): string;
export declare function scheduleCronRefusal(cron: unknown): string | null;
/**
 * The longest wait between two runs of a schedule the editor offers, in
 * minutes: what a surface ages a job's newest reading against. Every
 * minute of one week is tried, so a list reads as its widest gap —
 * `10,30,50 * * * *` waits 20 minutes, a daily run 1440, a weekly one 10080.
 * Null for an expression the editor does not offer.
 */
export declare function cronIntervalMinutes(cron: string): number | null;
export declare function schedulesRefusal(value: unknown): string | null;
export declare function schedulesOpRefusal(op: {
    file?: string;
    pointer?: string;
    kind: string;
    value?: unknown;
}): string | null;
export declare function jobRunName(job: ScheduledJob): string;
