#!/usr/bin/env node
// THE COMMAND INDEX, GENERATED FROM package.json AND EACH SCRIPT'S OWN HEADER.
//
// `package.json` `scripts` is the one list of commands this repo offers, and
// the first comment line of each script file is its one-line description. A
// hand-kept table of the same facts drifts the day a script is added or
// renamed, so scripts/README.md carries this index between two markers and
// `pnpm scripts:index --check` (run by scripts/scripts-index.test.mjs) fails
// when the committed block no longer matches what the code says.
//
//   node scripts/scripts-index.mjs            print the index
//   node scripts/scripts-index.mjs --write    rewrite the block in scripts/README.md
//   node scripts/scripts-index.mjs --check    exit 1 when the block is stale

import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

export const REPO_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
export const README = 'scripts/README.md';
export const START = '<!-- scripts-index:start -->';
export const END = '<!-- scripts-index:end -->';

/** The script file a package command runs, repo-relative, or null for a composite command. */
export function scriptFile(command) {
  const match = /(?:^|\s)node\s+(?:--[^\s]+\s+)*((?:scripts|apps\/tower\/e2e)\/[\w./-]+\.mjs)\b/u.exec(command);
  return match?.[1] ?? null;
}

/** The authored source of a script: the `.mts` beside a generated `.mjs`, else the file itself. */
export function authoredSource(root, file) {
  const authored = file.replace(/\.mjs$/u, '.mts');
  return existsSync(path.join(root, authored)) ? authored : file;
}

/** The first line of a script's header comment, as one sentence without the file's own name. */
export function headerLine(source, file) {
  const lines = source.split('\n');
  let index = 0;
  if (lines[0]?.startsWith('#!')) index = 1;
  for (; index < lines.length; index += 1) {
    const line = lines[index].trim();
    if (!line) continue;
    const text = line.replace(/^\/\/\s?/u, '').replace(/^\/\*\*?\s?/u, '').replace(/^\*\s?/u, '').replace(/\*\/\s*$/u, '').trim();
    if (!text || text.startsWith('import ') || text.startsWith('export ') || text.startsWith('const ')) break;
    const base = path.basename(file).replace(/\.(?:mjs|mts)$/u, '');
    return text.replace(new RegExp(`^${base.replace(/[.*+?^${}()|[\]\\]/gu, '\\$&')}\\.(?:mjs|mts)\\s*[—:-]\\s*`, 'u'), '').replace(/\s+$/u, '');
  }
  return '';
}

/** One row per package script: name, command, the script's own one line. */
export function indexRows(root = REPO_ROOT) {
  const manifest = JSON.parse(readFileSync(path.join(root, 'package.json'), 'utf8'));
  return Object.entries(manifest.scripts ?? {}).map(([name, command]) => {
    const file = scriptFile(command);
    let description = '';
    if (file) {
      const source = authoredSource(root, file);
      description = existsSync(path.join(root, source)) ? headerLine(readFileSync(path.join(root, source), 'utf8'), source) : '(missing file)';
    }
    return { name, command, file, description };
  });
}

const cell = (text) => text.replace(/\|/gu, '\\|').replace(/\s+/gu, ' ').trim();

export function renderIndex(rows) {
  const lines = [
    START,
    '',
    '| `pnpm …` | Runs | The script\'s own first line |',
    '|---|---|---|',
    ...rows.map(({ name, command, file, description }) => {
      const runs = file ? `${file}${command.slice(command.indexOf(file) + file.length).trimEnd()}` : `${cell(command).slice(0, 80)}${command.length > 80 ? '…' : ''}`;
      return `| \`${name}\` | \`${cell(runs)}\` | ${cell(description) || '—'} |`;
    }),
    '',
    `Generated by \`pnpm scripts:index -- --write\` from \`package.json\` and each script's header; \`scripts/scripts-index.test.mjs\` fails when this block is stale.`,
    '',
    END,
  ];
  return lines.join('\n');
}

export function currentBlock(readme) {
  const start = readme.indexOf(START);
  const end = readme.indexOf(END);
  if (start < 0 || end < 0 || end < start) return null;
  return readme.slice(start, end + END.length);
}

export function withBlock(readme, block) {
  const current = currentBlock(readme);
  if (current) return readme.replace(current, block);
  // No markers yet: the index goes before the first section heading.
  const at = readme.search(/^# /mu);
  return at < 0 ? `${readme.trimEnd()}\n\n${block}\n` : `${readme.slice(0, at)}${block}\n\n${readme.slice(at)}`;
}

export function main(argv = process.argv.slice(2), root = REPO_ROOT) {
  const block = renderIndex(indexRows(root));
  const file = path.join(root, README);
  const readme = readFileSync(file, 'utf8');
  if (argv.includes('--write')) {
    writeFileSync(file, withBlock(readme, block));
    return 0;
  }
  if (argv.includes('--check')) {
    if (currentBlock(readme) === block) return 0;
    process.stderr.write(`${README}: the command index is stale; run pnpm scripts:index -- --write\n`);
    return 1;
  }
  process.stdout.write(`${block}\n`);
  return 0;
}

const invoked = process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (invoked) process.exitCode = main();
