// Generated by pnpm generate. Edit the sibling .mts source.
import type { SourceVersion } from '../apps/tower/shared/source-version.js';
/** Git is optional, bounded and local. A parent repository is never this source. */
export declare function gitSourceVersion(root: string, { declared }?: {
    declared?: boolean;
}): SourceVersion | null;
/** An image's sealed manifest wins over any checkout beside it. */
export declare function sourceVersion(root: string): SourceVersion | null;
