// Generated by pnpm generate. Edit the sibling .mts source.
export interface TaskProject {
    asset: string;
    prefix: string;
    database: string | null;
    repo: string;
    unavailableReason?: string;
}
export interface TaskProjectReadOptions {
    repoRoot?: string;
    door?: string;
    token?: string;
    fetchImpl?: typeof fetch;
    readHost?: () => Promise<string>;
}
/** The host's task repository links for the checkout at `repoRoot`: this
 * installation's `task-host.json`, else the product's empty default. The home
 * checkout for the live runner and its lanes. */
export declare function taskHostFile(repoRoot?: string): string;
/** Canonical physical database identifier for backup, poll and drift readers. */
export declare function beadsDatabaseName(value: unknown): string | null;
/** Resolve saved logical rows only against repositories explicitly linked on
 * this host. A stored repo/hub value never grants local filesystem access. */
export declare function resolveTaskProjects(stored: unknown, host: unknown): TaskProject[];
/**
 * The host's repository links. `absentLinksNone`: no inventory file at all
 * links nothing — a folder `pnpm start` made is not a checkout and has neither
 * its own copy nor the product's default, so its task
 * screens say a project has no checkout linked instead of failing on a missing
 * file. Without it a missing file throws: the managed host's backup must not
 * read a lost inventory as an empty one.
 */
export declare function readTaskHost({ repoRoot, readHost, absentLinksNone }?: Pick<TaskProjectReadOptions, 'repoRoot' | 'readHost'> & {
    absentLinksNone?: boolean;
}): Promise<{
    repositories: unknown[];
}>;
export declare function readTaskProjects({ repoRoot, readHost, ...storeOptions }?: TaskProjectReadOptions): Promise<TaskProject[]>;
/** The runner's existing parsers consume one JSON map; host topology is absent. */
export declare function readTaskProjectConfig(options?: TaskProjectReadOptions): Promise<string>;
