// Generated by pnpm config:generate. Edit the sibling .mts source.
import type { LiveTask, LiveEpic, TaskComment } from "../apps/tower/shared/tasks";
declare function text(value: unknown, fallback?: string): string;
export declare function toLiveTask(row: unknown, ready: ReadonlySet<string>): LiveTask;
export declare function toEpic(row: unknown): LiveEpic | null;
export declare function toComment(row: unknown): TaskComment;
export { text as taskRowText };
