// Generated by pnpm generate. Edit the sibling .mts source.
/** The parts of a Vite dependency optimizer read here. */
export interface OptimizerLike {
    /** Set while the first run scans the project for dependencies. */
    readonly scanProcessing?: Promise<void> | undefined;
    /** Each dependency found and not yet bundled carries its bundle's promise. */
    readonly metadata: {
        readonly discovered: Readonly<Record<string, {
            readonly processing?: Promise<void> | undefined;
        }>>;
    };
}
/** The parts of a Vite dev server read and replaced here. */
export interface TestViteServerLike {
    readonly environments: Readonly<Record<string, {
        readonly depsOptimizer?: OptimizerLike | undefined;
    } | undefined>>;
    close(): Promise<void>;
}
/** The parts of a Vite inline config written here. */
export interface TestViteConfigLike {
    cacheDir?: string;
    plugins?: readonly unknown[];
    server?: object;
}
/** The parts of a Vite plugin this module writes. */
export interface OptimizerOffPlugin {
    readonly name: string;
    readonly enforce: 'post';
    configEnvironment(name: string, options: {
        optimizeDeps?: Record<string, unknown>;
    }): void;
}
/** What `createTestViteServer` needs besides the config. */
export interface TestViteServerOptions {
    /** Whether a browser loads pages from it: only then does it run the dependency optimizer. */
    pages: boolean;
    /** How long a close waits for the optimizer before closing anyway. */
    optimizerTimeoutMs?: number;
}
/** The prefix of every test server's cache folder in the OS temp dir. */
export declare const TEST_VITE_CACHE_PREFIX: string;
/** How long a close waits for the optimizer by default: a cold bundle of the Tower's dependencies on a loaded host. */
export declare const OPTIMIZER_TIMEOUT_MS: number;
/**
 * The client environment's dependency optimizer, off. A plugin rather than
 * `optimizeDeps` in the inline config because Vite merges `include` lists and
 * the React plugin adds to it: only an empty list, set last, turns it off.
 */
export declare function optimizerOff(): OptimizerOffPlugin;
/** The optimizer work a server still has in flight: a scan, or a bundle some dependency waits on. */
export declare function optimizerWork(server: TestViteServerLike): Promise<void>[];
/**
 * Resolves true once no optimizer work is in flight, or false when `timeoutMs`
 * passes first. A finished run can leave its settled promise on a dependency,
 * so a promise counts once it has settled, and each pass looks again for work
 * a run started meanwhile.
 */
export declare function optimizerIdle(server: TestViteServerLike, timeoutMs?: number): Promise<boolean>;
/**
 * A new cache folder in `parent` for this process, removed when it exits. A
 * folder whose process is gone (killed before its exit handler ran) is removed
 * by the next one made; a live process's folder is never touched.
 */
export declare function testViteCacheDir(parent?: string): string;
/** `config` as a test server starts it: its own cache, no watcher, and no optimizer unless pages load. */
export declare function testViteConfig<C extends TestViteConfigLike>(config: C, options: Pick<TestViteServerOptions, 'pages'>): C;
/** Makes every close of `server`, Vite's own on SIGTERM included, wait for its optimizer first. */
export declare function closeAfterOptimizer<S extends TestViteServerLike>(server: S, timeoutMs?: number): S;
/** A Vite dev server a test starts: see the top of this file. */
export declare function createTestViteServer<C extends TestViteConfigLike, S extends TestViteServerLike>(createServer: (config?: C) => Promise<S>, config: NoInfer<C>, options: TestViteServerOptions): Promise<S>;
