// Generated by pnpm generate. Edit the sibling .mts source.
/** The variable that overrides the worker count. */
export declare const UNIT_TEST_WORKERS_ENV: string;
/** Half the cores per suite: the two suites together use them all once. */
export declare const DEFAULT_UNIT_TEST_WORKERS: string;
/** Vitest's `maxWorkers` for one unit suite. */
export declare function unitTestWorkers(env?: Readonly<Record<string, string | undefined>>): string | number;
