// Generated by pnpm config:generate. Edit the sibling .mts source.
export interface WallFitBox {
    top: number;
    bottom: number;
    left: number;
    right: number;
    width: number;
    height: number;
}
export interface WallFitOffender {
    kind: string;
    el: string;
    by: number;
    right?: number;
    bottom?: number;
    text: string;
}
export interface WallFitLeak {
    el: string;
    axis: "x" | "y";
    delta: number;
    text: string;
}
export interface WallFitMeasurement {
    viewport: {
        width: number;
        height: number;
    };
    tvMediaQuery: boolean;
    /** Which Wall the screen drew (`wallScreen`): the TV's layout or the
     * one-column stack, and the TV layout's scale — 1 on the TV, about 0.77 on
     * a 13-inch laptop. */
    layout: string | null;
    scale: number;
    rootClipped: boolean;
    /** How far content reaches, clip or no clip. */
    content: {
        right: number;
        bottom: number;
    };
    /** The furthest edge anything actually paints. */
    tight: {
        right: number;
        bottom: number;
    };
    worst: {
        x: WallFitOffender | null;
        y: WallFitOffender | null;
    };
    offenders: {
        x: WallFitOffender[];
        y: WallFitOffender[];
    };
    ink: WallFitLeak[];
    clipped: WallFitLeak[];
    /** The regions, where the Wall draws them. */
    regions: Record<"strip" | "revenue" | "needs" | "sites" | "feed", WallFitBox | null>;
    /** The site region: its tier, each row's height, and the height left under
     * the last row (null in the one-site tier, which draws tiles, not rows). */
    sites: {
        density: string | null;
        rows: {
            id: string;
            height: number;
        }[];
        spare: number | null;
    };
    /** The feed: rows drawn, and whether the lowest one ends inside the column. */
    feed: {
        shown: number;
        lastRowWhole: boolean | null;
    };
    counts: {
        elements: number;
        overX: number;
        overY: number;
        ink: number;
        clipped: number;
    };
}
export declare function measureWallFit(): WallFitMeasurement | {
    error: string;
};
export interface WallFitVerdict {
    /** Nothing reaches past the viewport on either axis. */
    fits: boolean;
    overWidth: number;
    overHeight: number;
    /** `--strict`: also nothing painting outside its own box, and no text cut off. */
    clean: boolean;
}
/** The one reading of a measurement both the fit tool and the journeys use. */
export declare function wallFitVerdict(measured: WallFitMeasurement): WallFitVerdict;
