// Generated by pnpm config:generate. Edit the sibling .mts source.
export declare const WALL_LAYOUT_VERSION = 1;
/** JSON pointer inside `config/tower.json` that holds the `WallConfig`. */
export declare const WALL_LAYOUT_POINTER = "/wall";
/** Versions kept beside the current layout; the oldest falls off. */
export declare const WALL_LAYOUT_HISTORY_MAX: number;
export declare const WALL_MAX_ROWS: number;
export declare const WALL_MAX_WIDGETS_PER_ROW: number;
/** `width` bounds, in grid fractions. A quarter is the narrowest anything on a
 * TV can still be read from across a room; twelve is wider than any row. */
export declare const WALL_WIDTH_MIN: number;
export declare const WALL_WIDTH_MAX: number;
export declare const WALL_WIDTH_STEP: number;
/** The TV the Wall is fitted to (`scripts/wall-fit-check.mjs`). */
export declare const WALL_TV_WIDTH: number;
export declare const WALL_TV_HEIGHT: number;
/** D28's widgets (docs/25-the-wall.md, epic `ro-trai`), in reading order. */
export declare const WALL_WIDGET_TYPES: readonly ["strip", "revenue", "needs", "sites", "feed"];
export type WallWidgetType = (typeof WALL_WIDGET_TYPES)[number];
/** The widgets D28 took off the Wall (bead `ro-trai.11`). A saved layout may
 * still name them; see the header's RETIRED WIDGETS. */
export declare const RETIRED_WALL_WIDGET_TYPES: readonly ["attention", "portfolio", "system", "clock", "countdown", "meetings", "assets"];
/** The settings a widget MAY carry. Each key is applied by the renderer for
 * every type whose spec lists it, and refused by the validator elsewhere. */
export interface WallWidgetSettings {
    /** Only these asset ids, in the layout's own order; absent means every asset. */
    assets?: string[];
    /** Selected pulse totals per asset. Absent uses its configured totals; [] hides them. */
    pulseMetrics?: Record<string, string[]>;
}
export type WallSettingKey = keyof WallWidgetSettings;
export interface WallWidgetSpec {
    type: WallWidgetType;
    /** Operator-facing name — doc 17 words, the same the desk uses. */
    label: string;
    /** What the widget shows, as the library panel's facets — two to five
     * nouns, never a sentence (bead `ro-ujb9.96.6.17`): the name says what it
     * is, the facets what is on it, and the live preview beside the library
     * shows it the moment it is added. */
    shows: readonly string[];
    /** The weight a freshly added widget gets. */
    defaultWidth: number;
    /** The track floor the renderer applies (`minmax(<rem>, <width>fr)`); 0 = none. */
    minWidthRem: number;
    /**
     * The widest its track may grow; null = none. A capped widget's track is its
     * share of the row by weight, between its floor and this cap, and the
     * widgets beside it take the rest (bead `ro-trai.31`): the feed is a column
     * of lines, and a line longer than a glance is a column that took width the
     * site rows needed.
     */
    maxWidthRem: number | null;
    /** At most one per layout — the fact it shows is portfolio-wide. */
    unique: boolean;
    /** Belongs in the row that takes the remaining screen height. */
    prefersFill: boolean;
    /**
     * Its place in the one column the Wall becomes on a portrait tablet or a
     * phone (operator 2026-09-23, beads `ro-trai.24`, `ro-trai.29`,
     * `ro-trai.31`, docs/25-the-wall.md § Laptop, tablet and phone): the strip,
     * revenue, the site rows, Needs you, the feed. The sites come before Needs
     * you and the feed because their numbers are what changes and what shows
     * the state of the business. By type, so any saved layout reads the same.
     */
    stackOrder: number;
    /** Renders nothing — and yields its track — when it has nothing to show,
     * exactly as the countdown and meetings do today (bead `ro-py40`): an empty
     * track is a hole on the Wall for a feature nobody set up. */
    hidesWhenEmpty: boolean;
    /** The settings keys this widget honours. */
    settings: readonly WallSettingKey[];
    /** Where this widget's OWN configuration lives when it is not a widget
     * setting — the editor's panel renders that form instead of fields. */
    configuredAt?: string;
}
export interface WallWidget {
    /** Stable within the layout; the editor's selection and the renderer's key. */
    id: string;
    type: WallWidgetType;
    /** Grid fraction — see the header above. */
    width: number;
    settings?: WallWidgetSettings;
}
/**
 * A slot that stacks rows of widgets inside a row (bead `ro-trai.2`,
 * docs/25-the-wall.md § Regions), so one widget can run the full height beside
 * several: D28's live feed beside the revenue band and the site rows. It sits
 * in its row's `widgets` like a widget and takes a width like one.
 *
 * ONE LEVEL DEEP. A column holds rows of widgets and never another column —
 * the types say so and the validator refuses it — because a Wall arranged from
 * across a room needs a layout an operator can picture, and two levels already
 * express every region doc 25 names.
 */
export interface WallColumn {
    /** Shares the widget id space: the editor selects and keys it the same way. */
    id: string;
    type: 'column';
    /** Grid fraction of its row, exactly as a widget's. */
    width: number;
    /** Stacked top to bottom; at most one takes the column's remaining height. */
    rows: WallColumnRow[];
}
/** A row inside a column: widgets side by side, never another column. */
export interface WallColumnRow {
    id: string;
    /** `fill` takes the height the column's other rows leave. */
    height: 'auto' | 'fill';
    widgets: WallWidget[];
}
/** What a row holds, left to right: widgets, and at most depth-1 columns. */
export type WallSlot = WallWidget | WallColumn;
export interface WallRow {
    id: string;
    /** `fill` takes the height the other rows leave; at most one row may. */
    height: 'auto' | 'fill';
    widgets: WallSlot[];
}
export interface WallLayout {
    version: typeof WALL_LAYOUT_VERSION;
    rows: WallRow[];
}
/** One saved layout the current one replaced. */
export interface WallLayoutVersion {
    /** ISO-8601 instant of the save that retired it. */
    savedAt: string;
    /** The operator's own words at Save; the editor requires one. */
    reason: string;
    layout: WallLayout;
}
export interface WallConfig {
    layout: WallLayout;
    /** Newest first, capped at `WALL_LAYOUT_HISTORY_MAX`. */
    history: WallLayoutVersion[];
    /** Present only when the saved `/wall` names a retired widget. Read-side
     * only: `parseWallConfig` sets it and every write door refuses it. */
    retired?: WallRetired;
}
/** What `parseWallConfig` did with a saved `/wall` that names a widget D28
 * took off the Wall (bead `ro-trai.11`). */
export interface WallRetired {
    /** The `/wall` value exactly as saved. The editor's Save is guarded by it,
     * because the guard compares against the store, not against the default
     * drawn in its place. */
    saved: unknown;
    /** The saved current layout named one, so the Wall draws the default. False
     * when only older versions did; those are left out of the history. */
    replaced: boolean;
}
export type WallLayoutCheck = {
    ok: true;
    layout: WallLayout;
} | {
    ok: false;
    reason: string;
};
export declare const WALL_WIDGET_LIBRARY: Readonly<Record<WallWidgetType, WallWidgetSpec>>;
export declare function wallWidgetSpec(type: WallWidgetType): WallWidgetSpec;
/** A slot that is a column rather than a widget. */
export declare function isWallColumn(slot: WallSlot): slot is WallColumn;
/** One row of the layout wherever it sits. */
export interface WallRowPlace {
    row: WallRow | WallColumnRow;
    /** Its index among its siblings: the layout's rows, or its column's rows. */
    index: number;
    /** The column holding it and the top-level row holding that; null at the top. */
    column: WallColumn | null;
    parent: WallRow | null;
}
/** Every row in reading order: each top-level row, then its columns' rows. */
export declare function wallRowPlaces(layout: WallLayout): WallRowPlace[];
/** Every widget on the Wall, columns' included, in reading order. */
export declare function wallLayoutWidgets(layout: WallLayout): WallWidget[];
/**
 * D28's Wall (docs/25-the-wall.md § Regions, bead `ro-trai.11`): the strip on
 * top; below it a column — revenue beside Needs you, then the site rows taking
 * the rest — beside the live feed, which runs the body's full height. The
 * weights are the budget's (column ≈1,390 px to the feed's 440 px at 1920).
 */
export declare const DEFAULT_WALL_LAYOUT: WallLayout;
export declare const EMPTY_WALL_CONFIG: WallConfig;
/**
 * Does this saved layout name a widget D28 took off the Wall? Read off the raw
 * value, before validation, because the answer decides whether it is validated
 * at all: a retired widget is drawn as the default, never refused.
 */
export declare function wallLayoutNamesRetired(value: unknown): boolean;
/** A width the editor can produce: inside the bounds, on the step grid. */
export declare function isWallWidth(value: unknown): value is number;
/**
 * The one rule for "can the Wall draw this". Returns the layout NORMALISED —
 * widths rounded onto the step grid, settings without unknown keys — so the
 * value the lane writes is the value the validator accepted.
 *
 * Reasons are operator sentences: the editor prints them under Save and every
 * write door returns them as the refusal, so the operator reads the same words
 * in the browser and in the terminal (doc 15 principle 2).
 */
export declare function validateWallLayout(value: unknown): WallLayoutCheck;
/**
 * Non-blocking observations the editor shows beside Save. A layout can be
 * drawn and still be a poor Wall; these name the state, in the operator's
 * words, and leave the decision with them (it is their TV).
 *
 * STATES, NOT SENTENCES (bead `ro-ujb9.96.6.17`). Each is what the TV will
 * look like — the editor draws it as a caution chip — and the fix is a control
 * already beside it: every row carries its own "Remaining height" toggle, and
 * the library its Add. The "so the bottom of the TV will be empty" clauses
 * restated the state they followed.
 */
export declare function wallLayoutWarnings(layout: WallLayout): string[];
/** The editor's one warning for a saved layout that named a retired widget:
 * the state the TV is in, as a chip beside Save (bead `ro-trai.11`). */
export declare const WALL_RETIRED_WARNING = "Old layout retired, new default shown";
/** Read `/wall` out of a parsed `config/tower.json`. Absent → the default;
 * present but undrawable → throws with the validator's own sentence, so a bad
 * file fails the build the way a bad countdown does (`parseDashboardConfig`).
 *
 * A layout naming a widget D28 retired is the one exception (bead
 * `ro-trai.11`): the current layout becomes the default, an older version
 * naming one leaves the history (it could only be reverted to the default),
 * and `retired` keeps the value as saved for the editor's Save guard. */
export declare function parseWallConfig(value: unknown): WallConfig;
/** True when two layouts would draw the same Wall. */
export declare function sameWallLayout(a: WallLayout, b: WallLayout): boolean;
/**
 * The `WallConfig` a Save produces: the new layout becomes current and the one
 * it replaces goes to the top of the history with the operator's reason. Saving
 * an identical layout is not a version — the editor should not offer it.
 */
export declare function withSavedWallLayout(config: WallConfig, layout: WallLayout, reason: string, savedAt: string): WallConfig;
/**
 * Revert is a Save whose layout is an older version — the current layout is
 * retired into the history like any other, so a revert can itself be undone
 * (doc 15 principle 5). The reverted entry stays in the history: it is a
 * record of what the Wall showed, not a stack to pop.
 */
export declare function withRevertedWallLayout(config: WallConfig, historyIndex: number, savedAt: string): WallConfig;
/** A widget id no other widget or column in the layout uses — `<type>`, then
 * `<type>-2`… */
export declare function nextWallWidgetId(layout: WallLayout, type: WallWidgetType | 'column'): string;
/** A row id no other row uses, a column's rows included. */
export declare function nextWallRowId(layout: WallLayout): string;
/**
 * The refusal a changeset's `/wall` ops earn, or `null` (bead `ro-lzmq.3`).
 *
 * THIS IS THE RULE AT EVERY DOOR. `validateSchemaAndSafety` calls it, so the
 * terminal (`pnpm config:apply`), the Worker's `PUT /api/config`, the ingest's
 * `applyConfigOps` and the dev write lane all refuse the same layout in the same
 * words — and `parseWallConfig` fails the build on one that arrived any other
 * way. It was written at ONE of those doors until today, which meant a
 * hand-written changeset applied in a terminal committed a layout the television
 * could not draw and nothing noticed until the next build.
 *
 * A layout is written WHOLE, at `/wall` or `/wall/layout`. A pointer inside one
 * is refused, because a row or a width lifted out of its document cannot be
 * judged on its own and the answer must never be "probably fine".
 */
export declare function wallOpRefusal(op: unknown, at: string): string | null;
