// Generated by pnpm config:generate. Edit the sibling .mts source.
import type { WorkflowStepOutput } from '../packages/contract/src/workflows.js';
/**
 * How many sites a step could not read, when every item of its `failed` list
 * is a site whose remote the unpublished-commit check could not read (bead
 * ro-ujb9.233); otherwise null. The step summary names those as sites, since
 * nothing was collected from them.
 */
export declare function unreadSiteCount(value: unknown): number | null;
export declare function captureWorkflowOutput(value: unknown): WorkflowStepOutput | undefined;
export declare function isWorkflowStepOutput(value: unknown): value is WorkflowStepOutput;
