// Generated by pnpm generate. Edit the sibling .mts source.
import type { WorkflowStepRun } from '../packages/contract/src/workflows.js';
type StepVerdict = Pick<WorkflowStepRun, 'state' | 'summary'>;
export declare function stepResult(result: unknown): StepVerdict;
export declare function workflowResult(steps: WorkflowStepRun[], outcome: string): 'failed' | 'skipped' | 'succeeded';
/** Return only after every started branch has supplied its terminal evidence. */
export declare function settleWorkflowSteps(promises: Promise<unknown>[]): Promise<void>;
export interface WorkflowRecorder {
    steps: WorkflowStepRun[];
    run<T>(id: string, fn: () => Promise<T>, assess?: (result: T) => StepVerdict): Promise<T>;
}
/**
 * `failed` hears each step's own error as it is recorded, so the caller can
 * write it where "Check the service logs" sends the operator. The recorder
 * itself still does no I/O and keeps no error.
 */
export declare function createWorkflowRecorder({ now, changed, failed }?: {
    now?: () => number;
    changed?: (steps: WorkflowStepRun[]) => void;
    failed?: (id: string, error: unknown) => void;
}): WorkflowRecorder;
export {};
