// Generated by pnpm config:generate. Edit the sibling .mts source.
/** The two Worker configs, at the same relative paths in every folder as in the checkout. */
export declare const WORKER_CONFIGS: readonly string[];
/**
 * Two wrangler switches that let the shell choose a Worker's local secrets: an
 * environment (`.dev.vars.<environment>`), and every process variable as a
 * binding.
 */
export declare const WRANGLER_SECRET_SWITCHES: readonly string[];
/** Wrangler's documented switch for the `.env` read; "false" also skips the process read. */
export declare const WRANGLER_DOT_ENV_SWITCH: string;
/** The checkout's Worker config with every path made absolute, so it works from any folder. */
export declare function relocatedWorkerConfig(sourceText: string, sourceFile: string): Record<string, unknown>;
/**
 * A Worker config for `pnpm start`'s folder, with its one-line header. Its
 * resources keep the checked-in names, which are a new installation's
 * (scripts/resource-names.mts NEW_INSTALL_NAMES, scripts/new-install-names.test.mjs).
 */
export declare function workerConfig(sourceText: string, sourceFile: string): string;
export interface SecretFreeWorkerConfigs {
    /** The new folder: the configs and nothing else, so no `.dev.vars` and no `.env`. */
    root: string;
    /** Where the config at this checkout path was written. */
    configPath(relative: string): string;
    /** Deletes the folder. */
    remove(): void;
}
/** The checkout's Worker configs, written into a new, empty folder for a test run. */
export declare function secretFreeWorkerConfigs({ checkout, parent, configs, }?: {
    checkout?: string;
    parent?: string;
    configs?: readonly string[];
}): SecretFreeWorkerConfigs;
/** Stops wrangler, in this process, reading local secrets from `.env` files or the process itself. */
export declare function stopLocalSecretReads(env?: Record<string, string | undefined>): void;
