// Generated by pnpm config:generate. Edit the sibling .mts source.
import type { WorkspaceAction } from './workspace-admission.mjs';
import type { RuleBacktestInput } from '../packages/contract/src/rule-backtest.js';
export { watchQueryHistoryRange } from '../packages/contract/src/watch-series.mjs';
export interface WorkspaceOperation {
    /** Classification only: neither caller authorization nor RPC argument,
     * asset-selector or workspace binding. Receivers retain those validators. */
    readonly kind: 'workspace' | 'protocol' | 'standalone-only' | 'public';
    readonly action: WorkspaceAction | null;
    readonly rpcMethods: readonly string[];
}
export declare class OperationRefused extends Error {
    name: string;
    constructor();
}
export declare const GOOGLE_INTEGRATION_START = "/api/integrations/google/oauth/start";
export declare const GOOGLE_INTEGRATION_CALLBACK = "/api/integrations/google/oauth/callback";
export declare const GOOGLE_INTEGRATION_PROPERTIES = "/api/integrations/google/properties";
export interface WatchQueryRead {
    readonly asset: string;
    readonly metric: string;
    readonly query: string;
}
/** One retained GSC query, never a caller-selected archive key or time window. */
export declare function watchQueryHistoryRequest(request: Request): WatchQueryRead | null;
export type AssetMutationMethod = 'createAsset' | 'readAssetState' | 'writeAssetColumn' | 'moveAsset' | 'createAnnotation';
export type AssetMutationRoute = {
    readonly kind: 'create';
} | {
    readonly kind: 'column';
    readonly asset: string;
} | {
    readonly kind: 'order';
    readonly asset: string;
} | {
    readonly kind: 'decision';
    readonly asset: string;
} | {
    readonly kind: 'annotation';
    readonly asset: string;
} | {
    readonly kind: 'flag';
    readonly number: number;
};
/** Fixed existing mutation routes. Protected watch registration is deliberately
 * absent; query/archive reads need their own reviewed entry. */
export declare function assetMutationRequest(request: Request): AssetMutationRoute | null;
/** Exact public envelope, bounded by the same catalog parser as other hosted
 * families. Ordinary writers retain field/domain validation and error results. */
export declare function assetMutationInput(request: Request): Promise<{
    readonly route: AssetMutationRoute;
    readonly body: Readonly<Record<string, unknown>>;
}>;
/** One fixed provider read, with no body or caller-selected discovery scope. */
export declare function isHostedGoogleDiscovery(request: Request): boolean;
export type LiveProviderRead = {
    readonly method: 'ga4Realtime' | 'calendarUpcoming';
} | {
    readonly method: 'siteName';
    readonly domain: string;
};
/** Fixed panel reads. Property/feed selection remains in the selected store;
 * only the existing public-page name lookup accepts a bounded domain. */
export declare function liveProviderReadRequest(request: Request): LiveProviderRead | null;
/** The existing connection-readiness family, not a general provider dispatcher.
 * Provider catalog validation remains with the ordinary route and receiver. */
export declare function connectionReadinessRequest(request: Request): {
    readonly provider: string;
    readonly method: 'discoverSites' | 'probeCredential';
} | null;
export type CredentialWriteMethod = 'putCredential' | 'deleteCredential' | 'setCredentialExpiry' | 'connectCredential' | 'putSiteToken';
export type ProviderCollectionMethod = 'collectNow' | 'syncMediavine';
/** These existing workflow effects have fixed paths and bounded asset inputs;
 * the original message, never a caller's lane/service claim, selects the edge. */
export declare function providerCollectionRequest(request: Request): {
    readonly provider: string;
    readonly method: ProviderCollectionMethod;
} | null;
type ProviderCollectionInput = {
    readonly method: 'collectNow';
    readonly input: {
        provider: string;
        assets: readonly string[];
    };
} | {
    readonly method: 'syncMediavine';
    readonly input: {
        asset: string;
        start?: string;
        end?: string;
    };
};
/** Snapshot exact public fields before any identity, credential or provider I/O.
 * Ordinary collectors retain their mapping, date, lease and budget validation. */
export declare function providerCollectionInput(request: Request): Promise<ProviderCollectionInput>;
/** Fixed existing credential operations; no provider, actor or action comes
 * from the body. Provider field rules remain in the ordinary credential store. */
export declare function credentialWriteRequest(request: Request): {
    readonly provider: string;
    readonly method: CredentialWriteMethod;
} | null;
type CredentialWriteInput = {
    readonly method: 'putCredential' | 'connectCredential';
    readonly input: {
        provider: string;
        fields: Record<string, string>;
    };
} | {
    readonly method: 'deleteCredential';
    readonly input: string;
} | {
    readonly method: 'setCredentialExpiry';
    readonly input: {
        provider: string;
        expiresAt: string | null;
    };
} | {
    readonly method: 'putSiteToken';
    readonly input: {
        provider: string;
        asset: string;
        token: string;
    };
};
/** A bounded snapshot of the original body, shared with the fixed receiver's
 * duplicate-argument check. Secrets are neither logged nor returned to HTTP. */
export declare function credentialWriteInput(request: Request): Promise<CredentialWriteInput>;
export interface GoogleCallbackInput {
    readonly state: string;
    readonly code: string | null;
    readonly error: string | null;
}
/** Fixed protocol grammar, not identity or authority. Consumers pass the real
 * original Request and their server-declared origin, never serialized results. */
export declare function googleOAuthRequest(request: Request, trustedOrigin: string, phase: 'start'): Promise<{
    readonly workspaceId: string;
}>;
export declare function googleOAuthRequest(request: Request, trustedOrigin: string, phase: 'callback'): GoogleCallbackInput;
/** Reviewed store-only dispatch. Provider, credential and native reads have
 * separate entry work even when the semantic catalog classifies them. */
export declare function isHostedStoredRead(request: Request): boolean;
export type StoredResearchRead = {
    readonly method: 'mcp';
    readonly body: Record<string, unknown>;
    readonly tool: string | null;
} | {
    readonly method: 'backtestRule';
    readonly input: RuleBacktestInput;
};
/** Only the existing stored tools and candidate-rule replay. No provider call,
 * arbitrary RPC, threshold write or request-selected authority is inferred. */
export declare function storedResearchReadRequest(request: Request): Promise<StoredResearchRead | null>;
/** Classify an actual Tower request; no request field selects an entry profile. */
export declare function towerOperation(request: Request): Promise<WorkspaceOperation>;
/** Receiver code supplies its fixed method. This never consumes a forwarded
 * classification. Fresh identity/admission is still required in this realm.
 * The receiver separately validates payload selectors against the admitted
 * workspace; matching this edge does not prove forwarded arguments intact.
 */
export declare function ingestOperation(method: string, originalRequest: Request): Promise<WorkspaceOperation>;
