// Generated by pnpm config:generate. Edit the sibling .mts source.
/** Shared workspace admission (ro-ujb9.289.8.3.2).
 * Server composition selects this entry and its fresh authority readers.
 * Request selectors, UUIDs, profile handles and identity facts are not authority.
 * Route mapping, identity protocols and operational capabilities live elsewhere.
 */
export type WorkspaceStatus = 'active' | 'provisioning' | 'suspended';
export type WorkspaceRole = 'owner' | 'operator' | 'viewer';
type Category = 'stored-read' | 'provider-read' | 'write' | 'human-decision' | 'membership' | 'protected';
declare const ACTIONS: Readonly<{
    'evidence.read': Readonly<{
        category: Category;
        demo: boolean;
    }>;
    'tasks.read': Readonly<{
        category: Category;
        demo: boolean;
    }>;
    'settings.read': Readonly<{
        category: Category;
        demo: boolean;
    }>;
    'workflows.read': Readonly<{
        category: Category;
        demo: boolean;
    }>;
    'integrations.summary.read': Readonly<{
        category: Category;
        demo: boolean;
    }>;
    'provider.read': Readonly<{
        category: Category;
        demo: boolean;
    }>;
    'assets.write': Readonly<{
        category: Category;
        demo: boolean;
    }>;
    'findings.write': Readonly<{
        category: Category;
        demo: boolean;
    }>;
    'annotations.write': Readonly<{
        category: Category;
        demo: boolean;
    }>;
    'tasks.write': Readonly<{
        category: Category;
        demo: boolean;
    }>;
    'tasks.decide': Readonly<{
        category: Category;
        demo: boolean;
    }>;
    'settings.write': Readonly<{
        category: Category;
        demo: boolean;
    }>;
    'integrations.write': Readonly<{
        category: Category;
        demo: boolean;
    }>;
    'workflows.run': Readonly<{
        category: Category;
        demo: boolean;
    }>;
    'memberships.manage': Readonly<{
        category: Category;
        demo: boolean;
    }>;
    'measurement.write': Readonly<{
        category: Category;
        demo: boolean;
    }>;
    'identity.manage': Readonly<{
        category: Category;
        demo: boolean;
    }>;
    'credentials.rotate-key': Readonly<{
        category: Category;
        demo: boolean;
    }>;
    'platform.maintain': Readonly<{
        category: Category;
        demo: boolean;
    }>;
}>;
export type WorkspaceAction = keyof typeof ACTIONS;
export interface WorkspaceMembership {
    readonly principalId: string;
    readonly sessionId: string;
    readonly expiresAt: string;
    readonly workspaceId: string;
    readonly role: WorkspaceRole;
    /** Canonical lifecycle read with the current membership/session observation. */
    readonly workspaceStatus: WorkspaceStatus;
}
export interface GoogleOAuthAdmissionAdapter {
    /** Server-owned transaction adapters. Call authorize exactly once with fresh
     * immutable facts; resolve only after issuance/consumption COMMIT. */
    issue(request: Request, workspaceId: string, authorize: (facts: WorkspaceMembership) => void): Promise<string>;
    claim(request: Request, authorize: (facts: WorkspaceMembership) => void): Promise<void>;
}
/** A verified agent token's fresh facts in the workspace a call names
 * (identity agentAuthority, epic ro-cvl9): the person it acts for, the
 * client, the person's current role there and the scopes still consented. */
export interface AgentAuthority {
    readonly principalId: string;
    readonly clientId: string;
    readonly workspaceId: string;
    readonly role: WorkspaceRole;
    readonly workspaceStatus: WorkspaceStatus;
    readonly expiresAt: string;
    readonly scopes: readonly string[];
}
export interface StandaloneAuthority {
    readonly principalId: string;
    readonly workspaceId: string;
    readonly workspaceStatus: WorkspaceStatus;
}
export interface ServiceAuthority extends StandaloneAuthority {
    readonly expiresAt: string;
    readonly actions: readonly string[];
}
interface EntryBase {
    /** Opaque server-owned profile identity, not paths, credentials or a request key. */
    readonly profile: symbol;
    /** Test clock; server-owned, never supplied by the request. */
    readonly now?: () => number;
}
export type WorkspaceEntry = EntryBase & ({
    readonly kind: 'hosted';
    readonly trustedOrigin: string;
    readonly membership: (headers: Headers, workspaceId: string) => Promise<WorkspaceMembership | null>;
    readonly googleOAuth?: GoogleOAuthAdmissionAdapter;
    /** Verifies a bearer request's agent token and reads its person's
     * membership in the requested workspace. Without it, a bearer request
     * is refused. */
    readonly agent?: (request: Request, workspaceId: string) => Promise<AgentAuthority | null>;
} | {
    readonly kind: 'standalone';
    /** Authenticate the existing door and resolve the sole workspace; ambiguity denies. */
    readonly authority: (request: Request) => Promise<StandaloneAuthority | null>;
} | {
    readonly kind: 'demo';
    readonly workspaceId: string;
    readonly workspaceStatus: (workspaceId: string) => Promise<WorkspaceStatus | null>;
} | {
    readonly kind: 'service';
    /** Authenticate original service proof and reload its scoped grant on every call. */
    readonly authority: (request: Request) => Promise<ServiceAuthority | null>;
});
export interface WorkspaceSelection {
    readonly requestedWorkspaceId?: string;
    readonly correlationId: string;
}
export interface WorkspaceContext {
    readonly workspaceId: string;
    readonly principalId: string;
    readonly principalKind: 'person' | 'agent' | 'standalone-operator' | 'demo-reader' | 'workspace-service';
    /** Only person contexts carry this from the same fresh membership facts. */
    readonly sessionId?: string;
    /** Only agent contexts carry this: the OAuth client acting for the person. */
    readonly agentClientId?: string;
    readonly entryProfile: WorkspaceEntry['kind'];
    readonly profile: symbol;
    readonly action: WorkspaceAction;
    readonly correlationId: string;
    /** Fresh permission summary for this operation's UI only. A later request
     * still needs new admission; serialized/copied contexts grant nothing. */
    readonly allowedActions: readonly WorkspaceAction[];
}
export interface WorkspaceAdmission {
    /** Await all operation work here. Queued/resumed work requires fresh admission.
     * Same-operation helpers may read required settings without upgrading action. */
    withAdmission<T>(action: WorkspaceAction, selection: WorkspaceSelection, proof: Request, work: (context: WorkspaceContext) => Promise<T>): Promise<T>;
    /** Accept only this factory's live context for the same semantic operation. */
    assertContext(context: unknown, action: WorkspaceAction): asserts context is WorkspaceContext;
    /** Fixed hosted Google entries only. They are not general protocol bypasses. */
    withGoogleStart<T>(correlationId: string, proof: Request, work: (context: WorkspaceContext, state: string) => Promise<T>): Promise<T>;
    withGoogleCallback<T>(correlationId: string, proof: Request, work: (context: WorkspaceContext) => Promise<T>): Promise<T>;
}
export declare class AdmissionRefused extends Error {
    name: string;
    constructor();
}
export declare function createWorkspaceAdmission(input: WorkspaceEntry): WorkspaceAdmission;
export {};
