// Generated by pnpm generate. Edit the sibling .mts source.
import type { WorkflowStepRun } from '../packages/contract/src/workflows.js';
import { type WorkflowRecorder } from './workflow-trace.mjs';
export declare const WORKFLOW_HISTORY_FILE: string;
export declare const WORKFLOW_ACTIVE_FILE: string;
export declare const WORKFLOW_SESSION_ID: string;
export interface WorkflowRunTrace {
    local: boolean;
    run: WorkflowRecorder['run'];
    verdict(outcome: string): 'failed' | 'skipped' | 'succeeded';
    adopt(steps?: WorkflowStepRun[]): void;
    finish(outcome: string): Promise<void>;
}
export interface WorkflowHistory {
    publishHeartbeat(): Promise<void>;
    beginRun(job: string, startedAtMs: number): null | WorkflowRunTrace;
}
/**
 * The workflow history of the installation whose state is under `root`: the
 * home folder for the stack's runner (its code folder links `.local` to home),
 * the installation's own folder for `pnpm start`. The Tower
 * reads the same two files under its home (apps/tower/vite/workflow-history.ts).
 */
export declare function createWorkflowHistory(root: string): WorkflowHistory;
export declare function publishWorkflowHeartbeat(): Promise<void>;
export declare function beginWorkflowRun(job: string, startedAtMs: number): null | WorkflowRunTrace;
/** Bounded tail read; a torn first/last JSONL line is never an invented run. */
export declare function readJsonLines(file: string, maxBytes?: number): Promise<unknown[]>;
