// Generated by pnpm generate. Edit the sibling .mts source.
import type { WorkflowStepDefinition } from '../packages/contract/src/workflows.js';
import { type ScheduledJob } from './scheduled-jobs.mjs';
export interface WorkflowDefinition extends ScheduledJob {
    version: number;
    triggerKind: 'schedule';
    stages: WorkflowStepDefinition[];
}
export declare const WORKFLOW_DEFINITIONS: WorkflowDefinition[];
