// A WORKER CONFIG IN A FOLDER OF ITS OWN: the folder decides which local
// secrets the Worker runs on (beads ro-ujb9.126, ro-ujb9.182).
//
// Wrangler reads a Worker's local secrets from beside the config it is given:
// `.dev.vars` in the config's own folder, else that folder's `.env` files (and
// every variable of the process, when CLOUDFLARE_INCLUDE_PROCESS_ENV is set).
// Neither wrangler nor @cloudflare/vitest-pool-workers has an option that turns
// the `.dev.vars` read off. The pool's `wrangler` option takes a config path and
// an environment, and a missing `.dev.vars.<environment>` falls back to the
// plain file. So the folder is the lever:
//
//   - `pnpm start` writes the checkout's Worker configs into the new
//     installation's folder, beside that installation's own `.dev.vars`
//     (scripts/start.mjs);
//   - the unit tests write them into a new, empty temporary folder
//     (`secretFreeWorkerConfigs`) and switch the `.env` and process reads off
//     (`stopLocalSecretReads`). The ingest suite's Workers pool and the Tower's
//     end-to-end door test then run on the bindings each test declares and
//     nothing else. Before this, both read the checkout's
//     `workers/ingest/.dev.vars`: a real Clarity token merged into a test's
//     expected map, and the assertion diff printed it into the run's log.
//
// Authored TypeScript: `pnpm config:generate` writes the `.mjs` the scripts,
// the ingest suite's vitest config and the Tower's tests import, and the
// `.d.mts` beside it.

import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { stripJsonc } from "./jsonc.mjs";

const REPO_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

/** The two Worker configs, at the same relative paths in every folder as in the checkout. */
export const WORKER_CONFIGS: readonly string[] = Object.freeze([
  path.join("apps", "tower", "wrangler.jsonc"),
  path.join("workers", "ingest", "wrangler.jsonc"),
]);

/**
 * Two wrangler switches that let the shell choose a Worker's local secrets: an
 * environment (`.dev.vars.<environment>`), and every process variable as a
 * binding.
 */
export const WRANGLER_SECRET_SWITCHES: readonly string[] = Object.freeze([
  "CLOUDFLARE_ENV",
  "CLOUDFLARE_INCLUDE_PROCESS_ENV",
]);

/** Wrangler's documented switch for the `.env` read; "false" also skips the process read. */
export const WRANGLER_DOT_ENV_SWITCH: string = "CLOUDFLARE_LOAD_DEV_VARS_FROM_DOT_ENV";

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

/** The checkout's Worker config with every path made absolute, so it works from any folder. */
export function relocatedWorkerConfig(sourceText: string, sourceFile: string): Record<string, unknown> {
  const config: unknown = JSON.parse(stripJsonc(sourceText));
  if (!isRecord(config)) throw new Error(`${sourceFile} is not a Worker config`);
  const dir = path.dirname(sourceFile);
  delete config.$schema;
  if (typeof config.main === "string") config.main = path.resolve(dir, config.main);
  if (config.d1_databases !== undefined &&
      (!Array.isArray(config.d1_databases) || config.d1_databases.length > 0)) {
    throw new Error(`${sourceFile} declares D1; NoticeOS supports Postgres only`);
  }
  return config;
}

/**
 * A Worker config for `pnpm start`'s folder, with its one-line header. Its
 * resources keep the checked-in names, which are a new installation's
 * (scripts/resource-names.mts NEW_INSTALL_NAMES, scripts/new-install-names.test.mjs).
 */
export function workerConfig(sourceText: string, sourceFile: string): string {
  const config = relocatedWorkerConfig(sourceText, sourceFile);
  return `// Generated by pnpm start from ${sourceFile}; replaced on every start.\n${JSON.stringify(config, null, 2)}\n`;
}

export interface SecretFreeWorkerConfigs {
  /** The new folder: the configs and nothing else, so no `.dev.vars` and no `.env`. */
  root: string;
  /** Where the config at this checkout path was written. */
  configPath(relative: string): string;
  /** Deletes the folder. */
  remove(): void;
}

/** The checkout's Worker configs, written into a new, empty folder for a test run. */
export function secretFreeWorkerConfigs({
  checkout = REPO_ROOT,
  parent = os.tmpdir(),
  configs = WORKER_CONFIGS,
}: { checkout?: string; parent?: string; configs?: readonly string[] } = {}): SecretFreeWorkerConfigs {
  const root = mkdtempSync(path.join(parent, "noticeos-test-workers-"));
  for (const relative of configs) {
    const source = path.join(checkout, relative);
    const target = path.join(root, relative);
    mkdirSync(path.dirname(target), { recursive: true });
    const config = relocatedWorkerConfig(readFileSync(source, "utf8"), source);
    writeFileSync(target, `// Written for a test run from ${source}.\n${JSON.stringify(config, null, 2)}\n`);
  }
  return {
    root,
    configPath: (relative) => path.join(root, relative),
    remove: () => rmSync(root, { recursive: true, force: true }),
  };
}

/** Stops wrangler, in this process, reading local secrets from `.env` files or the process itself. */
export function stopLocalSecretReads(env: Record<string, string | undefined> = process.env): void {
  for (const name of WRANGLER_SECRET_SWITCHES) delete env[name];
  env[WRANGLER_DOT_ENV_SWITCH] = "false";
}
