// Generated by pnpm config:generate. Edit the sibling .mts source.
import { type IdentityOptions } from './identity-engine.mjs';
import type { MembershipRole, SessionFacts, WorkspaceStatus } from './identity.mjs';
export declare const WORKSPACE_CHOICES_PAGE_SIZE = 100;
export interface BrowserWorkspaceChoice {
    readonly workspaceId: string;
    readonly displayName: string;
    readonly status: WorkspaceStatus;
    readonly role: MembershipRole;
}
export interface BrowserSessionSnapshot {
    readonly session: SessionFacts;
    readonly workspaces: readonly BrowserWorkspaceChoice[];
    readonly nextCursor: string | null;
    readonly selectedWorkspace: BrowserWorkspaceChoice | null;
}
/** Keyset pages keep responses bounded by membership count. A page cursor is
 * only an ordering marker, not authority. Selection is read in the same SQL
 * snapshot even when it is on another page; it must be active to be selected.
 * A verified person without memberships has an empty list and no selection. */
export declare function readBrowserSession(input: IdentityOptions, headers: Headers, requestedWorkspaceId?: string | null, afterWorkspaceId?: string | null): Promise<BrowserSessionSnapshot | null>;
