// Generated by pnpm generate. Edit the sibling .mts source.
import { type EmailEnrollment } from '../../../scripts/identity-protocol.mjs';
import { type IdentityOptions, type EmailCodeMessage } from './identity-engine.mjs';
export { EMAIL_CODE_PATHS, type EmailEnrollment } from '../../../scripts/identity-protocol.mjs';
export interface EmailCodeOptions extends IdentityOptions {
    /** Supplied by a trusted outer server adapter, never a browser/RPC IP claim. */
    readonly peerAddress: string;
    /** Called only after database commit. No real sender is selected here. */
    readonly deliver: (message: EmailCodeMessage) => Promise<void>;
}
export interface EmailCodeLogin {
    requestCode(request: Request, enrollment?: EmailEnrollment): Promise<Response>;
    verifyCode(request: Request, enrollment?: EmailEnrollment): Promise<Response>;
    logout(request: Request): Promise<Response>;
    close(): Promise<void>;
}
/** Lazy, request-owned lifecycle: original evidence is checked before any
 * connection/query. The trusted peer and fixed action are server facts; caller
 * headers never choose a rate bucket. Close in finally after the last action. */
export declare function openEmailCodeLogin(options: EmailCodeOptions): EmailCodeLogin;
