// Generated by pnpm config:generate. Edit the sibling .mts source.
import { Pool } from 'pg';
import { Kysely, type Transaction } from 'kysely';
import type { AuthContext, BetterAuthPlugin } from '@better-auth/core';
export declare const IDENTITY_ROLE = "noticeos_identity";
export declare const IDENTITY_SCHEMA = "noticeos_identity";
export interface IdentityOptions {
    readonly connectionString: string;
    readonly trustedOrigin: string;
    readonly sessionSecret: string;
}
export declare class IdentityRefused extends Error {
    name: string;
}
export interface EmailCodeMessage {
    readonly email: string;
    readonly code: string;
}
export interface InvitationMessage {
    readonly invitationId: string;
    readonly workspaceId: string;
    readonly email: string;
    readonly role: 'owner' | 'operator' | 'viewer';
    readonly expiresAt: string;
}
export type IdentityDatabase = Record<string, Record<string, unknown>>;
/** Static mappings shared by the maintained engine and schema qualification. */
export declare const IDENTITY_NAMES: {
    readonly user: {
        readonly modelName: "auth_user";
        readonly fields: {
            readonly emailVerified: "email_verified";
            readonly createdAt: "created_at";
            readonly updatedAt: "updated_at";
        };
    };
    readonly session: {
        readonly modelName: "auth_session";
        readonly fields: {
            readonly expiresAt: "expires_at";
            readonly createdAt: "created_at";
            readonly updatedAt: "updated_at";
            readonly ipAddress: "ip_address";
            readonly userAgent: "user_agent";
            readonly userId: "user_id";
        };
    };
    readonly account: {
        readonly modelName: "auth_account";
        readonly fields: {
            readonly accountId: "account_id";
            readonly providerId: "provider_id";
            readonly userId: "user_id";
            readonly accessToken: "access_token";
            readonly refreshToken: "refresh_token";
            readonly idToken: "id_token";
            readonly accessTokenExpiresAt: "access_token_expires_at";
            readonly refreshTokenExpiresAt: "refresh_token_expires_at";
            readonly createdAt: "created_at";
            readonly updatedAt: "updated_at";
        };
    };
    readonly verification: {
        readonly modelName: "auth_verification";
        readonly fields: {
            readonly expiresAt: "expires_at";
            readonly createdAt: "created_at";
            readonly updatedAt: "updated_at";
        };
    };
    readonly organization: {
        readonly organization: {
            readonly modelName: "auth_organization";
            readonly fields: {
                readonly createdAt: "created_at";
            };
        };
        readonly member: {
            readonly modelName: "auth_member";
            readonly fields: {
                readonly organizationId: "organization_id";
                readonly userId: "user_id";
                readonly createdAt: "created_at";
            };
        };
        readonly invitation: {
            readonly modelName: "auth_invitation";
            readonly fields: {
                readonly organizationId: "organization_id";
                readonly expiresAt: "expires_at";
                readonly createdAt: "created_at";
                readonly inviterId: "inviter_id";
            };
        };
        readonly session: {
            readonly fields: {
                readonly activeOrganizationId: "active_organization_id";
            };
        };
    };
};
/** Agent sign-in's maintained tables (epic ro-cvl9; migration 0014): signing
 * keys, OAuth clients, the protected resources, tokens and consents. */
export declare const AGENT_NAMES: {
    readonly jwks: {
        modelName: string;
        fields: Record<"expiresAt" | "createdAt" | "publicKey" | "privateKey" | "alg" | "crv", string>;
    };
    readonly oauth: {
        readonly oauthClient: {
            modelName: string;
            fields: Record<"name" | "createdAt" | "metadata" | "scopes" | "clientId" | "clientSecret" | "clientDiscoveryId" | "disabled" | "skipConsent" | "enableEndSession" | "subjectType" | "clientCredentialsScopes" | "userId" | "updatedAt" | "uri" | "icon" | "contacts" | "tos" | "policy" | "softwareId" | "softwareVersion" | "softwareStatement" | "redirectUris" | "postLogoutRedirectUris" | "backchannelLogoutUri" | "backchannelLogoutSessionRequired" | "tokenEndpointAuthMethod" | "applicationType" | "jwks" | "jwksUri" | "grantTypes" | "responseTypes" | "requirePKCE" | "dpopBoundAccessTokens" | "referenceId", string>;
        };
        readonly oauthResource: {
            modelName: string;
            fields: Record<"name" | "createdAt" | "metadata" | "identifier" | "disabled" | "updatedAt" | "accessTokenTtl" | "refreshTokenTtl" | "signingAlgorithm" | "signingKeyId" | "allowedScopes" | "customClaims" | "dpopBoundAccessTokensRequired" | "policyVersion", string>;
        };
        readonly oauthClientResource: {
            modelName: string;
            fields: Record<"createdAt" | "metadata" | "clientId" | "resourceId", string>;
        };
        readonly oauthRefreshToken: {
            modelName: string;
            fields: Record<"expiresAt" | "createdAt" | "token" | "scopes" | "sessionId" | "clientId" | "userId" | "referenceId" | "authorizationCodeId" | "resources" | "requestedUserInfoClaims" | "revoked" | "rotatedAt" | "rotationReplayResponse" | "rotationReplayExpiresAt" | "authTime" | "confirmation", string>;
        };
        readonly oauthAccessToken: {
            modelName: string;
            fields: Record<"expiresAt" | "createdAt" | "token" | "scopes" | "sessionId" | "clientId" | "userId" | "referenceId" | "authorizationCodeId" | "resources" | "requestedUserInfoClaims" | "revoked" | "confirmation" | "refreshId", string>;
        };
        readonly oauthConsent: {
            modelName: string;
            fields: Record<"createdAt" | "scopes" | "clientId" | "userId" | "updatedAt" | "referenceId" | "resources" | "requestedUserInfoClaims", string>;
        };
        readonly oauthClientAssertion: {
            modelName: string;
            fields: Record<"expiresAt", string>;
        };
    };
};
export declare const UUID: RegExp;
export declare function validateIdentityOptions(input: IdentityOptions): string;
export declare function openIdentityDatabase(input: IdentityOptions): Promise<{
    pool: Pool;
    database: Kysely<IdentityDatabase>;
}>;
interface EngineOptions {
    readonly transaction: boolean;
    readonly emailCode?: true;
    readonly validateSchema?: boolean;
    /** Browser bootstrap is a GET fact read, including expired sessions. */
    readonly readOnlySession?: true;
    readonly peer?: string;
    readonly eligible?: boolean;
    readonly deliver?: (message: EmailCodeMessage) => void;
    /** Capture only. The membership module delivers after its outer commit. */
    readonly invitation?: (message: InvitationMessage) => void;
    /** The OAuth authorization server for agents (agent-sign-in.mts). */
    readonly agents?: true;
}
/** Exported for schema qualification (the 0014 parity proof). */
export declare function agentPlugins(baseURL: string): BetterAuthPlugin[];
interface IdentityEngine {
    readonly $context: Promise<Pick<AuthContext, 'internalAdapter' | 'options' | 'checkSchema'>>;
    handler(request: Request): Promise<Response>;
    readonly api: {
        /** Supported server-only API; the public raw organization handler stays private. */
        addMember(input: {
            body: {
                organizationId: string;
                userId: string;
                role: 'owner';
            };
        }): Promise<{
            id: string;
            organizationId: string;
            userId: string;
            role: string;
        }>;
        getSession(input: {
            headers: Headers;
            query: {
                disableCookieCache: true;
                disableRefresh: true;
            };
        }): Promise<{
            session: {
                id: string;
                expiresAt: Date;
            };
            user: {
                id: string;
            };
        } | null>;
    };
}
export interface IdentityMembershipFacts {
    readonly principalId: string;
    readonly sessionId: string;
    readonly expiresAt: string;
    readonly workspaceId: string;
    readonly role: 'owner' | 'operator' | 'viewer';
    readonly workspaceStatus?: 'active' | 'provisioning' | 'suspended';
}
/** Private fresh fact reader shared by ordinary identity and transaction-bound
 * integration custody. It validates facts, never decides action permission.
 * Locking callers first hold organization then canonical workspace. */
export declare function identityMembership(database: Kysely<IdentityDatabase> | Transaction<IdentityDatabase>, auth: Pick<IdentityEngine, 'api'>, headers: Headers, workspaceId: string, admission: boolean, lock?: boolean): Promise<IdentityMembershipFacts | null>;
/** One configuration for native/Worker facts and transaction-bound login.
 * Schema validation uses the same feature schema, even with limiter execution
 * disabled. No exported product handler exposes the library's other routes. */
export declare function identityEngine(database: Kysely<IdentityDatabase> | Transaction<IdentityDatabase>, input: IdentityOptions, options: EngineOptions): IdentityEngine;
export {};
