// Generated by pnpm config:generate. Edit the sibling .mts source.
import { type IdentityOptions } from './identity-engine.mjs';
export { AGENT_NAMES, IDENTITY_NAMES, IDENTITY_ROLE, IDENTITY_SCHEMA, IdentityRefused, agentPlugins, type IdentityOptions } from './identity-engine.mjs';
export type MembershipRole = 'owner' | 'operator' | 'viewer';
export interface SessionFacts {
    readonly principalId: string;
    readonly sessionId: string;
    readonly expiresAt: string;
}
export interface MembershipFacts extends SessionFacts {
    readonly workspaceId: string;
    readonly role: MembershipRole;
}
export type WorkspaceStatus = 'active' | 'provisioning' | 'suspended';
export interface WorkspaceSummary {
    readonly workspaceId: string;
    readonly displayName: string;
    readonly status: WorkspaceStatus;
}
export interface AdmissionMembershipFacts extends MembershipFacts {
    readonly workspaceStatus: WorkspaceStatus;
}
/** A verified agent access token: the person it acts for,
 * the client, its scopes still consented, and when it expires. */
export interface AgentToken {
    readonly principalId: string;
    readonly clientId: string;
    readonly expiresAt: string;
    readonly scopes: readonly string[];
}
/** The token with its person's fresh membership and lifecycle in one named
 * workspace. A fact, never a grant: admission maps the scopes to actions and
 * bounds them by the role. */
export interface AgentAuthorityFacts extends AgentToken {
    readonly workspaceId: string;
    readonly role: MembershipRole;
    readonly workspaceStatus: WorkspaceStatus;
}
export interface AgentWorkspace {
    readonly workspaceId: string;
    readonly displayName: string;
    readonly role: MembershipRole;
    readonly status: WorkspaceStatus;
}
export interface WorkspaceActor {
    readonly principalId: string;
    readonly displayName: string;
}
export interface Identity {
    /** Fresh verified cookie/session facts, or null. Never a cookie-cache answer. */
    session(headers: Headers): Promise<SessionFacts | null>;
    /** Current membership and unexpired session in one database observation. */
    membership(headers: Headers, workspaceId: string): Promise<MembershipFacts | null>;
    /** Same fresh session/member observation plus canonical lifecycle. Requires
     * the lifecycle migration; neither method grants workspace capabilities. */
    admissionMembership(headers: Headers, workspaceId: string): Promise<AdmissionMembershipFacts | null>;
    /** Internal control-plane fact read. Never expose an arbitrary UUID endpoint;
     * membership choices must first verify session and owned membership. */
    workspaceSummary(workspaceId: string): Promise<WorkspaceSummary | null>;
    /** Private presentation facts, never authority. Call only for an admitted
     * selected workspace; no email/account fields or foreign UUID lookup. The
     * bounded roster refuses over 1,000 members rather than returning a sample. */
    workspaceActors(workspaceId: string): Promise<readonly WorkspaceActor[]>;
    /** The request's agent access token, or null: signed by this deployment's
     * key, issued here for its MCP endpoint, unexpired, and still backed by a
     * live consent and an enabled client. */
    agentToken(request: Request): Promise<AgentToken | null>;
    /** The token plus its person's current membership in this workspace and
     * the workspace's lifecycle, in one observation; null when either lapsed. */
    agentAuthority(request: Request, workspaceId: string): Promise<AgentAuthorityFacts | null>;
    /** The token's person's workspaces, as an agent lists them (at most 100). */
    agentWorkspaces(request: Request): Promise<readonly AgentWorkspace[] | null>;
    /** Idempotent; awaits operations already started and rejects new operations. */
    close(): Promise<void>;
}
/** Open per request; close in finally (or an awaited Worker waitUntil).
 * No fallback URL, active-organization selection or automatic migration. */
export declare function openIdentity(input: IdentityOptions): Promise<Identity>;
