// Generated by pnpm config:generate. Edit the sibling .mts source.
// Private shared maintained engine. Public modules expose facts or fixed login
// actions; the raw library handler and organization administration stay private.
import { Pool } from 'pg';
import { betterAuth } from 'better-auth/minimal';
import { organization, emailOTP } from 'better-auth/plugins';
import { defaultAc, ownerAc } from 'better-auth/plugins/organization/access';
import { createAuthMiddleware, formCsrfMiddleware } from 'better-auth/api';
import { kyselyAdapter } from '@better-auth/kysely-adapter';
import { Kysely, PostgresDialect, sql } from 'kysely';
export const IDENTITY_ROLE = 'noticeos_identity';
export const IDENTITY_SCHEMA = 'noticeos_identity';
export class IdentityRefused extends Error {
    name = 'IdentityRefused';
}
/** Static mappings shared by the maintained engine and schema qualification. */
export const IDENTITY_NAMES = {
    user: { modelName: 'auth_user', fields: { emailVerified: 'email_verified', createdAt: 'created_at', updatedAt: 'updated_at' } },
    session: { modelName: 'auth_session', fields: { expiresAt: 'expires_at', createdAt: 'created_at', updatedAt: 'updated_at', ipAddress: 'ip_address', userAgent: 'user_agent', userId: 'user_id' } },
    account: { modelName: 'auth_account', fields: { accountId: 'account_id', providerId: 'provider_id', userId: 'user_id', accessToken: 'access_token', refreshToken: 'refresh_token', idToken: 'id_token', accessTokenExpiresAt: 'access_token_expires_at', refreshTokenExpiresAt: 'refresh_token_expires_at', createdAt: 'created_at', updatedAt: 'updated_at' } },
    verification: { modelName: 'auth_verification', fields: { expiresAt: 'expires_at', createdAt: 'created_at', updatedAt: 'updated_at' } },
    organization: {
        organization: { modelName: 'auth_organization', fields: { createdAt: 'created_at' } },
        member: { modelName: 'auth_member', fields: { organizationId: 'organization_id', userId: 'user_id', createdAt: 'created_at' } },
        invitation: { modelName: 'auth_invitation', fields: { organizationId: 'organization_id', expiresAt: 'expires_at', createdAt: 'created_at', inviterId: 'inviter_id' } },
        session: { fields: { activeOrganizationId: 'active_organization_id' } },
    },
};
export const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/u;
function origin(value) {
    let parsed;
    try {
        parsed = new URL(value);
    }
    catch {
        throw new IdentityRefused('Identity requires an explicit trusted origin');
    }
    const loopback = parsed.hostname === '127.0.0.1' || parsed.hostname === 'localhost' || parsed.hostname === '[::1]';
    if (parsed.origin !== value || parsed.username || parsed.password || (parsed.protocol !== 'https:' && !(parsed.protocol === 'http:' && loopback))) {
        throw new IdentityRefused('Identity requires an HTTPS origin or a local fixture origin');
    }
    return value;
}
const ROLE_SQL = `SELECT session_user::text AS session_role, current_user::text AS acting_role,
  r.rolsuper OR r.rolbypassrls OR r.rolcreatedb OR r.rolcreaterole OR r.rolreplication AS elevated,
  EXISTS (SELECT 1 FROM pg_catalog.pg_roles other WHERE other.rolname<>current_user
    AND pg_has_role(current_user, other.oid, 'MEMBER')) AS another_role,
  has_schema_privilege(current_user, 'noticeos', 'USAGE') OR
  has_schema_privilege(current_user, 'noticeos_identity', 'CREATE') AS broad_schema
  FROM pg_catalog.pg_roles r WHERE r.rolname=current_user`;
export function validateIdentityOptions(input) {
    const baseURL = origin(input.trustedOrigin);
    if (typeof input.connectionString !== 'string' || input.connectionString.length === 0 || typeof input.sessionSecret !== 'string' || input.sessionSecret.length < 32) {
        throw new IdentityRefused('Identity requires an explicit connection and session secret');
    }
    let connection;
    try {
        connection = new URL(input.connectionString);
    }
    catch {
        throw new IdentityRefused('Identity requires a PostgreSQL connection URL');
    }
    if ((connection.protocol !== 'postgresql:' && connection.protocol !== 'postgres:') || !connection.hostname || !connection.username || connection.pathname.length < 2 || connection.hash) {
        throw new IdentityRefused('Identity requires a PostgreSQL connection URL');
    }
    return baseURL;
}
export async function openIdentityDatabase(input) {
    validateIdentityOptions(input);
    // Request-owned pool. Workers timers cannot unref(), so no allowExitOnIdle.
    const pool = new Pool({ connectionString: input.connectionString, max: 2, connectionTimeoutMillis: 5000, idleTimeoutMillis: 1000 });
    pool.on('error', () => undefined);
    try {
        const { rows } = await pool.query(ROLE_SQL);
        const role = rows[0];
        if (role?.session_role !== IDENTITY_ROLE || role.acting_role !== IDENTITY_ROLE || role.elevated !== false || role.another_role !== false || role.broad_schema !== false) {
            throw new IdentityRefused('Identity must use its separate non-owner runtime role');
        }
        const database = new Kysely({ dialect: new PostgresDialect({ pool }) });
        return { pool, database };
    }
    catch {
        await pool.end();
        throw new IdentityRefused('Identity connection refused');
    }
}
/** Private fresh fact reader shared by ordinary identity and transaction-bound
 * integration custody. It validates facts, never decides action permission.
 * Locking callers first hold organization then canonical workspace. */
export async function identityMembership(database, auth, headers, workspaceId, admission, lock = false) {
    if (!UUID.test(workspaceId))
        throw new IdentityRefused('Membership requires an explicit workspace UUID');
    const result = await auth.api.getSession({ headers, query: { disableCookieCache: true, disableRefresh: true } });
    if (!result)
        return null;
    const response = await sql `
    SELECT m.organization_id AS workspace_id, m.role, s.expires_at${admission ? sql `, w.status` : sql ``}
    FROM noticeos_identity.auth_session s
    JOIN noticeos_identity.auth_member m ON m.user_id=s.user_id
    ${admission ? sql `JOIN LATERAL noticeos_identity.workspace_summary(m.organization_id) w ON w.workspace_id=m.organization_id` : sql ``}
    WHERE s.id=${result.session.id}::uuid AND s.user_id=${result.user.id}::uuid
      AND s.expires_at>clock_timestamp() AND m.organization_id=${workspaceId}::uuid
    ${lock ? sql `FOR SHARE OF s, m` : sql ``}`.execute(database);
    const member = response.rows[0];
    if (!member || (member.role !== 'owner' && member.role !== 'operator' && member.role !== 'viewer'))
        return null;
    if (admission && (!member.status || !['active', 'provisioning', 'suspended'].includes(member.status))) {
        throw new IdentityRefused('Workspace lifecycle is unavailable');
    }
    return Object.freeze({ principalId: result.user.id, sessionId: result.session.id,
        expiresAt: member.expires_at.toISOString(), workspaceId: member.workspace_id, role: member.role,
        ...(admission ? { workspaceStatus: member.status } : {}) });
}
/** One configuration for native/Worker facts and transaction-bound login.
 * Schema validation uses the same feature schema, even with limiter execution
 * disabled. No exported product handler exposes the library's other routes. */
export function identityEngine(database, input, options) {
    const baseURL = validateIdentityOptions(input);
    return betterAuth({
        database: kyselyAdapter(database.withSchema(IDENTITY_SCHEMA), { type: 'postgres', transaction: options.transaction }),
        baseURL, trustedOrigins: [baseURL], secret: input.sessionSecret,
        appName: 'NoticeOS', telemetry: { enabled: false }, logger: { disabled: true },
        advanced: {
            database: { generateId: 'uuid', validateSchema: options.validateSchema },
            ...(options.peer ? { ipAddress: { ipAddressHeaders: ['x-noticeos-trusted-peer'] } } : {}),
        },
        ...(options.emailCode ? { rateLimit: { enabled: Boolean(options.peer) && !options.validateSchema, storage: 'database', modelName: 'auth_rate_limit', fields: { key: 'key', count: 'count', lastRequest: 'last_request' } } } : {}),
        user: IDENTITY_NAMES.user, account: IDENTITY_NAMES.account, verification: IDENTITY_NAMES.verification,
        session: { ...IDENTITY_NAMES.session, cookieCache: { enabled: false },
            ...(options.readOnlySession ? { deferSessionRefresh: true } : {}) },
        plugins: [organization({ allowUserToCreateOrganization: false, requireEmailVerificationOnInvitation: true,
                schema: IDENTITY_NAMES.organization,
                // These configure maintained organization behavior, not NoticeOS action
                // permission. The server's central memberships.manage decision still
                // authorizes every administration transaction before the library runs.
                roles: { owner: ownerAc, operator: defaultAc.newRole({}), viewer: defaultAc.newRole({}) },
                ...(options.invitation ? { sendInvitationEmail: async (message) => {
                        if (message.role !== 'owner' && message.role !== 'operator' && message.role !== 'viewer') {
                            throw new IdentityRefused('Invitation role refused');
                        }
                        options.invitation(Object.freeze({ invitationId: message.id,
                            workspaceId: message.organization.id, email: message.email,
                            role: message.role, expiresAt: message.invitation.expiresAt.toISOString() }));
                    } } : {}),
            }),
            ...(options.emailCode ? [emailOTP({ storeOTP: 'hashed', allowedAttempts: 3, expiresIn: 300,
                    sendVerificationOTP: async (message) => {
                        if (message.type !== 'sign-in' || !options.deliver)
                            throw new IdentityRefused('Identity action unavailable');
                        options.deliver({ email: message.email, code: message.otp });
                    },
                })] : [])],
        hooks: { before: createAuthMiddleware(async (ctx) => {
                if (ctx.path === '/sign-in/email-otp' || ctx.path === '/email-otp/send-verification-otp') {
                    await formCsrfMiddleware(ctx);
                    // Maintained onRequest rate accounting runs before this documented hook.
                    if (options.eligible === false)
                        return ctx.json({ code: 'ENROLLMENT_UNAVAILABLE' }, { status: ctx.path === '/email-otp/send-verification-otp' ? 202 : 400 });
                }
            }) },
    });
}
