// Generated by pnpm generate. Edit the sibling .mts source.
import { type IdentityOptions, type IdentityMembershipFacts } from './identity-engine.mjs';
import { GOOGLE_INTEGRATION_START, GOOGLE_INTEGRATION_CALLBACK } from '../../../scripts/workspace-operations.mjs';
export { GOOGLE_INTEGRATION_START, GOOGLE_INTEGRATION_CALLBACK };
export declare const GOOGLE_INTEGRATION_TTL_MS: number;
export interface GoogleOAuthMembership extends IdentityMembershipFacts {
    readonly workspaceStatus: 'active' | 'provisioning' | 'suspended';
}
export type AuthorizeGoogleOAuth = (facts: GoogleOAuthMembership) => void | Promise<void>;
export interface IntegrationOAuthCustody {
    issueGoogle(request: Request, workspaceId: string, authorize: AuthorizeGoogleOAuth): Promise<string>;
    /** Exact callback only; current initiator/membership/lifecycle and atomic
     * consumption share one transaction. No operational capability runs here. */
    claimGoogleCallback(request: Request, authorize: AuthorizeGoogleOAuth): Promise<void>;
    close(): Promise<void>;
}
/** Lazy request-owned resources; malformed original proof never opens a pool.
 * `authorize` is the server's shared policy callback, never request input. */
export declare function openIntegrationOAuthCustody(input: IdentityOptions): IntegrationOAuthCustody;
/** Platform housekeeping only. No caller-selected namespace or batch size,
 * maintained login verification read, tenant store or provider capability. */
export declare function retireExpiredGoogleOAuth(input: IdentityOptions): Promise<number>;
