// Generated by pnpm generate. Edit the sibling .mts source.
import type { Transaction } from './store.mjs';
/** Evidence only. The receiver authorizes first and supplies fresh person
 * facts; this recorder grants no capability and opens no transaction. */
export interface MutationActor {
    readonly workspaceId: string;
    readonly principalId: string;
    readonly sessionId: string;
}
export type MutationEvent = {
    readonly event: 'asset.create';
    readonly assetId: string;
    readonly subject: Record<string, never>;
} | {
    readonly event: 'asset.column';
    readonly assetId: string;
    readonly subject: {
        readonly column: 'status' | 'sense_only' | 'display_name';
    };
} | {
    readonly event: 'asset.move';
    readonly assetId: string;
    readonly subject: {
        readonly to: string;
        readonly changedCount: number;
    };
} | {
    readonly event: 'decision.set';
    readonly assetId: string;
    readonly subject: {
        readonly kind: 'query' | 'finding';
        readonly key: string;
        readonly status: 'marked' | 'dismissed';
    };
} | {
    readonly event: 'decision.clear';
    readonly assetId: string;
    readonly subject: {
        readonly kind: 'query' | 'finding';
        readonly key: string;
    };
} | {
    readonly event: 'annotation.create';
    readonly assetId: string;
    readonly subject: {
        readonly annotationNumber: string;
        readonly kind: string;
    };
} | {
    readonly event: 'flag.acknowledge' | 'flag.resolve' | 'flag.snooze' | 'flag.unsnooze' | 'flag.tune';
    readonly assetId: string;
    readonly subject: {
        readonly flagNumber: number;
        readonly changedCount: number;
    };
};
/** The event and actor are snapshotted before I/O. Unknown standalone authors
 * stay explicitly unknown; free-form values/notes and request bodies never
 * enter the event-specific metadata envelope. Failure rolls back its caller's
 * effect because both use the same transaction. */
export declare function recordMutation(tx: Transaction, actor: MutationActor | null, input: MutationEvent): Promise<void>;
