// Generated by pnpm generate. Edit the sibling .mts source.
import type { TaskProjectMapping } from './task-directory.mjs';
export interface PlatformProvisioningOptions {
    readonly platformConnectionString: string;
    readonly identityConnectionString: string;
    readonly trustedOrigin: string;
    readonly sessionSecret: string;
    /** Fixed trusted server composition. It verifies the real physical target,
     * checks factory custody in its own realm, and awaits cleanup on cancellation.
     * No readiness boolean or claimed branded result is accepted from a caller.
     */
    readonly verifyProject: (mapping: TaskProjectMapping, budget: {
        readonly signal: AbortSignal;
        readonly deadline: number;
    }) => Promise<void>;
}
export interface PreparedWorkspace {
    readonly workspaceId: string;
    readonly enrollmentId: string;
}
export interface PlatformProvisioning {
    prepare(input: unknown): Promise<PreparedWorkspace>;
    activate(input: unknown): Promise<PreparedWorkspace>;
    close(): Promise<void>;
}
export declare class PlatformProvisioningRefused extends Error {
    name: string;
    constructor();
}
/** Lazy server composition. All command fields/defaults are captured before I/O.
 * Caller transport and platform-operator authorization are separate entry work.
 */
export declare function openPlatformProvisioning(input: PlatformProvisioningOptions): PlatformProvisioning;
