// Generated by pnpm config:generate. Edit the sibling .mts source.
export interface WorkspaceServiceFacts {
    readonly principalId: string;
    readonly workspaceId: string;
    readonly workspaceStatus: 'active' | 'provisioning' | 'suspended';
    readonly expiresAt: string;
    /** Untrusted stored names. Central admission validates its released catalog. */
    readonly actions: readonly string[];
}
export interface WorkspaceServiceGrant {
    facts(): Promise<WorkspaceServiceFacts | null>;
    close(): Promise<void>;
}
export declare class ServiceGrantRefused extends Error {
    name: string;
}
export declare function openWorkspaceServiceGrant(options: {
    readonly connectionString: string;
    readonly principalId: string;
    readonly workspaceId: string;
}): WorkspaceServiceGrant;
