// Generated by pnpm config:generate. Edit the sibling .mts source.
/** The role every transaction must be connected as (db/postgres/roles.sql). */
export declare const APPLICATION_ROLE = "noticeos_app";
/** The per-transaction setting forced row security reads (0001_baseline.sql). */
export declare const WORKSPACE_SETTING = "noticeos.workspace_id";
/** Connections one store opens at most, unless told otherwise. */
export declare const DEFAULT_MAX_CONNECTIONS = 5;
/** A value a statement's parameter may carry (see the header for each rule). */
export type SqlValue = string | number | bigint | boolean | Date | Uint8Array | null | readonly SqlValue[];
/** One row: column name → value, parsed by the rules in the header. */
export type Row = Record<string, unknown>;
/** The statements `work` runs, all inside its one transaction. */
export interface Transaction {
    /** The workspace this transaction acts for, for statements that bind it. */
    readonly workspaceId: string;
    /** One statement; its rows. */
    query<R extends Row = Row>(sql: string, params?: readonly SqlValue[]): Promise<R[]>;
    /** One statement; how many rows it inserted, changed or removed. */
    execute(sql: string, params?: readonly SqlValue[]): Promise<number>;
}
export interface TransactionOptions {
    /** Open the transaction READ ONLY: a reader that cannot write by mistake. */
    readonly readOnly?: boolean;
}
export interface PostgresStore {
    /** The installation's one workspace id, named by the store; see the header.
     * Throws NoSingleWorkspace, before any transaction opens, when the store holds
     * none or several. */
    onlyWorkspace(): Promise<string>;
    /** Run `work` in one transaction that names `workspaceId`; see the header. */
    inWorkspace<T>(workspaceId: string, work: (tx: Transaction) => Promise<T>, options?: TransactionOptions): Promise<T>;
    /** Close every connection. A closed store opens no more transactions. */
    close(): Promise<void>;
}
export interface StoreOptions {
    /** Connections open at most (default 5). */
    readonly maxConnections?: number;
}
/** The helper refused: nothing was sent, or what was sent is rolled back. */
export declare class TransactionRefused extends Error {
    name: string;
}
/** The transaction did not commit, although `work` returned: a statement failed
 * (and `work` went on), or Postgres ended it with ROLLBACK. Nothing was kept. */
export declare class TransactionRolledBack extends Error {
    name: string;
}
/** The store holds no workspace yet, or several: it names no only workspace,
 * and no transaction was opened. A new installation creates its one workspace
 * once, at its bootstrap (db/postgres/README.md); an installation with several
 * names the workspace of each request instead. */
export declare class NoSingleWorkspace extends TransactionRefused {
    name: string;
}
type Parse = (text: string) => unknown;
/** The one parser table every statement's results go through. */
export declare function exactTypeParser(oid: number, format?: string): Parse;
declare const EXACT_TYPES: {
    getTypeParser: typeof exactTypeParser;
};
/**
 * An instant as JavaScript writes one — `Date#toISOString()`, milliseconds and
 * `Z` — from the form this helper reads (`…:03.456789Z`). For a module whose
 * callers compare instants as strings with ones JavaScript made: the two forms
 * of one instant do not compare equal, or even in order, as strings. An
 * instant JavaScript wrote comes back unchanged; a server-made one
 * (`DEFAULT now()`) loses its microseconds. Anything that is not an instant
 * is refused.
 */
export declare function javascriptInstant(instant: string): string;
/** What a statement returns, as the driver reports it. */
export interface ClientResult {
    readonly rows: unknown[];
    readonly rowCount: number | null;
    readonly command: string;
}
/** One statement for the driver: SQL, parameters, the parser table, and (for
 * work's statements) the extended protocol, which takes one statement only. */
export interface ClientQuery {
    readonly text: string;
    readonly values?: unknown[];
    readonly types: typeof EXACT_TYPES;
    readonly queryMode?: 'extended';
}
/** One held connection: a node-postgres client, or anything that answers alike. */
export interface QueryClient {
    query(query: ClientQuery): Promise<ClientResult | ClientResult[]>;
}
/**
 * The transaction `inWorkspace` runs, on a connection the caller holds. A store
 * calls it with a pooled connection; a proof calls it with its own, to look at
 * the connection afterwards.
 */
export declare function runInWorkspace<T>(client: QueryClient, workspaceId: string, work: (tx: Transaction) => Promise<T>, options?: TransactionOptions): Promise<T>;
/**
 * The workspace the store names as its only one, asked on a connection the
 * caller holds: one statement, outside any transaction. Throws
 * NoSingleWorkspace when the store holds none or several, and refuses a
 * connection that is not the application role, like `runInWorkspace`.
 */
export declare function findOnlyWorkspace(client: QueryClient): Promise<string>;
/** A store on `connectionString` (a Worker: its Hyperdrive binding's). */
export declare function openStore(connectionString: string, options?: StoreOptions): PostgresStore;
/** The store one call works in: one workspace, a transaction per unit of work. */
export interface WorkspaceStore {
    /** Where the store is — host, port and database, never a credential — for
     * a cache key or a message. */
    readonly where: string;
    /** The workspace this store acts for: the one the caller named, or the
     * store's only one, asked once. */
    workspaceId(): Promise<string>;
    /** `work` in one READ ONLY transaction in the workspace. */
    read<T>(work: (tx: Transaction) => Promise<T>): Promise<T>;
    /** `work` in one transaction in the workspace, committed whole or not at all. */
    write<T>(work: (tx: Transaction) => Promise<T>): Promise<T>;
    /** Close every connection; a closed store runs no more work. */
    close(): Promise<void>;
}
export interface WorkspaceStoreOptions extends StoreOptions {
    /** The workspace to act for, where an installation has several; otherwise the store's only one. */
    readonly workspaceId?: string;
}
/** Host, port and database of a connection string, never its credential. */
export declare function storeLocation(connectionString: string): string;
/** A Worker's Hyperdrive binding, as far as a call's store reads it. */
export interface StoreBinding {
    readonly connectionString: string;
}
/** The part of a Worker's execution context a call's store needs. */
export interface CallContext {
    waitUntil(promise: Promise<unknown>): void;
}
/** A direct connection selected by server deployment code, never a request. */
export interface DirectPostgresTransport {
    readonly kind: 'direct';
    readonly connectionString: string;
}
/** Inputs supplied after the server has authorized this operation. This
 * structural type and its workspace UUID do not establish authorization. */
export interface HostedStoreCall {
    readonly transport: DirectPostgresTransport;
    readonly workspace: {
        readonly workspaceId: string;
    };
}
/**
 * `work` with a store opened for this call alone on `binding` (a Worker's
 * POSTGRES Hyperdrive binding), closed once `work` has finished, through
 * `ctx.waitUntil`. The whole lifecycle of a Worker's store: a connection may
 * not outlive the request that opened it, and Hyperdrive pools behind the
 * binding. With no binding the store refuses each unit of work, naming why,
 * so a call that never reads the store still runs.
 */
export declare function withWorkspaceStore<T>(binding: StoreBinding | undefined, ctx: CallContext, work: (store: WorkspaceStore) => Promise<T>): Promise<T>;
/** The caller must authenticate and authorize the operation before calling.
 * This helper validates shape, not authority. It accepts only an explicit
 * server-selected direct transport and workspace; it never discovers the sole
 * workspace or reads an ambient address. Invalid inputs refuse before work or
 * any connection, without putting supplied values in the error. */
export declare function withHostedWorkspaceStore<T>(call: HostedStoreCall, ctx: CallContext, work: (store: WorkspaceStore) => Promise<T>): Promise<T>;
/** A WorkspaceStore on `connectionString` (a Worker: its Hyperdrive binding's). */
export declare function openWorkspaceStore(connectionString: string, options?: WorkspaceStoreOptions): WorkspaceStore;
export {};
