// Generated by pnpm config:generate. Edit the sibling .mts source.
import type { TaskProjectMapping } from './task-directory.mjs';
export interface TaskCatalogSetup {
    configure(input: unknown): Promise<void>;
    close(): Promise<void>;
}
export declare class TaskCatalogRefused extends Error {
    name: string;
    constructor();
}
export declare function openTaskCatalogSetup(options: {
    readonly connectionString: string;
    /** Verify and assert factory custody in the same realm. Never return a boolean. */
    readonly verifyProject: (mapping: TaskProjectMapping, budget: {
        readonly signal: AbortSignal;
        readonly deadline: number;
        readonly expectedPrefix: string;
    }) => Promise<void>;
}): TaskCatalogSetup;
